window.esdocSearchIndex = [
  [
    "rx-scheduler/src/async.js~asyncscheduler",
    "class/src/async.js~AsyncScheduler.html",
    "<span>AsyncScheduler</span> <span class=\"search-result-import-path\">rx-scheduler/src/async.js</span>",
    "class"
  ],
  [
    "rx-scheduler/src/current.js~currentscheduler",
    "class/src/current.js~CurrentScheduler.html",
    "<span>CurrentScheduler</span> <span class=\"search-result-import-path\">rx-scheduler/src/current.js</span>",
    "class"
  ],
  [
    "rx-scheduler/src/immediate.browser.js~immediatescheduler",
    "class/src/immediate.browser.js~ImmediateScheduler.html",
    "<span>ImmediateScheduler</span> <span class=\"search-result-import-path\">rx-scheduler/src/immediate.browser.js</span>",
    "class"
  ],
  [
    "rx-scheduler/src/immediate.node.js~immediatescheduler",
    "class/src/immediate.node.js~ImmediateScheduler.html",
    "<span>ImmediateScheduler</span> <span class=\"search-result-import-path\">rx-scheduler/src/immediate.node.js</span>",
    "class"
  ],
  [
    "rx-scheduler/src/pool.browser.js~poolscheduler",
    "class/src/pool.browser.js~PoolScheduler.html",
    "<span>PoolScheduler</span> <span class=\"search-result-import-path\">rx-scheduler/src/pool.browser.js</span>",
    "class"
  ],
  [
    "rx-scheduler/src/index.browser.js~scheduler",
    "class/src/index.browser.js~Scheduler.html",
    "<span>Scheduler</span> <span class=\"search-result-import-path\">rx-scheduler/src/index.browser.js</span>",
    "class"
  ],
  [
    "rx-scheduler/src/index.node.js~scheduler",
    "class/src/index.node.js~Scheduler.html",
    "<span>Scheduler</span> <span class=\"search-result-import-path\">rx-scheduler/src/index.node.js</span>",
    "class"
  ],
  [
    "rx-scheduler/src/scheduler-interface.js~schedulerinterface",
    "class/src/scheduler-interface.js~SchedulerInterface.html",
    "<span>SchedulerInterface</span> <span class=\"search-result-import-path\">rx-scheduler/src/scheduler-interface.js</span>",
    "class"
  ],
  [
    "rx-scheduler/src/tick.js~tickscheduler",
    "class/src/tick.js~TickScheduler.html",
    "<span>TickScheduler</span> <span class=\"search-result-import-path\">rx-scheduler/src/tick.js</span>",
    "class"
  ],
  [
    "rx-scheduler/src/timeout.js~timeoutscheduler",
    "class/src/timeout.js~TimeoutScheduler.html",
    "<span>TimeoutScheduler</span> <span class=\"search-result-import-path\">rx-scheduler/src/timeout.js</span>",
    "class"
  ],
  [
    "rx-scheduler/src/worker.browser.js~workerscheduler",
    "class/src/worker.browser.js~WorkerScheduler.html",
    "<span>WorkerScheduler</span> <span class=\"search-result-import-path\">rx-scheduler/src/worker.browser.js</span>",
    "class"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber15",
    "Scheduler",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber236",
    "Scheduler #async",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber305",
    "Scheduler #async #delay",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber325",
    "Scheduler #async #delay should execute after current thread",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber333",
    "Scheduler #async #delay should execute after tick",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber349",
    "Scheduler #async #delay should execute before immediate",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber341",
    "Scheduler #async #delay should execute before timeout",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber309",
    "Scheduler #async #delay should return a Cancellable",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber317",
    "Scheduler #async #delay should return a cancelled Cancellable if first arg is not a function.",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber252",
    "Scheduler #async #schedule",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber272",
    "Scheduler #async #schedule should execute after current thread",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber280",
    "Scheduler #async #schedule should execute after tick",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber296",
    "Scheduler #async #schedule should execute before immediate",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber288",
    "Scheduler #async #schedule should execute before timeout",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber256",
    "Scheduler #async #schedule should return a Cancellable",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber264",
    "Scheduler #async #schedule should return a cancelled Cancellable if first arg is not a function.",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber246",
    "Scheduler #async should return a AsyncScheduler",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber240",
    "Scheduler #async should return a SchedulerInterface",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber19",
    "Scheduler #current",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber59",
    "Scheduler #current #delay",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber87",
    "Scheduler #current #delay should execute before async",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber103",
    "Scheduler #current #delay should execute before immediate",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber79",
    "Scheduler #current #delay should execute before tick",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber95",
    "Scheduler #current #delay should execute before timeout",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber63",
    "Scheduler #current #delay should return a Cancellable",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber71",
    "Scheduler #current #delay should return a cancelled Cancellable if first arg is not a function.",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber51",
    "Scheduler #current #schedule",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber52",
    "Scheduler #current #schedule should return a Cancellable.",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber23",
    "Scheduler #current should return a Cancellable",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber45",
    "Scheduler #current should return a CurrentScheduler",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber39",
    "Scheduler #current should return a SchedulerInterface",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber31",
    "Scheduler #current should return a cancelled Cancellable if first arg is not a function.",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber113",
    "Scheduler #immediate",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber182",
    "Scheduler #immediate #delay",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber218",
    "Scheduler #immediate #delay should execute after async",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber202",
    "Scheduler #immediate #delay should execute after current thread",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber210",
    "Scheduler #immediate #delay should execute after tick",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber226",
    "Scheduler #immediate #delay should execute after timeout",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber186",
    "Scheduler #immediate #delay should return a Cancellable",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber194",
    "Scheduler #immediate #delay should return a cancelled Cancellable if first arg is not a function.",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber129",
    "Scheduler #immediate #schedule",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber165",
    "Scheduler #immediate #schedule should execute after async",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber149",
    "Scheduler #immediate #schedule should execute after current thread",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber157",
    "Scheduler #immediate #schedule should execute after tick",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber173",
    "Scheduler #immediate #schedule should execute after timeout",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber133",
    "Scheduler #immediate #schedule should return a Cancellable",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber141",
    "Scheduler #immediate #schedule should return a cancelled Cancellable if first arg is not a function.",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber123",
    "Scheduler #immediate should return a ImmediateScheduler",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber117",
    "Scheduler #immediate should return a SchedulerInterface",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber482",
    "Scheduler #tick",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber535",
    "Scheduler #tick #delay",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber555",
    "Scheduler #tick #delay should execute after current thread",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber563",
    "Scheduler #tick #delay should execute before async",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber579",
    "Scheduler #tick #delay should execute before immediate",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber571",
    "Scheduler #tick #delay should execute before timeout",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber539",
    "Scheduler #tick #delay should return a Cancellable",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber547",
    "Scheduler #tick #delay should return a cancelled Cancellable if first arg is not a function.",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber498",
    "Scheduler #tick #schedule",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber502",
    "Scheduler #tick #schedule should execute after current thread",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber510",
    "Scheduler #tick #schedule should execute before async",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber526",
    "Scheduler #tick #schedule should execute before immediate",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber518",
    "Scheduler #tick #schedule should execute before timeout",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber486",
    "Scheduler #tick should return a SchedulerInterface",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber492",
    "Scheduler #tick should return a TickScheduler",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber359",
    "Scheduler #timeout",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber428",
    "Scheduler #timeout #delay",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber464",
    "Scheduler #timeout #delay should execute after async",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber448",
    "Scheduler #timeout #delay should execute after current thread",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber456",
    "Scheduler #timeout #delay should execute after tick",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber472",
    "Scheduler #timeout #delay should execute before immediate",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber432",
    "Scheduler #timeout #delay should return a Cancellable",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber440",
    "Scheduler #timeout #delay should return a cancelled Cancellable if first arg is not a function.",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber375",
    "Scheduler #timeout #schedule",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber411",
    "Scheduler #timeout #schedule should execute after async",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber395",
    "Scheduler #timeout #schedule should execute after current thread",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber403",
    "Scheduler #timeout #schedule should execute after tick",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber419",
    "Scheduler #timeout #schedule should execute before immediate",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber379",
    "Scheduler #timeout #schedule should return a Cancellable",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber387",
    "Scheduler #timeout #schedule should return a cancelled Cancellable if first arg is not a function.",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber363",
    "Scheduler #timeout should return a SchedulerInterface",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber369",
    "Scheduler #timeout should return a TimeoutScheduler",
    "test"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/async.js",
    "file/src/async.js.html",
    "src/async.js",
    "file"
  ],
  [
    "src/async.js~asyncscheduler#delay",
    "class/src/async.js~AsyncScheduler.html#instance-method-delay",
    "src/async.js~AsyncScheduler#delay",
    "method"
  ],
  [
    "src/async.js~asyncscheduler#schedule",
    "class/src/async.js~AsyncScheduler.html#instance-method-schedule",
    "src/async.js~AsyncScheduler#schedule",
    "method"
  ],
  [
    "src/async.js~asyncscheduler.instance",
    "class/src/async.js~AsyncScheduler.html#static-get-instance",
    "src/async.js~AsyncScheduler.instance",
    "member"
  ],
  [
    "src/current.js",
    "file/src/current.js.html",
    "src/current.js",
    "file"
  ],
  [
    "src/current.js~currentscheduler#delay",
    "class/src/current.js~CurrentScheduler.html#instance-method-delay",
    "src/current.js~CurrentScheduler#delay",
    "method"
  ],
  [
    "src/current.js~currentscheduler#schedule",
    "class/src/current.js~CurrentScheduler.html#instance-method-schedule",
    "src/current.js~CurrentScheduler#schedule",
    "method"
  ],
  [
    "src/current.js~currentscheduler.instance",
    "class/src/current.js~CurrentScheduler.html#static-get-instance",
    "src/current.js~CurrentScheduler.instance",
    "member"
  ],
  [
    "src/immediate.browser.js",
    "file/src/immediate.browser.js.html",
    "src/immediate.browser.js",
    "file"
  ],
  [
    "src/immediate.browser.js~immediatescheduler#delay",
    "class/src/immediate.browser.js~ImmediateScheduler.html#instance-method-delay",
    "src/immediate.browser.js~ImmediateScheduler#delay",
    "method"
  ],
  [
    "src/immediate.browser.js~immediatescheduler#schedule",
    "class/src/immediate.browser.js~ImmediateScheduler.html#instance-method-schedule",
    "src/immediate.browser.js~ImmediateScheduler#schedule",
    "method"
  ],
  [
    "src/immediate.browser.js~immediatescheduler.instance",
    "class/src/immediate.browser.js~ImmediateScheduler.html#static-get-instance",
    "src/immediate.browser.js~ImmediateScheduler.instance",
    "member"
  ],
  [
    "src/immediate.node.js",
    "file/src/immediate.node.js.html",
    "src/immediate.node.js",
    "file"
  ],
  [
    "src/immediate.node.js~immediatescheduler#delay",
    "class/src/immediate.node.js~ImmediateScheduler.html#instance-method-delay",
    "src/immediate.node.js~ImmediateScheduler#delay",
    "method"
  ],
  [
    "src/immediate.node.js~immediatescheduler#schedule",
    "class/src/immediate.node.js~ImmediateScheduler.html#instance-method-schedule",
    "src/immediate.node.js~ImmediateScheduler#schedule",
    "method"
  ],
  [
    "src/immediate.node.js~immediatescheduler.instance",
    "class/src/immediate.node.js~ImmediateScheduler.html#static-get-instance",
    "src/immediate.node.js~ImmediateScheduler.instance",
    "member"
  ],
  [
    "src/index.browser.js",
    "file/src/index.browser.js.html",
    "src/index.browser.js",
    "file"
  ],
  [
    "src/index.browser.js~cancellable",
    "https://lxsmnsyc.github.io/rx-cancellable/",
    "src/index.browser.js~Cancellable",
    "external"
  ],
  [
    "src/index.browser.js~scheduler.async",
    "class/src/index.browser.js~Scheduler.html#static-get-async",
    "src/index.browser.js~Scheduler.async",
    "member"
  ],
  [
    "src/index.browser.js~scheduler.current",
    "class/src/index.browser.js~Scheduler.html#static-get-current",
    "src/index.browser.js~Scheduler.current",
    "member"
  ],
  [
    "src/index.browser.js~scheduler.immediate",
    "class/src/index.browser.js~Scheduler.html#static-get-immediate",
    "src/index.browser.js~Scheduler.immediate",
    "member"
  ],
  [
    "src/index.browser.js~scheduler.interface",
    "class/src/index.browser.js~Scheduler.html#static-get-interface",
    "src/index.browser.js~Scheduler.interface",
    "member"
  ],
  [
    "src/index.browser.js~scheduler.pool",
    "class/src/index.browser.js~Scheduler.html#static-get-pool",
    "src/index.browser.js~Scheduler.pool",
    "member"
  ],
  [
    "src/index.browser.js~scheduler.timeout",
    "class/src/index.browser.js~Scheduler.html#static-get-timeout",
    "src/index.browser.js~Scheduler.timeout",
    "member"
  ],
  [
    "src/index.browser.js~scheduler.worker",
    "class/src/index.browser.js~Scheduler.html#static-get-worker",
    "src/index.browser.js~Scheduler.worker",
    "member"
  ],
  [
    "src/index.node.js",
    "file/src/index.node.js.html",
    "src/index.node.js",
    "file"
  ],
  [
    "src/index.node.js~cancellable",
    "https://lxsmnsyc.github.io/rx-cancellable/",
    "src/index.node.js~Cancellable",
    "external"
  ],
  [
    "src/index.node.js~scheduler.async",
    "class/src/index.node.js~Scheduler.html#static-get-async",
    "src/index.node.js~Scheduler.async",
    "member"
  ],
  [
    "src/index.node.js~scheduler.current",
    "class/src/index.node.js~Scheduler.html#static-get-current",
    "src/index.node.js~Scheduler.current",
    "member"
  ],
  [
    "src/index.node.js~scheduler.immediate",
    "class/src/index.node.js~Scheduler.html#static-get-immediate",
    "src/index.node.js~Scheduler.immediate",
    "member"
  ],
  [
    "src/index.node.js~scheduler.interface",
    "class/src/index.node.js~Scheduler.html#static-get-interface",
    "src/index.node.js~Scheduler.interface",
    "member"
  ],
  [
    "src/index.node.js~scheduler.tick",
    "class/src/index.node.js~Scheduler.html#static-get-tick",
    "src/index.node.js~Scheduler.tick",
    "member"
  ],
  [
    "src/index.node.js~scheduler.timeout",
    "class/src/index.node.js~Scheduler.html#static-get-timeout",
    "src/index.node.js~Scheduler.timeout",
    "member"
  ],
  [
    "src/pool.browser.js",
    "file/src/pool.browser.js.html",
    "src/pool.browser.js",
    "file"
  ],
  [
    "src/pool.browser.js~poolscheduler#delay",
    "class/src/pool.browser.js~PoolScheduler.html#instance-method-delay",
    "src/pool.browser.js~PoolScheduler#delay",
    "method"
  ],
  [
    "src/pool.browser.js~poolscheduler#schedule",
    "class/src/pool.browser.js~PoolScheduler.html#instance-method-schedule",
    "src/pool.browser.js~PoolScheduler#schedule",
    "method"
  ],
  [
    "src/pool.browser.js~poolscheduler.instance",
    "class/src/pool.browser.js~PoolScheduler.html#static-get-instance",
    "src/pool.browser.js~PoolScheduler.instance",
    "member"
  ],
  [
    "src/scheduler-interface.js",
    "file/src/scheduler-interface.js.html",
    "src/scheduler-interface.js",
    "file"
  ],
  [
    "src/scheduler-interface.js~schedulerinterface#delay",
    "class/src/scheduler-interface.js~SchedulerInterface.html#instance-method-delay",
    "src/scheduler-interface.js~SchedulerInterface#delay",
    "method"
  ],
  [
    "src/scheduler-interface.js~schedulerinterface#schedule",
    "class/src/scheduler-interface.js~SchedulerInterface.html#instance-method-schedule",
    "src/scheduler-interface.js~SchedulerInterface#schedule",
    "method"
  ],
  [
    "src/tick.js",
    "file/src/tick.js.html",
    "src/tick.js",
    "file"
  ],
  [
    "src/tick.js~tickscheduler#delay",
    "class/src/tick.js~TickScheduler.html#instance-method-delay",
    "src/tick.js~TickScheduler#delay",
    "method"
  ],
  [
    "src/tick.js~tickscheduler#schedule",
    "class/src/tick.js~TickScheduler.html#instance-method-schedule",
    "src/tick.js~TickScheduler#schedule",
    "method"
  ],
  [
    "src/tick.js~tickscheduler.instance",
    "class/src/tick.js~TickScheduler.html#static-get-instance",
    "src/tick.js~TickScheduler.instance",
    "member"
  ],
  [
    "src/timeout.js",
    "file/src/timeout.js.html",
    "src/timeout.js",
    "file"
  ],
  [
    "src/timeout.js~timeoutscheduler#delay",
    "class/src/timeout.js~TimeoutScheduler.html#instance-method-delay",
    "src/timeout.js~TimeoutScheduler#delay",
    "method"
  ],
  [
    "src/timeout.js~timeoutscheduler#schedule",
    "class/src/timeout.js~TimeoutScheduler.html#instance-method-schedule",
    "src/timeout.js~TimeoutScheduler#schedule",
    "method"
  ],
  [
    "src/timeout.js~timeoutscheduler.instance",
    "class/src/timeout.js~TimeoutScheduler.html#static-get-instance",
    "src/timeout.js~TimeoutScheduler.instance",
    "member"
  ],
  [
    "src/utils.js",
    "file/src/utils.js.html",
    "src/utils.js",
    "file"
  ],
  [
    "src/worker.browser.js",
    "file/src/worker.browser.js.html",
    "src/worker.browser.js",
    "file"
  ],
  [
    "src/worker.browser.js~workerscheduler#delay",
    "class/src/worker.browser.js~WorkerScheduler.html#instance-method-delay",
    "src/worker.browser.js~WorkerScheduler#delay",
    "method"
  ],
  [
    "src/worker.browser.js~workerscheduler#schedule",
    "class/src/worker.browser.js~WorkerScheduler.html#instance-method-schedule",
    "src/worker.browser.js~WorkerScheduler#schedule",
    "method"
  ],
  [
    "src/worker.browser.js~workerscheduler.instance",
    "class/src/worker.browser.js~WorkerScheduler.html#static-get-instance",
    "src/worker.browser.js~WorkerScheduler.instance",
    "member"
  ],
  [
    "test/index.js",
    "test-file/test/index.js.html",
    "test/index.js",
    "testFile"
  ]
]