window.esdocSearchIndex = [
  [
    "rx-scheduler/src/async.js~asyncscheduler",
    "class/src/async.js~AsyncScheduler.html",
    "<span>AsyncScheduler</span> <span class=\"search-result-import-path\">rx-scheduler/src/async.js</span>",
    "class"
  ],
  [
    "rx-scheduler/src/current.js~currentscheduler",
    "class/src/current.js~CurrentScheduler.html",
    "<span>CurrentScheduler</span> <span class=\"search-result-import-path\">rx-scheduler/src/current.js</span>",
    "class"
  ],
  [
    "rx-scheduler/src/immediate.browser.js~immediatescheduler",
    "class/src/immediate.browser.js~ImmediateScheduler.html",
    "<span>ImmediateScheduler</span> <span class=\"search-result-import-path\">rx-scheduler/src/immediate.browser.js</span>",
    "class"
  ],
  [
    "rx-scheduler/src/immediate.node.js~immediatescheduler",
    "class/src/immediate.node.js~ImmediateScheduler.html",
    "<span>ImmediateScheduler</span> <span class=\"search-result-import-path\">rx-scheduler/src/immediate.node.js</span>",
    "class"
  ],
  [
    "rx-scheduler/src/index.browser.js~scheduler",
    "class/src/index.browser.js~Scheduler.html",
    "<span>Scheduler</span> <span class=\"search-result-import-path\">rx-scheduler/src/index.browser.js</span>",
    "class"
  ],
  [
    "rx-scheduler/src/index.node.js~scheduler",
    "class/src/index.node.js~Scheduler.html",
    "<span>Scheduler</span> <span class=\"search-result-import-path\">rx-scheduler/src/index.node.js</span>",
    "class"
  ],
  [
    "rx-scheduler/src/scheduler-interface.js~schedulerinterface",
    "class/src/scheduler-interface.js~SchedulerInterface.html",
    "<span>SchedulerInterface</span> <span class=\"search-result-import-path\">rx-scheduler/src/scheduler-interface.js</span>",
    "class"
  ],
  [
    "rx-scheduler/src/tick.js~tickscheduler",
    "class/src/tick.js~TickScheduler.html",
    "<span>TickScheduler</span> <span class=\"search-result-import-path\">rx-scheduler/src/tick.js</span>",
    "class"
  ],
  [
    "rx-scheduler/src/timeout.js~timeoutscheduler",
    "class/src/timeout.js~TimeoutScheduler.html",
    "<span>TimeoutScheduler</span> <span class=\"search-result-import-path\">rx-scheduler/src/timeout.js</span>",
    "class"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber15",
    "Scheduler",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber202",
    "Scheduler #async",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber255",
    "Scheduler #async #delay",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber275",
    "Scheduler #async #delay should execute after current thread",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber283",
    "Scheduler #async #delay should execute after tick",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber299",
    "Scheduler #async #delay should execute before immediate",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber291",
    "Scheduler #async #delay should execute before timeout",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber259",
    "Scheduler #async #delay should return an AbortController",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber267",
    "Scheduler #async #delay should return an aborted AbortControler if first arg is not a function.",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber218",
    "Scheduler #async #schedule",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber222",
    "Scheduler #async #schedule should execute after current thread",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber230",
    "Scheduler #async #schedule should execute after tick",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber246",
    "Scheduler #async #schedule should execute before immediate",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber238",
    "Scheduler #async #schedule should execute before timeout",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber212",
    "Scheduler #async should return a AsyncScheduler",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber206",
    "Scheduler #async should return a SchedulerInterface",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber19",
    "Scheduler #current",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber41",
    "Scheduler #current #delay",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber69",
    "Scheduler #current #delay should execute before async",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber85",
    "Scheduler #current #delay should execute before immediate",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber61",
    "Scheduler #current #delay should execute before tick",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber77",
    "Scheduler #current #delay should execute before timeout",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber45",
    "Scheduler #current #delay should return an AbortController",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber53",
    "Scheduler #current #delay should return an aborted AbortControler if first arg is not a function.",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber35",
    "Scheduler #current #schedule",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber29",
    "Scheduler #current should return a CurrentScheduler",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber23",
    "Scheduler #current should return a SchedulerInterface",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber95",
    "Scheduler #immediate",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber148",
    "Scheduler #immediate #delay",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber184",
    "Scheduler #immediate #delay should execute after async",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber168",
    "Scheduler #immediate #delay should execute after current thread",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber176",
    "Scheduler #immediate #delay should execute after tick",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber192",
    "Scheduler #immediate #delay should execute after timeout",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber152",
    "Scheduler #immediate #delay should return an AbortController",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber160",
    "Scheduler #immediate #delay should return an aborted AbortControler if first arg is not a function.",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber111",
    "Scheduler #immediate #schedule",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber131",
    "Scheduler #immediate #schedule should execute after async",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber115",
    "Scheduler #immediate #schedule should execute after current thread",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber123",
    "Scheduler #immediate #schedule should execute after tick",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber139",
    "Scheduler #immediate #schedule should execute after timeout",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber105",
    "Scheduler #immediate should return a ImmediateScheduler",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber99",
    "Scheduler #immediate should return a SchedulerInterface",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber416",
    "Scheduler #tick",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber469",
    "Scheduler #tick #delay",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber489",
    "Scheduler #tick #delay should execute after current thread",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber497",
    "Scheduler #tick #delay should execute before async",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber513",
    "Scheduler #tick #delay should execute before immediate",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber505",
    "Scheduler #tick #delay should execute before timeout",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber473",
    "Scheduler #tick #delay should return an AbortController",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber481",
    "Scheduler #tick #delay should return an aborted AbortControler if first arg is not a function.",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber432",
    "Scheduler #tick #schedule",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber436",
    "Scheduler #tick #schedule should execute after current thread",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber444",
    "Scheduler #tick #schedule should execute before async",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber460",
    "Scheduler #tick #schedule should execute before immediate",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber452",
    "Scheduler #tick #schedule should execute before timeout",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber420",
    "Scheduler #tick should return a SchedulerInterface",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber426",
    "Scheduler #tick should return a TickScheduler",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber309",
    "Scheduler #timeout",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber362",
    "Scheduler #timeout #delay",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber398",
    "Scheduler #timeout #delay should execute after async",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber382",
    "Scheduler #timeout #delay should execute after current thread",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber390",
    "Scheduler #timeout #delay should execute after tick",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber406",
    "Scheduler #timeout #delay should execute before immediate",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber366",
    "Scheduler #timeout #delay should return an AbortController",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber374",
    "Scheduler #timeout #delay should return an aborted AbortControler if first arg is not a function.",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber325",
    "Scheduler #timeout #schedule",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber345",
    "Scheduler #timeout #schedule should execute after async",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber329",
    "Scheduler #timeout #schedule should execute after current thread",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber337",
    "Scheduler #timeout #schedule should execute after tick",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber353",
    "Scheduler #timeout #schedule should execute before immediate",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber313",
    "Scheduler #timeout should return a SchedulerInterface",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber319",
    "Scheduler #timeout should return a TimeoutScheduler",
    "test"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/async.js",
    "file/src/async.js.html",
    "src/async.js",
    "file"
  ],
  [
    "src/async.js~asyncscheduler#delay",
    "class/src/async.js~AsyncScheduler.html#instance-method-delay",
    "src/async.js~AsyncScheduler#delay",
    "method"
  ],
  [
    "src/async.js~asyncscheduler#schedule",
    "class/src/async.js~AsyncScheduler.html#instance-method-schedule",
    "src/async.js~AsyncScheduler#schedule",
    "method"
  ],
  [
    "src/async.js~asyncscheduler.instance",
    "class/src/async.js~AsyncScheduler.html#static-get-instance",
    "src/async.js~AsyncScheduler.instance",
    "member"
  ],
  [
    "src/current.js",
    "file/src/current.js.html",
    "src/current.js",
    "file"
  ],
  [
    "src/current.js~currentscheduler#delay",
    "class/src/current.js~CurrentScheduler.html#instance-method-delay",
    "src/current.js~CurrentScheduler#delay",
    "method"
  ],
  [
    "src/current.js~currentscheduler#schedule",
    "class/src/current.js~CurrentScheduler.html#instance-method-schedule",
    "src/current.js~CurrentScheduler#schedule",
    "method"
  ],
  [
    "src/current.js~currentscheduler.instance",
    "class/src/current.js~CurrentScheduler.html#static-get-instance",
    "src/current.js~CurrentScheduler.instance",
    "member"
  ],
  [
    "src/immediate.browser.js",
    "file/src/immediate.browser.js.html",
    "src/immediate.browser.js",
    "file"
  ],
  [
    "src/immediate.browser.js~immediatescheduler#delay",
    "class/src/immediate.browser.js~ImmediateScheduler.html#instance-method-delay",
    "src/immediate.browser.js~ImmediateScheduler#delay",
    "method"
  ],
  [
    "src/immediate.browser.js~immediatescheduler#schedule",
    "class/src/immediate.browser.js~ImmediateScheduler.html#instance-method-schedule",
    "src/immediate.browser.js~ImmediateScheduler#schedule",
    "method"
  ],
  [
    "src/immediate.browser.js~immediatescheduler.instance",
    "class/src/immediate.browser.js~ImmediateScheduler.html#static-get-instance",
    "src/immediate.browser.js~ImmediateScheduler.instance",
    "member"
  ],
  [
    "src/immediate.node.js",
    "file/src/immediate.node.js.html",
    "src/immediate.node.js",
    "file"
  ],
  [
    "src/immediate.node.js~immediatescheduler#delay",
    "class/src/immediate.node.js~ImmediateScheduler.html#instance-method-delay",
    "src/immediate.node.js~ImmediateScheduler#delay",
    "method"
  ],
  [
    "src/immediate.node.js~immediatescheduler#schedule",
    "class/src/immediate.node.js~ImmediateScheduler.html#instance-method-schedule",
    "src/immediate.node.js~ImmediateScheduler#schedule",
    "method"
  ],
  [
    "src/immediate.node.js~immediatescheduler.instance",
    "class/src/immediate.node.js~ImmediateScheduler.html#static-get-instance",
    "src/immediate.node.js~ImmediateScheduler.instance",
    "member"
  ],
  [
    "src/index.browser.js",
    "file/src/index.browser.js.html",
    "src/index.browser.js",
    "file"
  ],
  [
    "src/index.browser.js~abortcontroller",
    "https://developer.mozilla.org/en-US/docs/Web/API/AbortController",
    "src/index.browser.js~AbortController",
    "external"
  ],
  [
    "src/index.browser.js~scheduler.async",
    "class/src/index.browser.js~Scheduler.html#static-get-async",
    "src/index.browser.js~Scheduler.async",
    "member"
  ],
  [
    "src/index.browser.js~scheduler.current",
    "class/src/index.browser.js~Scheduler.html#static-get-current",
    "src/index.browser.js~Scheduler.current",
    "member"
  ],
  [
    "src/index.browser.js~scheduler.immediate",
    "class/src/index.browser.js~Scheduler.html#static-get-immediate",
    "src/index.browser.js~Scheduler.immediate",
    "member"
  ],
  [
    "src/index.browser.js~scheduler.interface",
    "class/src/index.browser.js~Scheduler.html#static-get-interface",
    "src/index.browser.js~Scheduler.interface",
    "member"
  ],
  [
    "src/index.browser.js~scheduler.timeout",
    "class/src/index.browser.js~Scheduler.html#static-get-timeout",
    "src/index.browser.js~Scheduler.timeout",
    "member"
  ],
  [
    "src/index.node.js",
    "file/src/index.node.js.html",
    "src/index.node.js",
    "file"
  ],
  [
    "src/index.node.js~abortcontroller",
    "https://developer.mozilla.org/en-US/docs/Web/API/AbortController",
    "src/index.node.js~AbortController",
    "external"
  ],
  [
    "src/index.node.js~scheduler.async",
    "class/src/index.node.js~Scheduler.html#static-get-async",
    "src/index.node.js~Scheduler.async",
    "member"
  ],
  [
    "src/index.node.js~scheduler.current",
    "class/src/index.node.js~Scheduler.html#static-get-current",
    "src/index.node.js~Scheduler.current",
    "member"
  ],
  [
    "src/index.node.js~scheduler.immediate",
    "class/src/index.node.js~Scheduler.html#static-get-immediate",
    "src/index.node.js~Scheduler.immediate",
    "member"
  ],
  [
    "src/index.node.js~scheduler.interface",
    "class/src/index.node.js~Scheduler.html#static-get-interface",
    "src/index.node.js~Scheduler.interface",
    "member"
  ],
  [
    "src/index.node.js~scheduler.tick",
    "class/src/index.node.js~Scheduler.html#static-get-tick",
    "src/index.node.js~Scheduler.tick",
    "member"
  ],
  [
    "src/index.node.js~scheduler.timeout",
    "class/src/index.node.js~Scheduler.html#static-get-timeout",
    "src/index.node.js~Scheduler.timeout",
    "member"
  ],
  [
    "src/scheduler-interface.js",
    "file/src/scheduler-interface.js.html",
    "src/scheduler-interface.js",
    "file"
  ],
  [
    "src/scheduler-interface.js~schedulerinterface#delay",
    "class/src/scheduler-interface.js~SchedulerInterface.html#instance-method-delay",
    "src/scheduler-interface.js~SchedulerInterface#delay",
    "method"
  ],
  [
    "src/scheduler-interface.js~schedulerinterface#schedule",
    "class/src/scheduler-interface.js~SchedulerInterface.html#instance-method-schedule",
    "src/scheduler-interface.js~SchedulerInterface#schedule",
    "method"
  ],
  [
    "src/tick.js",
    "file/src/tick.js.html",
    "src/tick.js",
    "file"
  ],
  [
    "src/tick.js~tickscheduler#delay",
    "class/src/tick.js~TickScheduler.html#instance-method-delay",
    "src/tick.js~TickScheduler#delay",
    "method"
  ],
  [
    "src/tick.js~tickscheduler#schedule",
    "class/src/tick.js~TickScheduler.html#instance-method-schedule",
    "src/tick.js~TickScheduler#schedule",
    "method"
  ],
  [
    "src/tick.js~tickscheduler.instance",
    "class/src/tick.js~TickScheduler.html#static-get-instance",
    "src/tick.js~TickScheduler.instance",
    "member"
  ],
  [
    "src/timeout.js",
    "file/src/timeout.js.html",
    "src/timeout.js",
    "file"
  ],
  [
    "src/timeout.js~timeoutscheduler#delay",
    "class/src/timeout.js~TimeoutScheduler.html#instance-method-delay",
    "src/timeout.js~TimeoutScheduler#delay",
    "method"
  ],
  [
    "src/timeout.js~timeoutscheduler#schedule",
    "class/src/timeout.js~TimeoutScheduler.html#instance-method-schedule",
    "src/timeout.js~TimeoutScheduler#schedule",
    "method"
  ],
  [
    "src/timeout.js~timeoutscheduler.instance",
    "class/src/timeout.js~TimeoutScheduler.html#static-get-instance",
    "src/timeout.js~TimeoutScheduler.instance",
    "member"
  ],
  [
    "test/index.js",
    "test-file/test/index.js.html",
    "test/index.js",
    "testFile"
  ]
]