window.esdocSearchIndex = [
  [
    "",
    "test-file/test/amb.js.html#lineNumber7",
    "#amb",
    "test"
  ],
  [
    "",
    "test-file/test/amb.js.html#lineNumber11",
    "#amb should create a Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/amb.js.html#lineNumber29",
    "#amb should signal complete from the earliest source.",
    "test"
  ],
  [
    "",
    "test-file/test/amb.js.html#lineNumber40",
    "#amb should signal error from the earliest source.",
    "test"
  ],
  [
    "",
    "test-file/test/amb.js.html#lineNumber62",
    "#amb should signal error if given argument is not Iterable",
    "test"
  ],
  [
    "",
    "test-file/test/amb.js.html#lineNumber51",
    "#amb should signal error if one of the source is non-Maybe.",
    "test"
  ],
  [
    "",
    "test-file/test/amb.js.html#lineNumber18",
    "#amb should signal success from the earliest source.",
    "test"
  ],
  [
    "",
    "test-file/test/ambWith.js.html#lineNumber8",
    "#ambWith",
    "test"
  ],
  [
    "",
    "test-file/test/ambWith.js.html#lineNumber12",
    "#ambWith should create a Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/ambWith.js.html#lineNumber19",
    "#ambWith should return the same instance if the other value is non-Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/ambWith.js.html#lineNumber82",
    "#ambWith should signal error from the other (if earlier).",
    "test"
  ],
  [
    "",
    "test-file/test/ambWith.js.html#lineNumber71",
    "#ambWith should signal error from the source (if earlier).",
    "test"
  ],
  [
    "",
    "test-file/test/ambWith.js.html#lineNumber38",
    "#ambWith should signal success from the other (if earlier).",
    "test"
  ],
  [
    "",
    "test-file/test/ambWith.js.html#lineNumber60",
    "#ambWith should signal success from the other (if earlier).",
    "test"
  ],
  [
    "",
    "test-file/test/ambWith.js.html#lineNumber27",
    "#ambWith should signal success from the source (if earlier)",
    "test"
  ],
  [
    "",
    "test-file/test/ambWith.js.html#lineNumber49",
    "#ambWith should signal success from the source (if earlier)",
    "test"
  ],
  [
    "",
    "test-file/test/cache.js.html#lineNumber8",
    "#cache",
    "test"
  ],
  [
    "",
    "test-file/test/cache.js.html#lineNumber12",
    "#cache should create a Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/cache.js.html#lineNumber41",
    "#cache should signal cached complete",
    "test"
  ],
  [
    "",
    "test-file/test/cache.js.html#lineNumber63",
    "#cache should signal cached error value",
    "test"
  ],
  [
    "",
    "test-file/test/cache.js.html#lineNumber19",
    "#cache should signal cached success value",
    "test"
  ],
  [
    "",
    "test-file/test/catch.js.html#lineNumber8",
    "#catch",
    "test"
  ],
  [
    "",
    "test-file/test/catch.js.html#lineNumber12",
    "#catch should create a Promise",
    "test"
  ],
  [
    "",
    "test-file/test/compose.js.html#lineNumber8",
    "#compose",
    "test"
  ],
  [
    "",
    "test-file/test/compose.js.html#lineNumber29",
    "#compose should correctly signal the composed Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/compose.js.html#lineNumber21",
    "#compose should return a Maybe from the transformer",
    "test"
  ],
  [
    "",
    "test-file/test/compose.js.html#lineNumber12",
    "#compose should return the same instance if no function is provided",
    "test"
  ],
  [
    "",
    "test-file/test/compose.js.html#lineNumber41",
    "#compose should signal error if the transformer function returned a non-Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/create.js.html#lineNumber8",
    "#create",
    "test"
  ],
  [
    "",
    "test-file/test/create.js.html#lineNumber56",
    "#create should be aborted successfully if emitter is aborted before any signal.",
    "test"
  ],
  [
    "",
    "test-file/test/create.js.html#lineNumber12",
    "#create should create a Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/create.js.html#lineNumber74",
    "#create should signal error if subscriber throws an error.",
    "test"
  ],
  [
    "",
    "test-file/test/create.js.html#lineNumber20",
    "#create should signal error if the create received a non-function",
    "test"
  ],
  [
    "",
    "test-file/test/create.js.html#lineNumber44",
    "#create should signal error if the emitter signals error with undefined value.",
    "test"
  ],
  [
    "",
    "test-file/test/create.js.html#lineNumber32",
    "#create should signal error if the emitter signals success with undefined value.",
    "test"
  ],
  [
    "",
    "test-file/test/defaultIfEmpty.js.html#lineNumber5",
    "#defaultIfEmpty",
    "test"
  ],
  [
    "",
    "test-file/test/defaultIfEmpty.js.html#lineNumber6",
    "#defaultIfEmpty should return a Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/defaultIfEmpty.js.html#lineNumber9",
    "#defaultIfEmpty should return same reference if value is null",
    "test"
  ],
  [
    "",
    "test-file/test/defaultIfEmpty.js.html#lineNumber31",
    "#defaultIfEmpty should signal error if source signals error",
    "test"
  ],
  [
    "",
    "test-file/test/defaultIfEmpty.js.html#lineNumber22",
    "#defaultIfEmpty should signal success if source signals complete",
    "test"
  ],
  [
    "",
    "test-file/test/defaultIfEmpty.js.html#lineNumber13",
    "#defaultIfEmpty should signal success if source signals success",
    "test"
  ],
  [
    "",
    "test-file/test/defer.js.html#lineNumber8",
    "#defer",
    "test"
  ],
  [
    "",
    "test-file/test/defer.js.html#lineNumber12",
    "#defer should create a Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/defer.js.html#lineNumber32",
    "#defer should signal error if callable returns a non-Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/defer.js.html#lineNumber44",
    "#defer should signal error if callable throws an error",
    "test"
  ],
  [
    "",
    "test-file/test/defer.js.html#lineNumber20",
    "#defer should succeed with the given value.",
    "test"
  ],
  [
    "",
    "test-file/test/delaySubscription.js.html#lineNumber8",
    "#delaySubscription",
    "test"
  ],
  [
    "",
    "test-file/test/delaySubscription.js.html#lineNumber12",
    "#delaySubscription should create a Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/delaySubscription.js.html#lineNumber76",
    "#delaySubscription should not signal complete if aborted.",
    "test"
  ],
  [
    "",
    "test-file/test/delaySubscription.js.html#lineNumber92",
    "#delaySubscription should not signal error if aborted.",
    "test"
  ],
  [
    "",
    "test-file/test/delaySubscription.js.html#lineNumber60",
    "#delaySubscription should not signal success if aborted.",
    "test"
  ],
  [
    "",
    "test-file/test/delaySubscription.js.html#lineNumber19",
    "#delaySubscription should return the same instance if the amount is not a number.",
    "test"
  ],
  [
    "",
    "test-file/test/delaySubscription.js.html#lineNumber38",
    "#delaySubscription should signal complete.",
    "test"
  ],
  [
    "",
    "test-file/test/delaySubscription.js.html#lineNumber49",
    "#delaySubscription should signal error with the given value.",
    "test"
  ],
  [
    "",
    "test-file/test/delaySubscription.js.html#lineNumber27",
    "#delaySubscription should signal success with the given value.",
    "test"
  ],
  [
    "",
    "test-file/test/delayUntil.js.html#lineNumber8",
    "#delayUntil",
    "test"
  ],
  [
    "",
    "test-file/test/delayUntil.js.html#lineNumber12",
    "#delayUntil should create a Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/delayUntil.js.html#lineNumber87",
    "#delayUntil should not signal complete if aborted.",
    "test"
  ],
  [
    "",
    "test-file/test/delayUntil.js.html#lineNumber103",
    "#delayUntil should not signal error if aborted.",
    "test"
  ],
  [
    "",
    "test-file/test/delayUntil.js.html#lineNumber71",
    "#delayUntil should not signal success if aborted.",
    "test"
  ],
  [
    "",
    "test-file/test/delayUntil.js.html#lineNumber19",
    "#delayUntil should return the same instance if the provided value is not a Maybe.",
    "test"
  ],
  [
    "",
    "test-file/test/delayUntil.js.html#lineNumber38",
    "#delayUntil should signal complete.",
    "test"
  ],
  [
    "",
    "test-file/test/delayUntil.js.html#lineNumber60",
    "#delayUntil should signal error if other Maybe signals error.",
    "test"
  ],
  [
    "",
    "test-file/test/delayUntil.js.html#lineNumber49",
    "#delayUntil should signal error with the given value.",
    "test"
  ],
  [
    "",
    "test-file/test/delayUntil.js.html#lineNumber27",
    "#delayUntil should signal success with the given value.",
    "test"
  ],
  [
    "",
    "test-file/test/doAfterSuccess.js.html#lineNumber8",
    "#doAfterSuccess",
    "test"
  ],
  [
    "",
    "test-file/test/doAfterSuccess.js.html#lineNumber27",
    "#doAfterSuccess should call the given function after success.",
    "test"
  ],
  [
    "",
    "test-file/test/doAfterSuccess.js.html#lineNumber12",
    "#doAfterSuccess should create a Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/doAfterSuccess.js.html#lineNumber19",
    "#doAfterSuccess should return the same instance if the method received a non-function parameter.",
    "test"
  ],
  [
    "",
    "test-file/test/doAfterTerminate.js.html#lineNumber8",
    "#doAfterTerminate",
    "test"
  ],
  [
    "",
    "test-file/test/doAfterTerminate.js.html#lineNumber40",
    "#doAfterTerminate should call the given function after complete.",
    "test"
  ],
  [
    "",
    "test-file/test/doAfterTerminate.js.html#lineNumber53",
    "#doAfterTerminate should call the given function after error.",
    "test"
  ],
  [
    "",
    "test-file/test/doAfterTerminate.js.html#lineNumber27",
    "#doAfterTerminate should call the given function after success.",
    "test"
  ],
  [
    "",
    "test-file/test/doAfterTerminate.js.html#lineNumber12",
    "#doAfterTerminate should create a Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/doAfterTerminate.js.html#lineNumber19",
    "#doAfterTerminate should return the same instance if the method received a non-function parameter.",
    "test"
  ],
  [
    "",
    "test-file/test/doFinally.js.html#lineNumber8",
    "#doFinally",
    "test"
  ],
  [
    "",
    "test-file/test/doFinally.js.html#lineNumber40",
    "#doFinally should call the given function after complete.",
    "test"
  ],
  [
    "",
    "test-file/test/doFinally.js.html#lineNumber53",
    "#doFinally should call the given function after error.",
    "test"
  ],
  [
    "",
    "test-file/test/doFinally.js.html#lineNumber27",
    "#doFinally should call the given function after success.",
    "test"
  ],
  [
    "",
    "test-file/test/doFinally.js.html#lineNumber66",
    "#doFinally should call the given function on dispose.",
    "test"
  ],
  [
    "",
    "test-file/test/doFinally.js.html#lineNumber12",
    "#doFinally should create a Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/doFinally.js.html#lineNumber19",
    "#doFinally should return the same instance if the method received a non-function parameter.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnAbort.js.html#lineNumber8",
    "#doOnAbort",
    "test"
  ],
  [
    "",
    "test-file/test/doOnAbort.js.html#lineNumber69",
    "#doOnAbort should call the given function on abort.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnAbort.js.html#lineNumber12",
    "#doOnAbort should create a Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/doOnAbort.js.html#lineNumber19",
    "#doOnAbort should return the same instance if the method received a non-function parameter.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnAbort.js.html#lineNumber41",
    "#doOnAbort should signal the complete then fire abort callback.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnAbort.js.html#lineNumber55",
    "#doOnAbort should signal the error value then fire abort callback.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnAbort.js.html#lineNumber27",
    "#doOnAbort should signal the success value then fire abort callback.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnComplete.js.html#lineNumber8",
    "#doOnComplete",
    "test"
  ],
  [
    "",
    "test-file/test/doOnComplete.js.html#lineNumber27",
    "#doOnComplete should call the given function on error.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnComplete.js.html#lineNumber12",
    "#doOnComplete should create a Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/doOnComplete.js.html#lineNumber19",
    "#doOnComplete should return the same instance if the method received a non-function parameter.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnError.js.html#lineNumber8",
    "#doOnError",
    "test"
  ],
  [
    "",
    "test-file/test/doOnError.js.html#lineNumber27",
    "#doOnError should call the given function on error.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnError.js.html#lineNumber12",
    "#doOnError should create a Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/doOnError.js.html#lineNumber19",
    "#doOnError should return the same instance if the method received a non-function parameter.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnEvent.js.html#lineNumber8",
    "#doOnEvent",
    "test"
  ],
  [
    "",
    "test-file/test/doOnEvent.js.html#lineNumber40",
    "#doOnEvent should call the given function on complete.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnEvent.js.html#lineNumber53",
    "#doOnEvent should call the given function on error.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnEvent.js.html#lineNumber27",
    "#doOnEvent should call the given function on success.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnEvent.js.html#lineNumber12",
    "#doOnEvent should create a Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/doOnEvent.js.html#lineNumber19",
    "#doOnEvent should return the same instance if the method received a non-function parameter.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnSubscribe.js.html#lineNumber8",
    "#doOnSubscribe",
    "test"
  ],
  [
    "",
    "test-file/test/doOnSubscribe.js.html#lineNumber27",
    "#doOnSubscribe should be called before actual subscription.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnSubscribe.js.html#lineNumber12",
    "#doOnSubscribe should create a Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/doOnSubscribe.js.html#lineNumber19",
    "#doOnSubscribe should return the same instance if no function is passed",
    "test"
  ],
  [
    "",
    "test-file/test/doOnSuccess.js.html#lineNumber8",
    "#doOnSuccess",
    "test"
  ],
  [
    "",
    "test-file/test/doOnSuccess.js.html#lineNumber27",
    "#doOnSuccess should call the given function on success.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnSuccess.js.html#lineNumber12",
    "#doOnSuccess should create a Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/doOnSuccess.js.html#lineNumber19",
    "#doOnSuccess should return the same instance if the method received a non-function parameter.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnTerminate.js.html#lineNumber8",
    "#doOnTerminate",
    "test"
  ],
  [
    "",
    "test-file/test/doOnTerminate.js.html#lineNumber40",
    "#doOnTerminate should call the given function on complete.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnTerminate.js.html#lineNumber53",
    "#doOnTerminate should call the given function on error.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnTerminate.js.html#lineNumber27",
    "#doOnTerminate should call the given function on success.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnTerminate.js.html#lineNumber12",
    "#doOnTerminate should create a Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/doOnTerminate.js.html#lineNumber19",
    "#doOnTerminate should return the same instance if the method received a non-function parameter.",
    "test"
  ],
  [
    "",
    "test-file/test/error.js.html#lineNumber8",
    "#error",
    "test"
  ],
  [
    "",
    "test-file/test/error.js.html#lineNumber12",
    "#error should create a Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/error.js.html#lineNumber56",
    "#error should error if the callable throws an error.",
    "test"
  ],
  [
    "",
    "test-file/test/error.js.html#lineNumber44",
    "#error should error with the a message if the callable returned null",
    "test"
  ],
  [
    "",
    "test-file/test/error.js.html#lineNumber32",
    "#error should error with the a message if the given value is null",
    "test"
  ],
  [
    "",
    "test-file/test/error.js.html#lineNumber20",
    "#error should error with the given value.",
    "test"
  ],
  [
    "",
    "test-file/test/filter.js.html#lineNumber5",
    "#filter",
    "test"
  ],
  [
    "",
    "test-file/test/filter.js.html#lineNumber6",
    "#filter should return a Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/filter.js.html#lineNumber9",
    "#filter should return same reference if value is non-function",
    "test"
  ],
  [
    "",
    "test-file/test/filter.js.html#lineNumber13",
    "#filter should signal complete if source signals complete",
    "test"
  ],
  [
    "",
    "test-file/test/filter.js.html#lineNumber31",
    "#filter should signal complete if source signals success and predicate returns false",
    "test"
  ],
  [
    "",
    "test-file/test/filter.js.html#lineNumber40",
    "#filter should signal error if source  signals success and predicate throws error",
    "test"
  ],
  [
    "",
    "test-file/test/filter.js.html#lineNumber49",
    "#filter should signal error if source signals error",
    "test"
  ],
  [
    "",
    "test-file/test/filter.js.html#lineNumber22",
    "#filter should signal success if source signals success and predicate returns true",
    "test"
  ],
  [
    "",
    "test-file/test/flatMap.js.html#lineNumber8",
    "#flatMap",
    "test"
  ],
  [
    "",
    "test-file/test/flatMap.js.html#lineNumber12",
    "#flatMap should create a Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/flatMap.js.html#lineNumber20",
    "#flatMap should return the same instance if the method received a non-function parameter.",
    "test"
  ],
  [
    "",
    "test-file/test/flatMap.js.html#lineNumber40",
    "#flatMap should signal complete if source emits a complete signal",
    "test"
  ],
  [
    "",
    "test-file/test/flatMap.js.html#lineNumber76",
    "#flatMap should signal complete of the returned Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/flatMap.js.html#lineNumber28",
    "#flatMap should signal error if mapper returns a non-Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/flatMap.js.html#lineNumber52",
    "#flatMap should signal error if source emits an error signal",
    "test"
  ],
  [
    "",
    "test-file/test/flatMap.js.html#lineNumber88",
    "#flatMap should signal error of the returned Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/flatMap.js.html#lineNumber64",
    "#flatMap should signal success of the returned Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/fromCallable.js.html#lineNumber8",
    "#fromCallable",
    "test"
  ],
  [
    "",
    "test-file/test/fromCallable.js.html#lineNumber31",
    "#fromCallable should complete",
    "test"
  ],
  [
    "",
    "test-file/test/fromCallable.js.html#lineNumber12",
    "#fromCallable should create a Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/fromCallable.js.html#lineNumber69",
    "#fromCallable should signal an complete if the callable returns a resolved Promise with no value.",
    "test"
  ],
  [
    "",
    "test-file/test/fromCallable.js.html#lineNumber93",
    "#fromCallable should signal an error if the callable is not a function",
    "test"
  ],
  [
    "",
    "test-file/test/fromCallable.js.html#lineNumber81",
    "#fromCallable should signal an error if the callable returns a rejected Promise.",
    "test"
  ],
  [
    "",
    "test-file/test/fromCallable.js.html#lineNumber43",
    "#fromCallable should signal an error if the callable throws an error.",
    "test"
  ],
  [
    "",
    "test-file/test/fromCallable.js.html#lineNumber57",
    "#fromCallable should signal an success if the callable returns a resolved Promise with a value.",
    "test"
  ],
  [
    "",
    "test-file/test/fromCallable.js.html#lineNumber19",
    "#fromCallable should succeed with the given value.",
    "test"
  ],
  [
    "",
    "test-file/test/fromPromise.js.html#lineNumber9",
    "#fromPromise",
    "test"
  ],
  [
    "",
    "test-file/test/fromPromise.js.html#lineNumber13",
    "#fromPromise should create a Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/fromPromise.js.html#lineNumber33",
    "#fromPromise should signal error if the given value is not Promise like",
    "test"
  ],
  [
    "",
    "test-file/test/fromPromise.js.html#lineNumber20",
    "#fromPromise should succeed with the given value.",
    "test"
  ],
  [
    "",
    "test-file/test/fromResolvable.js.html#lineNumber8",
    "#fromResolvable",
    "test"
  ],
  [
    "",
    "test-file/test/fromResolvable.js.html#lineNumber12",
    "#fromResolvable should create a Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/fromResolvable.js.html#lineNumber30",
    "#fromResolvable should signal error if the given value is not a function",
    "test"
  ],
  [
    "",
    "test-file/test/fromResolvable.js.html#lineNumber19",
    "#fromResolvable should succeed with the given value.",
    "test"
  ],
  [
    "",
    "test-file/test/just.js.html#lineNumber8",
    "#just",
    "test"
  ],
  [
    "",
    "test-file/test/just.js.html#lineNumber12",
    "#just should create a Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/just.js.html#lineNumber32",
    "#just should emit error if value is undefined.",
    "test"
  ],
  [
    "",
    "test-file/test/just.js.html#lineNumber20",
    "#just should succeed with the given value.",
    "test"
  ],
  [
    "",
    "test-file/test/map.js.html#lineNumber8",
    "#map",
    "test"
  ],
  [
    "",
    "test-file/test/map.js.html#lineNumber12",
    "#map should create a Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/map.js.html#lineNumber56",
    "#map should retain the value if no function is supplied.",
    "test"
  ],
  [
    "",
    "test-file/test/map.js.html#lineNumber44",
    "#map should signal an error if the mapper returns undefined",
    "test"
  ],
  [
    "",
    "test-file/test/map.js.html#lineNumber30",
    "#map should signal an error if the mapper throws an error",
    "test"
  ],
  [
    "",
    "test-file/test/map.js.html#lineNumber19",
    "#map should succeed with the given value.",
    "test"
  ],
  [
    "",
    "test-file/test/merge.js.html#lineNumber8",
    "#merge",
    "test"
  ],
  [
    "",
    "test-file/test/merge.js.html#lineNumber12",
    "#merge should create a Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/merge.js.html#lineNumber44",
    "#merge should signal complete if source emits a complete signal",
    "test"
  ],
  [
    "",
    "test-file/test/merge.js.html#lineNumber80",
    "#merge should signal complete of the signaled Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/merge.js.html#lineNumber20",
    "#merge should signal error if no source is provided",
    "test"
  ],
  [
    "",
    "test-file/test/merge.js.html#lineNumber56",
    "#merge should signal error if source emits an error signal",
    "test"
  ],
  [
    "",
    "test-file/test/merge.js.html#lineNumber32",
    "#merge should signal error if source emitted a non-Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/merge.js.html#lineNumber68",
    "#merge should signal success of the signaled Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/never.js.html#lineNumber8",
    "#never",
    "test"
  ],
  [
    "",
    "test-file/test/never.js.html#lineNumber12",
    "#never should create a Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/never.js.html#lineNumber19",
    "#never should not signal.",
    "test"
  ],
  [
    "",
    "test-file/test/observeOn.js.html#lineNumber6",
    "#observeOn",
    "test"
  ],
  [
    "",
    "test-file/test/observeOn.js.html#lineNumber67",
    "#observeOn should be asynchronous with Scheduler.async",
    "test"
  ],
  [
    "",
    "test-file/test/observeOn.js.html#lineNumber90",
    "#observeOn should be asynchronous with Scheduler.immediate",
    "test"
  ],
  [
    "",
    "test-file/test/observeOn.js.html#lineNumber44",
    "#observeOn should be asynchronous with Scheduler.tick",
    "test"
  ],
  [
    "",
    "test-file/test/observeOn.js.html#lineNumber113",
    "#observeOn should be asynchronous with Scheduler.timeout",
    "test"
  ],
  [
    "",
    "test-file/test/observeOn.js.html#lineNumber27",
    "#observeOn should be synchronous with Scheduler.current",
    "test"
  ],
  [
    "",
    "test-file/test/observeOn.js.html#lineNumber10",
    "#observeOn should be synchronous with non-Scheduler",
    "test"
  ],
  [
    "",
    "test-file/test/observeOn.js.html#lineNumber7",
    "#observeOn should return a Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorComplete.js.html#lineNumber8",
    "#onErrorComplete",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorComplete.js.html#lineNumber12",
    "#onErrorComplete should create a Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorComplete.js.html#lineNumber50",
    "#onErrorComplete should emit error if provide function returns undefined.",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorComplete.js.html#lineNumber39",
    "#onErrorComplete should emit error if provide function throws error.",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorComplete.js.html#lineNumber27",
    "#onErrorComplete should emit the supplied item by the given function in case of error",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorComplete.js.html#lineNumber19",
    "#onErrorComplete should return the same instance if parameter passed is not a Maybe or a function",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorResumeNext.js.html#lineNumber8",
    "#onErrorResumeNext",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorResumeNext.js.html#lineNumber12",
    "#onErrorResumeNext should create a Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorResumeNext.js.html#lineNumber128",
    "#onErrorResumeNext should emit error if provide function returns non-Maybe.",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorResumeNext.js.html#lineNumber117",
    "#onErrorResumeNext should emit error if provide function throws error.",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorResumeNext.js.html#lineNumber19",
    "#onErrorResumeNext should return the same instance if parameter passed is not a Maybe or a function",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorResumeNext.js.html#lineNumber50",
    "#onErrorResumeNext should signal complete if source emits a complete signal",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorResumeNext.js.html#lineNumber38",
    "#onErrorResumeNext should signal success if source emits an error signal",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorResumeNext.js.html#lineNumber27",
    "#onErrorResumeNext should subscribe to the given Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorResumeNext.js.html#lineNumber73",
    "#onErrorResumeNext should subscribe to the given Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorResumeNext.js.html#lineNumber95",
    "#onErrorResumeNext should subscribe to the given Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorResumeNext.js.html#lineNumber62",
    "#onErrorResumeNext should subscribe to the given Maybe-producing Function",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorResumeNext.js.html#lineNumber84",
    "#onErrorResumeNext should subscribe to the given Maybe-producing Function",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorResumeNext.js.html#lineNumber106",
    "#onErrorResumeNext should subscribe to the given Maybe-producing Function",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorReturn.js.html#lineNumber8",
    "#onErrorReturn",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorReturn.js.html#lineNumber12",
    "#onErrorReturn should create a Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorReturn.js.html#lineNumber50",
    "#onErrorReturn should emit error if provide function returns undefined.",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorReturn.js.html#lineNumber39",
    "#onErrorReturn should emit error if provide function throws error.",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorReturn.js.html#lineNumber27",
    "#onErrorReturn should emit the supplied item by the given function in case of error",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorReturn.js.html#lineNumber19",
    "#onErrorReturn should return the same instance if parameter passed is not a Maybe or a function",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorReturnItem.js.html#lineNumber8",
    "#onErrorReturnItem",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorReturnItem.js.html#lineNumber12",
    "#onErrorReturnItem should create a Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorReturnItem.js.html#lineNumber27",
    "#onErrorReturnItem should emit the given item in case of error",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorReturnItem.js.html#lineNumber19",
    "#onErrorReturnItem should return the same instance if parameter passed is not a Maybe or a function",
    "test"
  ],
  [
    "",
    "test-file/test/retry.js.html#lineNumber8",
    "#retry",
    "test"
  ],
  [
    "",
    "test-file/test/retry.js.html#lineNumber12",
    "#retry should create a Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/retry.js.html#lineNumber44",
    "#retry should retry if there is an error and if it passes the predicate",
    "test"
  ],
  [
    "",
    "test-file/test/retry.js.html#lineNumber20",
    "#retry should signal a success if no error",
    "test"
  ],
  [
    "",
    "test-file/test/retry.js.html#lineNumber62",
    "#retry should signal an error if predicate is false",
    "test"
  ],
  [
    "",
    "test-file/test/retry.js.html#lineNumber32",
    "#retry should signal complete if no error",
    "test"
  ],
  [
    "",
    "test-file/test/subscribeOn.js.html#lineNumber6",
    "#subscribeOn",
    "test"
  ],
  [
    "",
    "test-file/test/subscribeOn.js.html#lineNumber67",
    "#subscribeOn should be asynchronous with Scheduler.async",
    "test"
  ],
  [
    "",
    "test-file/test/subscribeOn.js.html#lineNumber90",
    "#subscribeOn should be asynchronous with Scheduler.immediate",
    "test"
  ],
  [
    "",
    "test-file/test/subscribeOn.js.html#lineNumber44",
    "#subscribeOn should be asynchronous with Scheduler.tick",
    "test"
  ],
  [
    "",
    "test-file/test/subscribeOn.js.html#lineNumber113",
    "#subscribeOn should be asynchronous with Scheduler.timeout",
    "test"
  ],
  [
    "",
    "test-file/test/subscribeOn.js.html#lineNumber27",
    "#subscribeOn should be synchronous with Scheduler.current",
    "test"
  ],
  [
    "",
    "test-file/test/subscribeOn.js.html#lineNumber10",
    "#subscribeOn should be synchronous with non-Scheduler",
    "test"
  ],
  [
    "",
    "test-file/test/subscribeOn.js.html#lineNumber7",
    "#subscribeOn should return a Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/switchIfEmpty.js.html#lineNumber5",
    "#switchIfEmpty",
    "test"
  ],
  [
    "",
    "test-file/test/switchIfEmpty.js.html#lineNumber6",
    "#switchIfEmpty should return a Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/switchIfEmpty.js.html#lineNumber9",
    "#switchIfEmpty should return same reference if value is non-Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/switchIfEmpty.js.html#lineNumber40",
    "#switchIfEmpty should signal error if source signals complete",
    "test"
  ],
  [
    "",
    "test-file/test/switchIfEmpty.js.html#lineNumber49",
    "#switchIfEmpty should signal error if source signals error",
    "test"
  ],
  [
    "",
    "test-file/test/switchIfEmpty.js.html#lineNumber22",
    "#switchIfEmpty should signal success if source signals complete",
    "test"
  ],
  [
    "",
    "test-file/test/switchIfEmpty.js.html#lineNumber31",
    "#switchIfEmpty should signal success if source signals complete",
    "test"
  ],
  [
    "",
    "test-file/test/switchIfEmpty.js.html#lineNumber13",
    "#switchIfEmpty should signal success if source signals success",
    "test"
  ],
  [
    "",
    "test-file/test/takeUntil.js.html#lineNumber8",
    "#takeUntil",
    "test"
  ],
  [
    "",
    "test-file/test/takeUntil.js.html#lineNumber12",
    "#takeUntil should create a Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/takeUntil.js.html#lineNumber20",
    "#takeUntil should return the same instance if no other Maybe is provided",
    "test"
  ],
  [
    "",
    "test-file/test/takeUntil.js.html#lineNumber53",
    "#takeUntil should signal complete if other Maybe has not emitted a success signal",
    "test"
  ],
  [
    "",
    "test-file/test/takeUntil.js.html#lineNumber65",
    "#takeUntil should signal complete if other Maybe has not emitted an error signal",
    "test"
  ],
  [
    "",
    "test-file/test/takeUntil.js.html#lineNumber89",
    "#takeUntil should signal error if other Maybe has emitted a completion signal",
    "test"
  ],
  [
    "",
    "test-file/test/takeUntil.js.html#lineNumber77",
    "#takeUntil should signal error if other Maybe has emitted a success signal",
    "test"
  ],
  [
    "",
    "test-file/test/takeUntil.js.html#lineNumber101",
    "#takeUntil should signal error if other Maybe has emitted an error signal",
    "test"
  ],
  [
    "",
    "test-file/test/takeUntil.js.html#lineNumber113",
    "#takeUntil should signal error if source signals error, nonetheless",
    "test"
  ],
  [
    "",
    "test-file/test/takeUntil.js.html#lineNumber29",
    "#takeUntil should signal success if other Maybe has not emitted a success signal",
    "test"
  ],
  [
    "",
    "test-file/test/takeUntil.js.html#lineNumber41",
    "#takeUntil should signal success if other Maybe has not emitted an error signal",
    "test"
  ],
  [
    "",
    "test-file/test/then.js.html#lineNumber8",
    "#then",
    "test"
  ],
  [
    "",
    "test-file/test/then.js.html#lineNumber12",
    "#then should create a Promise",
    "test"
  ],
  [
    "",
    "test-file/test/timeout.js.html#lineNumber8",
    "#timeout",
    "test"
  ],
  [
    "",
    "test-file/test/timeout.js.html#lineNumber12",
    "#timeout should create a Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/timeout.js.html#lineNumber86",
    "#timeout should not signal error if aborted.",
    "test"
  ],
  [
    "",
    "test-file/test/timeout.js.html#lineNumber71",
    "#timeout should not signal success if aborted.",
    "test"
  ],
  [
    "",
    "test-file/test/timeout.js.html#lineNumber19",
    "#timeout should return the same instance if the amount is not a number.",
    "test"
  ],
  [
    "",
    "test-file/test/timeout.js.html#lineNumber38",
    "#timeout should signal complete.",
    "test"
  ],
  [
    "",
    "test-file/test/timeout.js.html#lineNumber60",
    "#timeout should signal error if the Maybe does not emit item within the given timeout.",
    "test"
  ],
  [
    "",
    "test-file/test/timeout.js.html#lineNumber49",
    "#timeout should signal error with the given value.",
    "test"
  ],
  [
    "",
    "test-file/test/timeout.js.html#lineNumber27",
    "#timeout should signal success with the given value.",
    "test"
  ],
  [
    "",
    "test-file/test/timer.js.html#lineNumber8",
    "#timer",
    "test"
  ],
  [
    "",
    "test-file/test/timer.js.html#lineNumber12",
    "#timer should create a Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/timer.js.html#lineNumber42",
    "#timer should not signal success if aborted.",
    "test"
  ],
  [
    "",
    "test-file/test/timer.js.html#lineNumber19",
    "#timer should signal error if amount is not a number.",
    "test"
  ],
  [
    "",
    "test-file/test/timer.js.html#lineNumber31",
    "#timer should signal success 0",
    "test"
  ],
  [
    "",
    "test-file/test/toPromise.js.html#lineNumber8",
    "#toPromise",
    "test"
  ],
  [
    "",
    "test-file/test/toPromise.js.html#lineNumber12",
    "#toPromise should create a Promise",
    "test"
  ],
  [
    "",
    "test-file/test/zip.js.html#lineNumber8",
    "#zip",
    "test"
  ],
  [
    "",
    "test-file/test/zip.js.html#lineNumber12",
    "#zip should create a Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/zip.js.html#lineNumber119",
    "#zip should not signal success if aborted.",
    "test"
  ],
  [
    "",
    "test-file/test/zip.js.html#lineNumber41",
    "#zip should signal an error if the zipper throws an error",
    "test"
  ],
  [
    "",
    "test-file/test/zip.js.html#lineNumber108",
    "#zip should signal complete if a source throws error.",
    "test"
  ],
  [
    "",
    "test-file/test/zip.js.html#lineNumber97",
    "#zip should signal error if a source throws error.",
    "test"
  ],
  [
    "",
    "test-file/test/zip.js.html#lineNumber86",
    "#zip should signal error if one of the sources is undefined.",
    "test"
  ],
  [
    "",
    "test-file/test/zip.js.html#lineNumber30",
    "#zip should signal error if source is empty iterable.",
    "test"
  ],
  [
    "",
    "test-file/test/zip.js.html#lineNumber19",
    "#zip should signal error if sources is not iterable.",
    "test"
  ],
  [
    "",
    "test-file/test/zip.js.html#lineNumber53",
    "#zip should signal success with an array (no zipper function).",
    "test"
  ],
  [
    "",
    "test-file/test/zip.js.html#lineNumber64",
    "#zip should signal success with an array with the correct values (no zipper function).",
    "test"
  ],
  [
    "",
    "test-file/test/zip.js.html#lineNumber75",
    "#zip should signal success with an array with the correct values, consider non-Maybe (no zipper function).",
    "test"
  ],
  [
    "",
    "test-file/test/zipWith.js.html#lineNumber8",
    "#zipWith",
    "test"
  ],
  [
    "",
    "test-file/test/zipWith.js.html#lineNumber12",
    "#zipWith should create a Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/zipWith.js.html#lineNumber114",
    "#zipWith should not signal success if aborted.",
    "test"
  ],
  [
    "",
    "test-file/test/zipWith.js.html#lineNumber19",
    "#zipWith should return the same instance if the other parameter is non-Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/zipWith.js.html#lineNumber27",
    "#zipWith should signal an error if the zipper returns undefined",
    "test"
  ],
  [
    "",
    "test-file/test/zipWith.js.html#lineNumber39",
    "#zipWith should signal an error if the zipper returns undefined",
    "test"
  ],
  [
    "",
    "test-file/test/zipWith.js.html#lineNumber103",
    "#zipWith should signal complete if other Maybe signals complete.",
    "test"
  ],
  [
    "",
    "test-file/test/zipWith.js.html#lineNumber92",
    "#zipWith should signal complete if source signals complete.",
    "test"
  ],
  [
    "",
    "test-file/test/zipWith.js.html#lineNumber84",
    "#zipWith should signal error if other Maybe throws error.",
    "test"
  ],
  [
    "",
    "test-file/test/zipWith.js.html#lineNumber73",
    "#zipWith should signal error if source throws error.",
    "test"
  ],
  [
    "",
    "test-file/test/zipWith.js.html#lineNumber51",
    "#zipWith should signal success with an array (no zipper function).",
    "test"
  ],
  [
    "",
    "test-file/test/zipWith.js.html#lineNumber62",
    "#zipWith should signal success with an array with the correct values (no zipper function).",
    "test"
  ],
  [
    "rx-maybe/src/emitter.js~emitter",
    "class/src/emitter.js~Emitter.html",
    "<span>Emitter</span> <span class=\"search-result-import-path\">rx-maybe/src/emitter.js</span>",
    "class"
  ],
  [
    "rx-maybe/src/maybe.js~maybe",
    "class/src/maybe.js~Maybe.html",
    "<span>Maybe</span> <span class=\"search-result-import-path\">rx-maybe/src/maybe.js</span>",
    "class"
  ],
  [
    "rx-maybe/src/observer.js~observer",
    "class/src/observer.js~Observer.html",
    "<span>Observer</span> <span class=\"search-result-import-path\">rx-maybe/src/observer.js</span>",
    "class"
  ],
  [
    "",
    "test-file/test/lift.js.html#lineNumber7",
    "Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/delay.js.html#lineNumber8",
    "Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/delay.js.html#lineNumber12",
    "Maybe #delay",
    "test"
  ],
  [
    "",
    "test-file/test/delay.js.html#lineNumber16",
    "Maybe #delay should create a Maybe",
    "test"
  ],
  [
    "",
    "test-file/test/delay.js.html#lineNumber80",
    "Maybe #delay should not signal complete if aborted.",
    "test"
  ],
  [
    "",
    "test-file/test/delay.js.html#lineNumber96",
    "Maybe #delay should not signal error if aborted.",
    "test"
  ],
  [
    "",
    "test-file/test/delay.js.html#lineNumber64",
    "Maybe #delay should not signal success if aborted.",
    "test"
  ],
  [
    "",
    "test-file/test/delay.js.html#lineNumber23",
    "Maybe #delay should return the same instance if the amount is not a number.",
    "test"
  ],
  [
    "",
    "test-file/test/delay.js.html#lineNumber42",
    "Maybe #delay should signal complete",
    "test"
  ],
  [
    "",
    "test-file/test/delay.js.html#lineNumber53",
    "Maybe #delay should signal error with the given value.",
    "test"
  ],
  [
    "",
    "test-file/test/delay.js.html#lineNumber31",
    "Maybe #delay should signal success with the given value.",
    "test"
  ],
  [
    "",
    "test-file/test/lift.js.html#lineNumber11",
    "Maybe #lift",
    "test"
  ],
  [
    "",
    "test-file/test/lift.js.html#lineNumber15",
    "Maybe #lift should return the same instance if no function is provided",
    "test"
  ],
  [
    "",
    "test-file/test/lift.js.html#lineNumber24",
    "Maybe #lift should signal an error if the lift operator returned a non-Observer",
    "test"
  ],
  [
    "",
    "test-file/test/lift.js.html#lineNumber36",
    "Maybe #lift should subscribe successfully",
    "test"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/emitter.js",
    "file/src/emitter.js.html",
    "src/emitter.js",
    "file"
  ],
  [
    "src/emitter.js~emitter#oncomplete",
    "class/src/emitter.js~Emitter.html#instance-method-onComplete",
    "src/emitter.js~Emitter#onComplete",
    "method"
  ],
  [
    "src/emitter.js~emitter#onerror",
    "class/src/emitter.js~Emitter.html#instance-method-onError",
    "src/emitter.js~Emitter#onError",
    "method"
  ],
  [
    "src/emitter.js~emitter#onsuccess",
    "class/src/emitter.js~Emitter.html#instance-method-onSuccess",
    "src/emitter.js~Emitter#onSuccess",
    "method"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/internal/operators.js",
    "file/src/internal/operators.js.html",
    "src/internal/operators.js",
    "file"
  ],
  [
    "src/internal/operators/amb.js",
    "file/src/internal/operators/amb.js.html",
    "src/internal/operators/amb.js",
    "file"
  ],
  [
    "src/internal/operators/ambwith.js",
    "file/src/internal/operators/ambWith.js.html",
    "src/internal/operators/ambWith.js",
    "file"
  ],
  [
    "src/internal/operators/cache.js",
    "file/src/internal/operators/cache.js.html",
    "src/internal/operators/cache.js",
    "file"
  ],
  [
    "src/internal/operators/compose.js",
    "file/src/internal/operators/compose.js.html",
    "src/internal/operators/compose.js",
    "file"
  ],
  [
    "src/internal/operators/create.js",
    "file/src/internal/operators/create.js.html",
    "src/internal/operators/create.js",
    "file"
  ],
  [
    "src/internal/operators/defaultifempty.js",
    "file/src/internal/operators/defaultIfEmpty.js.html",
    "src/internal/operators/defaultIfEmpty.js",
    "file"
  ],
  [
    "src/internal/operators/defer.js",
    "file/src/internal/operators/defer.js.html",
    "src/internal/operators/defer.js",
    "file"
  ],
  [
    "src/internal/operators/delay.js",
    "file/src/internal/operators/delay.js.html",
    "src/internal/operators/delay.js",
    "file"
  ],
  [
    "src/internal/operators/delaysubscription.js",
    "file/src/internal/operators/delaySubscription.js.html",
    "src/internal/operators/delaySubscription.js",
    "file"
  ],
  [
    "src/internal/operators/delayuntil.js",
    "file/src/internal/operators/delayUntil.js.html",
    "src/internal/operators/delayUntil.js",
    "file"
  ],
  [
    "src/internal/operators/doaftersuccess.js",
    "file/src/internal/operators/doAfterSuccess.js.html",
    "src/internal/operators/doAfterSuccess.js",
    "file"
  ],
  [
    "src/internal/operators/doafterterminate.js",
    "file/src/internal/operators/doAfterTerminate.js.html",
    "src/internal/operators/doAfterTerminate.js",
    "file"
  ],
  [
    "src/internal/operators/dofinally.js",
    "file/src/internal/operators/doFinally.js.html",
    "src/internal/operators/doFinally.js",
    "file"
  ],
  [
    "src/internal/operators/doonabort.js",
    "file/src/internal/operators/doOnAbort.js.html",
    "src/internal/operators/doOnAbort.js",
    "file"
  ],
  [
    "src/internal/operators/dooncomplete.js",
    "file/src/internal/operators/doOnComplete.js.html",
    "src/internal/operators/doOnComplete.js",
    "file"
  ],
  [
    "src/internal/operators/doonerror.js",
    "file/src/internal/operators/doOnError.js.html",
    "src/internal/operators/doOnError.js",
    "file"
  ],
  [
    "src/internal/operators/doonevent.js",
    "file/src/internal/operators/doOnEvent.js.html",
    "src/internal/operators/doOnEvent.js",
    "file"
  ],
  [
    "src/internal/operators/doonsubscribe.js",
    "file/src/internal/operators/doOnSubscribe.js.html",
    "src/internal/operators/doOnSubscribe.js",
    "file"
  ],
  [
    "src/internal/operators/doonsuccess.js",
    "file/src/internal/operators/doOnSuccess.js.html",
    "src/internal/operators/doOnSuccess.js",
    "file"
  ],
  [
    "src/internal/operators/doonterminate.js",
    "file/src/internal/operators/doOnTerminate.js.html",
    "src/internal/operators/doOnTerminate.js",
    "file"
  ],
  [
    "src/internal/operators/empty.js",
    "file/src/internal/operators/empty.js.html",
    "src/internal/operators/empty.js",
    "file"
  ],
  [
    "src/internal/operators/error.js",
    "file/src/internal/operators/error.js.html",
    "src/internal/operators/error.js",
    "file"
  ],
  [
    "src/internal/operators/filter.js",
    "file/src/internal/operators/filter.js.html",
    "src/internal/operators/filter.js",
    "file"
  ],
  [
    "src/internal/operators/flatmap.js",
    "file/src/internal/operators/flatMap.js.html",
    "src/internal/operators/flatMap.js",
    "file"
  ],
  [
    "src/internal/operators/fromcallable.js",
    "file/src/internal/operators/fromCallable.js.html",
    "src/internal/operators/fromCallable.js",
    "file"
  ],
  [
    "src/internal/operators/frompromise.js",
    "file/src/internal/operators/fromPromise.js.html",
    "src/internal/operators/fromPromise.js",
    "file"
  ],
  [
    "src/internal/operators/fromresolvable.js",
    "file/src/internal/operators/fromResolvable.js.html",
    "src/internal/operators/fromResolvable.js",
    "file"
  ],
  [
    "src/internal/operators/just.js",
    "file/src/internal/operators/just.js.html",
    "src/internal/operators/just.js",
    "file"
  ],
  [
    "src/internal/operators/lift.js",
    "file/src/internal/operators/lift.js.html",
    "src/internal/operators/lift.js",
    "file"
  ],
  [
    "src/internal/operators/map.js",
    "file/src/internal/operators/map.js.html",
    "src/internal/operators/map.js",
    "file"
  ],
  [
    "src/internal/operators/merge.js",
    "file/src/internal/operators/merge.js.html",
    "src/internal/operators/merge.js",
    "file"
  ],
  [
    "src/internal/operators/never.js",
    "file/src/internal/operators/never.js.html",
    "src/internal/operators/never.js",
    "file"
  ],
  [
    "src/internal/operators/observeon.js",
    "file/src/internal/operators/observeOn.js.html",
    "src/internal/operators/observeOn.js",
    "file"
  ],
  [
    "src/internal/operators/onerrorcomplete.js",
    "file/src/internal/operators/onErrorComplete.js.html",
    "src/internal/operators/onErrorComplete.js",
    "file"
  ],
  [
    "src/internal/operators/onerrorresumenext.js",
    "file/src/internal/operators/onErrorResumeNext.js.html",
    "src/internal/operators/onErrorResumeNext.js",
    "file"
  ],
  [
    "src/internal/operators/onerrorreturn.js",
    "file/src/internal/operators/onErrorReturn.js.html",
    "src/internal/operators/onErrorReturn.js",
    "file"
  ],
  [
    "src/internal/operators/onerrorreturnitem.js",
    "file/src/internal/operators/onErrorReturnItem.js.html",
    "src/internal/operators/onErrorReturnItem.js",
    "file"
  ],
  [
    "src/internal/operators/retry.js",
    "file/src/internal/operators/retry.js.html",
    "src/internal/operators/retry.js",
    "file"
  ],
  [
    "src/internal/operators/subscribeon.js",
    "file/src/internal/operators/subscribeOn.js.html",
    "src/internal/operators/subscribeOn.js",
    "file"
  ],
  [
    "src/internal/operators/switchifempty.js",
    "file/src/internal/operators/switchIfEmpty.js.html",
    "src/internal/operators/switchIfEmpty.js",
    "file"
  ],
  [
    "src/internal/operators/takeuntil.js",
    "file/src/internal/operators/takeUntil.js.html",
    "src/internal/operators/takeUntil.js",
    "file"
  ],
  [
    "src/internal/operators/timeout.js",
    "file/src/internal/operators/timeout.js.html",
    "src/internal/operators/timeout.js",
    "file"
  ],
  [
    "src/internal/operators/timer.js",
    "file/src/internal/operators/timer.js.html",
    "src/internal/operators/timer.js",
    "file"
  ],
  [
    "src/internal/operators/zip.js",
    "file/src/internal/operators/zip.js.html",
    "src/internal/operators/zip.js",
    "file"
  ],
  [
    "src/internal/operators/zipwith.js",
    "file/src/internal/operators/zipWith.js.html",
    "src/internal/operators/zipWith.js",
    "file"
  ],
  [
    "src/internal/utils.js",
    "file/src/internal/utils.js.html",
    "src/internal/utils.js",
    "file"
  ],
  [
    "src/maybe.js",
    "file/src/maybe.js.html",
    "src/maybe.js",
    "file"
  ],
  [
    "src/maybe.js~abortcontroller",
    "https://developer.mozilla.org/en-US/docs/Web/API/AbortController",
    "src/maybe.js~AbortController",
    "external"
  ],
  [
    "src/maybe.js~iterable",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols",
    "src/maybe.js~Iterable",
    "external"
  ],
  [
    "src/maybe.js~maybe#ambwith",
    "class/src/maybe.js~Maybe.html#instance-method-ambWith",
    "src/maybe.js~Maybe#ambWith",
    "method"
  ],
  [
    "src/maybe.js~maybe#cache",
    "class/src/maybe.js~Maybe.html#instance-method-cache",
    "src/maybe.js~Maybe#cache",
    "method"
  ],
  [
    "src/maybe.js~maybe#catch",
    "class/src/maybe.js~Maybe.html#instance-method-catch",
    "src/maybe.js~Maybe#catch",
    "method"
  ],
  [
    "src/maybe.js~maybe#compose",
    "class/src/maybe.js~Maybe.html#instance-method-compose",
    "src/maybe.js~Maybe#compose",
    "method"
  ],
  [
    "src/maybe.js~maybe#defaultifempty",
    "class/src/maybe.js~Maybe.html#instance-method-defaultIfEmpty",
    "src/maybe.js~Maybe#defaultIfEmpty",
    "method"
  ],
  [
    "src/maybe.js~maybe#delay",
    "class/src/maybe.js~Maybe.html#instance-method-delay",
    "src/maybe.js~Maybe#delay",
    "method"
  ],
  [
    "src/maybe.js~maybe#delaysubscription",
    "class/src/maybe.js~Maybe.html#instance-method-delaySubscription",
    "src/maybe.js~Maybe#delaySubscription",
    "method"
  ],
  [
    "src/maybe.js~maybe#delayuntil",
    "class/src/maybe.js~Maybe.html#instance-method-delayUntil",
    "src/maybe.js~Maybe#delayUntil",
    "method"
  ],
  [
    "src/maybe.js~maybe#doaftersuccess",
    "class/src/maybe.js~Maybe.html#instance-method-doAfterSuccess",
    "src/maybe.js~Maybe#doAfterSuccess",
    "method"
  ],
  [
    "src/maybe.js~maybe#doafterterminate",
    "class/src/maybe.js~Maybe.html#instance-method-doAfterTerminate",
    "src/maybe.js~Maybe#doAfterTerminate",
    "method"
  ],
  [
    "src/maybe.js~maybe#dofinally",
    "class/src/maybe.js~Maybe.html#instance-method-doFinally",
    "src/maybe.js~Maybe#doFinally",
    "method"
  ],
  [
    "src/maybe.js~maybe#doonabort",
    "class/src/maybe.js~Maybe.html#instance-method-doOnAbort",
    "src/maybe.js~Maybe#doOnAbort",
    "method"
  ],
  [
    "src/maybe.js~maybe#dooncomplete",
    "class/src/maybe.js~Maybe.html#instance-method-doOnComplete",
    "src/maybe.js~Maybe#doOnComplete",
    "method"
  ],
  [
    "src/maybe.js~maybe#doonerror",
    "class/src/maybe.js~Maybe.html#instance-method-doOnError",
    "src/maybe.js~Maybe#doOnError",
    "method"
  ],
  [
    "src/maybe.js~maybe#doonevent",
    "class/src/maybe.js~Maybe.html#instance-method-doOnEvent",
    "src/maybe.js~Maybe#doOnEvent",
    "method"
  ],
  [
    "src/maybe.js~maybe#doonsubscribe",
    "class/src/maybe.js~Maybe.html#instance-method-doOnSubscribe",
    "src/maybe.js~Maybe#doOnSubscribe",
    "method"
  ],
  [
    "src/maybe.js~maybe#doonsuccess",
    "class/src/maybe.js~Maybe.html#instance-method-doOnSuccess",
    "src/maybe.js~Maybe#doOnSuccess",
    "method"
  ],
  [
    "src/maybe.js~maybe#doonterminate",
    "class/src/maybe.js~Maybe.html#instance-method-doOnTerminate",
    "src/maybe.js~Maybe#doOnTerminate",
    "method"
  ],
  [
    "src/maybe.js~maybe#filter",
    "class/src/maybe.js~Maybe.html#instance-method-filter",
    "src/maybe.js~Maybe#filter",
    "method"
  ],
  [
    "src/maybe.js~maybe#flatmap",
    "class/src/maybe.js~Maybe.html#instance-method-flatMap",
    "src/maybe.js~Maybe#flatMap",
    "method"
  ],
  [
    "src/maybe.js~maybe#lift",
    "class/src/maybe.js~Maybe.html#instance-method-lift",
    "src/maybe.js~Maybe#lift",
    "method"
  ],
  [
    "src/maybe.js~maybe#map",
    "class/src/maybe.js~Maybe.html#instance-method-map",
    "src/maybe.js~Maybe#map",
    "method"
  ],
  [
    "src/maybe.js~maybe#observeon",
    "class/src/maybe.js~Maybe.html#instance-method-observeOn",
    "src/maybe.js~Maybe#observeOn",
    "method"
  ],
  [
    "src/maybe.js~maybe#onerrorcomplete",
    "class/src/maybe.js~Maybe.html#instance-method-onErrorComplete",
    "src/maybe.js~Maybe#onErrorComplete",
    "method"
  ],
  [
    "src/maybe.js~maybe#onerrorresumenext",
    "class/src/maybe.js~Maybe.html#instance-method-onErrorResumeNext",
    "src/maybe.js~Maybe#onErrorResumeNext",
    "method"
  ],
  [
    "src/maybe.js~maybe#onerrorreturn",
    "class/src/maybe.js~Maybe.html#instance-method-onErrorReturn",
    "src/maybe.js~Maybe#onErrorReturn",
    "method"
  ],
  [
    "src/maybe.js~maybe#onerrorreturnitem",
    "class/src/maybe.js~Maybe.html#instance-method-onErrorReturnItem",
    "src/maybe.js~Maybe#onErrorReturnItem",
    "method"
  ],
  [
    "src/maybe.js~maybe#retry",
    "class/src/maybe.js~Maybe.html#instance-method-retry",
    "src/maybe.js~Maybe#retry",
    "method"
  ],
  [
    "src/maybe.js~maybe#subscribe",
    "class/src/maybe.js~Maybe.html#instance-method-subscribe",
    "src/maybe.js~Maybe#subscribe",
    "method"
  ],
  [
    "src/maybe.js~maybe#subscribeon",
    "class/src/maybe.js~Maybe.html#instance-method-subscribeOn",
    "src/maybe.js~Maybe#subscribeOn",
    "method"
  ],
  [
    "src/maybe.js~maybe#subscribewith",
    "class/src/maybe.js~Maybe.html#instance-method-subscribeWith",
    "src/maybe.js~Maybe#subscribeWith",
    "method"
  ],
  [
    "src/maybe.js~maybe#switchifempty",
    "class/src/maybe.js~Maybe.html#instance-method-switchIfEmpty",
    "src/maybe.js~Maybe#switchIfEmpty",
    "method"
  ],
  [
    "src/maybe.js~maybe#takeuntil",
    "class/src/maybe.js~Maybe.html#instance-method-takeUntil",
    "src/maybe.js~Maybe#takeUntil",
    "method"
  ],
  [
    "src/maybe.js~maybe#then",
    "class/src/maybe.js~Maybe.html#instance-method-then",
    "src/maybe.js~Maybe#then",
    "method"
  ],
  [
    "src/maybe.js~maybe#timeout",
    "class/src/maybe.js~Maybe.html#instance-method-timeout",
    "src/maybe.js~Maybe#timeout",
    "method"
  ],
  [
    "src/maybe.js~maybe#topromise",
    "class/src/maybe.js~Maybe.html#instance-method-toPromise",
    "src/maybe.js~Maybe#toPromise",
    "method"
  ],
  [
    "src/maybe.js~maybe#zipwith",
    "class/src/maybe.js~Maybe.html#instance-method-zipWith",
    "src/maybe.js~Maybe#zipWith",
    "method"
  ],
  [
    "src/maybe.js~maybe.amb",
    "class/src/maybe.js~Maybe.html#static-method-amb",
    "src/maybe.js~Maybe.amb",
    "method"
  ],
  [
    "src/maybe.js~maybe.create",
    "class/src/maybe.js~Maybe.html#static-method-create",
    "src/maybe.js~Maybe.create",
    "method"
  ],
  [
    "src/maybe.js~maybe.defer",
    "class/src/maybe.js~Maybe.html#static-method-defer",
    "src/maybe.js~Maybe.defer",
    "method"
  ],
  [
    "src/maybe.js~maybe.empty",
    "class/src/maybe.js~Maybe.html#static-method-empty",
    "src/maybe.js~Maybe.empty",
    "method"
  ],
  [
    "src/maybe.js~maybe.error",
    "class/src/maybe.js~Maybe.html#static-method-error",
    "src/maybe.js~Maybe.error",
    "method"
  ],
  [
    "src/maybe.js~maybe.fromcallable",
    "class/src/maybe.js~Maybe.html#static-method-fromCallable",
    "src/maybe.js~Maybe.fromCallable",
    "method"
  ],
  [
    "src/maybe.js~maybe.frompromise",
    "class/src/maybe.js~Maybe.html#static-method-fromPromise",
    "src/maybe.js~Maybe.fromPromise",
    "method"
  ],
  [
    "src/maybe.js~maybe.fromresolvable",
    "class/src/maybe.js~Maybe.html#static-method-fromResolvable",
    "src/maybe.js~Maybe.fromResolvable",
    "method"
  ],
  [
    "src/maybe.js~maybe.just",
    "class/src/maybe.js~Maybe.html#static-method-just",
    "src/maybe.js~Maybe.just",
    "method"
  ],
  [
    "src/maybe.js~maybe.merge",
    "class/src/maybe.js~Maybe.html#static-method-merge",
    "src/maybe.js~Maybe.merge",
    "method"
  ],
  [
    "src/maybe.js~maybe.never",
    "class/src/maybe.js~Maybe.html#static-method-never",
    "src/maybe.js~Maybe.never",
    "method"
  ],
  [
    "src/maybe.js~maybe.timer",
    "class/src/maybe.js~Maybe.html#static-method-timer",
    "src/maybe.js~Maybe.timer",
    "method"
  ],
  [
    "src/maybe.js~maybe.zip",
    "class/src/maybe.js~Maybe.html#static-method-zip",
    "src/maybe.js~Maybe.zip",
    "method"
  ],
  [
    "src/maybe.js~promiselike",
    "https://promisesaplus.com/",
    "src/maybe.js~PromiseLike",
    "external"
  ],
  [
    "src/maybe.js~thennable",
    "https://promisesaplus.com/",
    "src/maybe.js~Thennable",
    "external"
  ],
  [
    "src/observer.js",
    "file/src/observer.js.html",
    "src/observer.js",
    "file"
  ],
  [
    "src/observer.js~observer#oncomplete",
    "class/src/observer.js~Observer.html#instance-method-onComplete",
    "src/observer.js~Observer#onComplete",
    "method"
  ],
  [
    "src/observer.js~observer#onerror",
    "class/src/observer.js~Observer.html#instance-method-onError",
    "src/observer.js~Observer#onError",
    "method"
  ],
  [
    "src/observer.js~observer#onsubscribe",
    "class/src/observer.js~Observer.html#instance-method-onSubscribe",
    "src/observer.js~Observer#onSubscribe",
    "method"
  ],
  [
    "src/observer.js~observer#onsuccess",
    "class/src/observer.js~Observer.html#instance-method-onSuccess",
    "src/observer.js~Observer#onSuccess",
    "method"
  ],
  [
    "test/amb.js",
    "test-file/test/amb.js.html",
    "test/amb.js",
    "testFile"
  ],
  [
    "test/ambwith.js",
    "test-file/test/ambWith.js.html",
    "test/ambWith.js",
    "testFile"
  ],
  [
    "test/cache.js",
    "test-file/test/cache.js.html",
    "test/cache.js",
    "testFile"
  ],
  [
    "test/catch.js",
    "test-file/test/catch.js.html",
    "test/catch.js",
    "testFile"
  ],
  [
    "test/compose.js",
    "test-file/test/compose.js.html",
    "test/compose.js",
    "testFile"
  ],
  [
    "test/create.js",
    "test-file/test/create.js.html",
    "test/create.js",
    "testFile"
  ],
  [
    "test/defaultifempty.js",
    "test-file/test/defaultIfEmpty.js.html",
    "test/defaultIfEmpty.js",
    "testFile"
  ],
  [
    "test/defer.js",
    "test-file/test/defer.js.html",
    "test/defer.js",
    "testFile"
  ],
  [
    "test/delay.js",
    "test-file/test/delay.js.html",
    "test/delay.js",
    "testFile"
  ],
  [
    "test/delaysubscription.js",
    "test-file/test/delaySubscription.js.html",
    "test/delaySubscription.js",
    "testFile"
  ],
  [
    "test/delayuntil.js",
    "test-file/test/delayUntil.js.html",
    "test/delayUntil.js",
    "testFile"
  ],
  [
    "test/doaftersuccess.js",
    "test-file/test/doAfterSuccess.js.html",
    "test/doAfterSuccess.js",
    "testFile"
  ],
  [
    "test/doafterterminate.js",
    "test-file/test/doAfterTerminate.js.html",
    "test/doAfterTerminate.js",
    "testFile"
  ],
  [
    "test/dofinally.js",
    "test-file/test/doFinally.js.html",
    "test/doFinally.js",
    "testFile"
  ],
  [
    "test/doonabort.js",
    "test-file/test/doOnAbort.js.html",
    "test/doOnAbort.js",
    "testFile"
  ],
  [
    "test/dooncomplete.js",
    "test-file/test/doOnComplete.js.html",
    "test/doOnComplete.js",
    "testFile"
  ],
  [
    "test/doonerror.js",
    "test-file/test/doOnError.js.html",
    "test/doOnError.js",
    "testFile"
  ],
  [
    "test/doonevent.js",
    "test-file/test/doOnEvent.js.html",
    "test/doOnEvent.js",
    "testFile"
  ],
  [
    "test/doonsubscribe.js",
    "test-file/test/doOnSubscribe.js.html",
    "test/doOnSubscribe.js",
    "testFile"
  ],
  [
    "test/doonsuccess.js",
    "test-file/test/doOnSuccess.js.html",
    "test/doOnSuccess.js",
    "testFile"
  ],
  [
    "test/doonterminate.js",
    "test-file/test/doOnTerminate.js.html",
    "test/doOnTerminate.js",
    "testFile"
  ],
  [
    "test/error.js",
    "test-file/test/error.js.html",
    "test/error.js",
    "testFile"
  ],
  [
    "test/filter.js",
    "test-file/test/filter.js.html",
    "test/filter.js",
    "testFile"
  ],
  [
    "test/flatmap.js",
    "test-file/test/flatMap.js.html",
    "test/flatMap.js",
    "testFile"
  ],
  [
    "test/fromcallable.js",
    "test-file/test/fromCallable.js.html",
    "test/fromCallable.js",
    "testFile"
  ],
  [
    "test/frompromise.js",
    "test-file/test/fromPromise.js.html",
    "test/fromPromise.js",
    "testFile"
  ],
  [
    "test/fromresolvable.js",
    "test-file/test/fromResolvable.js.html",
    "test/fromResolvable.js",
    "testFile"
  ],
  [
    "test/just.js",
    "test-file/test/just.js.html",
    "test/just.js",
    "testFile"
  ],
  [
    "test/lift.js",
    "test-file/test/lift.js.html",
    "test/lift.js",
    "testFile"
  ],
  [
    "test/map.js",
    "test-file/test/map.js.html",
    "test/map.js",
    "testFile"
  ],
  [
    "test/merge.js",
    "test-file/test/merge.js.html",
    "test/merge.js",
    "testFile"
  ],
  [
    "test/never.js",
    "test-file/test/never.js.html",
    "test/never.js",
    "testFile"
  ],
  [
    "test/observeon.js",
    "test-file/test/observeOn.js.html",
    "test/observeOn.js",
    "testFile"
  ],
  [
    "test/onerrorcomplete.js",
    "test-file/test/onErrorComplete.js.html",
    "test/onErrorComplete.js",
    "testFile"
  ],
  [
    "test/onerrorresumenext.js",
    "test-file/test/onErrorResumeNext.js.html",
    "test/onErrorResumeNext.js",
    "testFile"
  ],
  [
    "test/onerrorreturn.js",
    "test-file/test/onErrorReturn.js.html",
    "test/onErrorReturn.js",
    "testFile"
  ],
  [
    "test/onerrorreturnitem.js",
    "test-file/test/onErrorReturnItem.js.html",
    "test/onErrorReturnItem.js",
    "testFile"
  ],
  [
    "test/retry.js",
    "test-file/test/retry.js.html",
    "test/retry.js",
    "testFile"
  ],
  [
    "test/subscribeon.js",
    "test-file/test/subscribeOn.js.html",
    "test/subscribeOn.js",
    "testFile"
  ],
  [
    "test/switchifempty.js",
    "test-file/test/switchIfEmpty.js.html",
    "test/switchIfEmpty.js",
    "testFile"
  ],
  [
    "test/takeuntil.js",
    "test-file/test/takeUntil.js.html",
    "test/takeUntil.js",
    "testFile"
  ],
  [
    "test/then.js",
    "test-file/test/then.js.html",
    "test/then.js",
    "testFile"
  ],
  [
    "test/timeout.js",
    "test-file/test/timeout.js.html",
    "test/timeout.js",
    "testFile"
  ],
  [
    "test/timer.js",
    "test-file/test/timer.js.html",
    "test/timer.js",
    "testFile"
  ],
  [
    "test/topromise.js",
    "test-file/test/toPromise.js.html",
    "test/toPromise.js",
    "testFile"
  ],
  [
    "test/zip.js",
    "test-file/test/zip.js.html",
    "test/zip.js",
    "testFile"
  ],
  [
    "test/zipwith.js",
    "test-file/test/zipWith.js.html",
    "test/zipWith.js",
    "testFile"
  ]
]