window.esdocSearchIndex = [
  [
    "regrets-js/src/async-and.js~and",
    "function/index.html#static-function-And",
    "<span>And</span> <span class=\"search-result-import-path\">regrets-js/src/async-and.js</span>",
    "function"
  ],
  [
    "regrets-js/src/async-for-each.js~asyncforeach",
    "class/src/async-for-each.js~AsyncForEach.html",
    "<span>AsyncForEach</span> <span class=\"search-result-import-path\">regrets-js/src/async-for-each.js</span>",
    "class"
  ],
  [
    "regrets-js/src/async-if.js~asyncif",
    "class/src/async-if.js~AsyncIf.html",
    "<span>AsyncIf</span> <span class=\"search-result-import-path\">regrets-js/src/async-if.js</span>",
    "class"
  ],
  [
    "regrets-js/src/async-repeat.js~asyncrepeat",
    "class/src/async-repeat.js~AsyncRepeat.html",
    "<span>AsyncRepeat</span> <span class=\"search-result-import-path\">regrets-js/src/async-repeat.js</span>",
    "class"
  ],
  [
    "regrets-js/src/async-switch.js~asyncswitch",
    "class/src/async-switch.js~AsyncSwitch.html",
    "<span>AsyncSwitch</span> <span class=\"search-result-import-path\">regrets-js/src/async-switch.js</span>",
    "class"
  ],
  [
    "regrets-js/src/async-while.js~asyncwhile",
    "class/src/async-while.js~AsyncWhile.html",
    "<span>AsyncWhile</span> <span class=\"search-result-import-path\">regrets-js/src/async-while.js</span>",
    "class"
  ],
  [
    "regrets-js/src/async-eq.js~eq",
    "function/index.html#static-function-EQ",
    "<span>EQ</span> <span class=\"search-result-import-path\">regrets-js/src/async-eq.js</span>",
    "function"
  ],
  [
    "regrets-js/src/async-ge.js~ge",
    "function/index.html#static-function-GE",
    "<span>GE</span> <span class=\"search-result-import-path\">regrets-js/src/async-ge.js</span>",
    "function"
  ],
  [
    "regrets-js/src/async-gt.js~gt",
    "function/index.html#static-function-GT",
    "<span>GT</span> <span class=\"search-result-import-path\">regrets-js/src/async-gt.js</span>",
    "function"
  ],
  [
    "regrets-js/src/async-le.js~le",
    "function/index.html#static-function-LE",
    "<span>LE</span> <span class=\"search-result-import-path\">regrets-js/src/async-le.js</span>",
    "function"
  ],
  [
    "regrets-js/src/async-lt.js~lt",
    "function/index.html#static-function-LT",
    "<span>LT</span> <span class=\"search-result-import-path\">regrets-js/src/async-lt.js</span>",
    "function"
  ],
  [
    "regrets-js/src/async-ne.js~ne",
    "function/index.html#static-function-NE",
    "<span>NE</span> <span class=\"search-result-import-path\">regrets-js/src/async-ne.js</span>",
    "function"
  ],
  [
    "regrets-js/src/async-not.js~not",
    "function/index.html#static-function-Not",
    "<span>Not</span> <span class=\"search-result-import-path\">regrets-js/src/async-not.js</span>",
    "function"
  ],
  [
    "regrets-js/src/async-or.js~or",
    "function/index.html#static-function-Or",
    "<span>Or</span> <span class=\"search-result-import-path\">regrets-js/src/async-or.js</span>",
    "function"
  ],
  [
    "",
    "test-file/test/async-and.js.html#lineNumber8",
    "And",
    "test"
  ],
  [
    "",
    "test-file/test/async-and.js.html#lineNumber24",
    "And should resolve to false if one of the values are falsey",
    "test"
  ],
  [
    "",
    "test-file/test/async-and.js.html#lineNumber18",
    "And should resolve to true if both resolved values are truthy",
    "test"
  ],
  [
    "",
    "test-file/test/async-and.js.html#lineNumber12",
    "And should return a Promise",
    "test"
  ],
  [
    "",
    "test-file/test/async-for-each.js.html#lineNumber5",
    "AsyncForEach",
    "test"
  ],
  [
    "",
    "test-file/test/async-for-each.js.html#lineNumber6",
    "AsyncForEach #do",
    "test"
  ],
  [
    "",
    "test-file/test/async-for-each.js.html#lineNumber10",
    "AsyncForEach #do should iterate all items in the iterable",
    "test"
  ],
  [
    "",
    "test-file/test/async-for-each.js.html#lineNumber7",
    "AsyncForEach #do should return a Promise",
    "test"
  ],
  [
    "",
    "test-file/test/async-if.js.html#lineNumber9",
    "AsyncIf",
    "test"
  ],
  [
    "",
    "test-file/test/async-if.js.html#lineNumber55",
    "AsyncIf #else",
    "test"
  ],
  [
    "",
    "test-file/test/async-if.js.html#lineNumber65",
    "AsyncIf #else should execute if the resolved promise is falsey",
    "test"
  ],
  [
    "",
    "test-file/test/async-if.js.html#lineNumber73",
    "AsyncIf #else should not execute if the resolved promise is truthy",
    "test"
  ],
  [
    "",
    "test-file/test/async-if.js.html#lineNumber59",
    "AsyncIf #else should return an AsyncIf instance",
    "test"
  ],
  [
    "",
    "test-file/test/async-if.js.html#lineNumber83",
    "AsyncIf #else should return the same instance if the passed value is not a function",
    "test"
  ],
  [
    "",
    "test-file/test/async-if.js.html#lineNumber97",
    "AsyncIf #elseIf",
    "test"
  ],
  [
    "",
    "test-file/test/async-if.js.html#lineNumber107",
    "AsyncIf #elseIf should execute if the resolved promise is falsey",
    "test"
  ],
  [
    "",
    "test-file/test/async-if.js.html#lineNumber116",
    "AsyncIf #elseIf should not execute if the resolved promise is truthy",
    "test"
  ],
  [
    "",
    "test-file/test/async-if.js.html#lineNumber101",
    "AsyncIf #elseIf should return an AsyncIf instance",
    "test"
  ],
  [
    "",
    "test-file/test/async-if.js.html#lineNumber13",
    "AsyncIf #then",
    "test"
  ],
  [
    "",
    "test-file/test/async-if.js.html#lineNumber23",
    "AsyncIf #then should execute if the resolved promise is truthy",
    "test"
  ],
  [
    "",
    "test-file/test/async-if.js.html#lineNumber31",
    "AsyncIf #then should not execute if the resolved promise is falsey",
    "test"
  ],
  [
    "",
    "test-file/test/async-if.js.html#lineNumber17",
    "AsyncIf #then should return an AsyncIf instance",
    "test"
  ],
  [
    "",
    "test-file/test/async-if.js.html#lineNumber41",
    "AsyncIf #then should return the same instance if the passed value is not a function",
    "test"
  ],
  [
    "",
    "test-file/test/async-repeat.js.html#lineNumber8",
    "AsyncRepeat",
    "test"
  ],
  [
    "",
    "test-file/test/async-repeat.js.html#lineNumber12",
    "AsyncRepeat #until",
    "test"
  ],
  [
    "",
    "test-file/test/async-repeat.js.html#lineNumber22",
    "AsyncRepeat #until should execute multiple times until the evaluator is true",
    "test"
  ],
  [
    "",
    "test-file/test/async-repeat.js.html#lineNumber16",
    "AsyncRepeat #until should return a Promise",
    "test"
  ],
  [
    "",
    "test-file/test/async-switch.js.html#lineNumber5",
    "AsyncSwitch",
    "test"
  ],
  [
    "",
    "test-file/test/async-switch.js.html#lineNumber12",
    "AsyncSwitch #break",
    "test"
  ],
  [
    "",
    "test-file/test/async-switch.js.html#lineNumber13",
    "AsyncSwitch #break should return the same AsyncSwitch reference",
    "test"
  ],
  [
    "",
    "test-file/test/async-switch.js.html#lineNumber6",
    "AsyncSwitch #case",
    "test"
  ],
  [
    "",
    "test-file/test/async-switch.js.html#lineNumber7",
    "AsyncSwitch #case should return the same AsyncSwitch reference",
    "test"
  ],
  [
    "",
    "test-file/test/async-switch.js.html#lineNumber40",
    "AsyncSwitch #default",
    "test"
  ],
  [
    "",
    "test-file/test/async-switch.js.html#lineNumber44",
    "AsyncSwitch #default should execute the scope if no break signals are sent",
    "test"
  ],
  [
    "",
    "test-file/test/async-switch.js.html#lineNumber47",
    "AsyncSwitch #default should execute the scope ifa match is unsuccessful",
    "test"
  ],
  [
    "",
    "test-file/test/async-switch.js.html#lineNumber50",
    "AsyncSwitch #default should not execute the scope if a break signal is received before.",
    "test"
  ],
  [
    "",
    "test-file/test/async-switch.js.html#lineNumber41",
    "AsyncSwitch #default should return a Promise",
    "test"
  ],
  [
    "",
    "test-file/test/async-switch.js.html#lineNumber18",
    "AsyncSwitch #do",
    "test"
  ],
  [
    "",
    "test-file/test/async-switch.js.html#lineNumber22",
    "AsyncSwitch #do should execute the scope if a match is successful",
    "test"
  ],
  [
    "",
    "test-file/test/async-switch.js.html#lineNumber29",
    "AsyncSwitch #do should not execute the scope if a match is successful but a break signal is received before.",
    "test"
  ],
  [
    "",
    "test-file/test/async-switch.js.html#lineNumber25",
    "AsyncSwitch #do should not execute the scope if a match is unsuccessful",
    "test"
  ],
  [
    "",
    "test-file/test/async-switch.js.html#lineNumber19",
    "AsyncSwitch #do should return an AsyncSwitch",
    "test"
  ],
  [
    "",
    "test-file/test/async-while.js.html#lineNumber8",
    "AsyncWhile",
    "test"
  ],
  [
    "",
    "test-file/test/async-while.js.html#lineNumber12",
    "AsyncWhile #do",
    "test"
  ],
  [
    "",
    "test-file/test/async-while.js.html#lineNumber22",
    "AsyncWhile #do should execute multiple times until the evaluator is false",
    "test"
  ],
  [
    "",
    "test-file/test/async-while.js.html#lineNumber16",
    "AsyncWhile #do should return a Promise",
    "test"
  ],
  [
    "",
    "test-file/test/async-eq.js.html#lineNumber8",
    "EQ",
    "test"
  ],
  [
    "",
    "test-file/test/async-eq.js.html#lineNumber24",
    "EQ should resolve to false if both values are not equal",
    "test"
  ],
  [
    "",
    "test-file/test/async-eq.js.html#lineNumber18",
    "EQ should resolve to true if both values are equal",
    "test"
  ],
  [
    "",
    "test-file/test/async-eq.js.html#lineNumber12",
    "EQ should return a Promise",
    "test"
  ],
  [
    "",
    "test-file/test/async-ge.js.html#lineNumber8",
    "GE",
    "test"
  ],
  [
    "",
    "test-file/test/async-ge.js.html#lineNumber30",
    "GE should resolve to false if a value is less than the other value",
    "test"
  ],
  [
    "",
    "test-file/test/async-ge.js.html#lineNumber24",
    "GE should resolve to true if a value is equal to the other value",
    "test"
  ],
  [
    "",
    "test-file/test/async-ge.js.html#lineNumber18",
    "GE should resolve to true if a value is greater than the other value",
    "test"
  ],
  [
    "",
    "test-file/test/async-ge.js.html#lineNumber12",
    "GE should return a Promise",
    "test"
  ],
  [
    "",
    "test-file/test/async-gt.js.html#lineNumber8",
    "GT",
    "test"
  ],
  [
    "",
    "test-file/test/async-gt.js.html#lineNumber24",
    "GT should resolve to false if a value is equal to the other value",
    "test"
  ],
  [
    "",
    "test-file/test/async-gt.js.html#lineNumber30",
    "GT should resolve to false if a value is less than the other value",
    "test"
  ],
  [
    "",
    "test-file/test/async-gt.js.html#lineNumber18",
    "GT should resolve to true if a value is greater than the other value",
    "test"
  ],
  [
    "",
    "test-file/test/async-gt.js.html#lineNumber12",
    "GT should return a Promise",
    "test"
  ],
  [
    "",
    "test-file/test/async-le.js.html#lineNumber8",
    "LE",
    "test"
  ],
  [
    "",
    "test-file/test/async-le.js.html#lineNumber30",
    "LE should resolve to false if a value is greater than the other value",
    "test"
  ],
  [
    "",
    "test-file/test/async-le.js.html#lineNumber24",
    "LE should resolve to true if a value is equal to the other value",
    "test"
  ],
  [
    "",
    "test-file/test/async-le.js.html#lineNumber18",
    "LE should resolve to true if a value is less than the other value",
    "test"
  ],
  [
    "",
    "test-file/test/async-le.js.html#lineNumber12",
    "LE should return a Promise",
    "test"
  ],
  [
    "",
    "test-file/test/async-lt.js.html#lineNumber8",
    "LT",
    "test"
  ],
  [
    "",
    "test-file/test/async-lt.js.html#lineNumber24",
    "LT should resolve to false if a value is equal to the other value",
    "test"
  ],
  [
    "",
    "test-file/test/async-lt.js.html#lineNumber30",
    "LT should resolve to false if a value is greater than the other value",
    "test"
  ],
  [
    "",
    "test-file/test/async-lt.js.html#lineNumber18",
    "LT should resolve to true if a value is less than the other value",
    "test"
  ],
  [
    "",
    "test-file/test/async-lt.js.html#lineNumber12",
    "LT should return a Promise",
    "test"
  ],
  [
    "",
    "test-file/test/async-ne.js.html#lineNumber8",
    "NE",
    "test"
  ],
  [
    "",
    "test-file/test/async-ne.js.html#lineNumber24",
    "NE should resolve to false if both values are equal",
    "test"
  ],
  [
    "",
    "test-file/test/async-ne.js.html#lineNumber18",
    "NE should resolve to true if both values are not equal",
    "test"
  ],
  [
    "",
    "test-file/test/async-ne.js.html#lineNumber12",
    "NE should return a Promise",
    "test"
  ],
  [
    "",
    "test-file/test/async-not.js.html#lineNumber8",
    "Not",
    "test"
  ],
  [
    "",
    "test-file/test/async-not.js.html#lineNumber24",
    "Not should resolve to false if the value is truthy",
    "test"
  ],
  [
    "",
    "test-file/test/async-not.js.html#lineNumber18",
    "Not should resolve to true if the value is falsey",
    "test"
  ],
  [
    "",
    "test-file/test/async-not.js.html#lineNumber12",
    "Not should return a Promise",
    "test"
  ],
  [
    "",
    "test-file/test/async-or.js.html#lineNumber8",
    "Or",
    "test"
  ],
  [
    "",
    "test-file/test/async-or.js.html#lineNumber24",
    "Or should resolve to false if both resolved values are falsey",
    "test"
  ],
  [
    "",
    "test-file/test/async-or.js.html#lineNumber18",
    "Or should resolve to true if one of the values are truthy",
    "test"
  ],
  [
    "",
    "test-file/test/async-or.js.html#lineNumber12",
    "Or should return a Promise",
    "test"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/async-and.js",
    "file/src/async-and.js.html",
    "src/async-and.js",
    "file"
  ],
  [
    "src/async-eq.js",
    "file/src/async-eq.js.html",
    "src/async-eq.js",
    "file"
  ],
  [
    "src/async-for-each.js",
    "file/src/async-for-each.js.html",
    "src/async-for-each.js",
    "file"
  ],
  [
    "src/async-for-each.js~asyncforeach#constructor",
    "class/src/async-for-each.js~AsyncForEach.html#instance-constructor-constructor",
    "src/async-for-each.js~AsyncForEach#constructor",
    "method"
  ],
  [
    "src/async-for-each.js~asyncforeach#do",
    "class/src/async-for-each.js~AsyncForEach.html#instance-method-do",
    "src/async-for-each.js~AsyncForEach#do",
    "method"
  ],
  [
    "src/async-ge.js",
    "file/src/async-ge.js.html",
    "src/async-ge.js",
    "file"
  ],
  [
    "src/async-gt.js",
    "file/src/async-gt.js.html",
    "src/async-gt.js",
    "file"
  ],
  [
    "src/async-if.js",
    "file/src/async-if.js.html",
    "src/async-if.js",
    "file"
  ],
  [
    "src/async-if.js~asyncif#constructor",
    "class/src/async-if.js~AsyncIf.html#instance-constructor-constructor",
    "src/async-if.js~AsyncIf#constructor",
    "method"
  ],
  [
    "src/async-if.js~asyncif#else",
    "class/src/async-if.js~AsyncIf.html#instance-method-else",
    "src/async-if.js~AsyncIf#else",
    "method"
  ],
  [
    "src/async-if.js~asyncif#elseif",
    "class/src/async-if.js~AsyncIf.html#instance-method-elseIf",
    "src/async-if.js~AsyncIf#elseIf",
    "method"
  ],
  [
    "src/async-if.js~asyncif#promise",
    "class/src/async-if.js~AsyncIf.html#instance-member-promise",
    "src/async-if.js~AsyncIf#promise",
    "member"
  ],
  [
    "src/async-if.js~asyncif#then",
    "class/src/async-if.js~AsyncIf.html#instance-method-then",
    "src/async-if.js~AsyncIf#then",
    "method"
  ],
  [
    "src/async-le.js",
    "file/src/async-le.js.html",
    "src/async-le.js",
    "file"
  ],
  [
    "src/async-lt.js",
    "file/src/async-lt.js.html",
    "src/async-lt.js",
    "file"
  ],
  [
    "src/async-ne.js",
    "file/src/async-ne.js.html",
    "src/async-ne.js",
    "file"
  ],
  [
    "src/async-not.js",
    "file/src/async-not.js.html",
    "src/async-not.js",
    "file"
  ],
  [
    "src/async-or.js",
    "file/src/async-or.js.html",
    "src/async-or.js",
    "file"
  ],
  [
    "src/async-repeat.js",
    "file/src/async-repeat.js.html",
    "src/async-repeat.js",
    "file"
  ],
  [
    "src/async-repeat.js~asyncrepeat#constructor",
    "class/src/async-repeat.js~AsyncRepeat.html#instance-constructor-constructor",
    "src/async-repeat.js~AsyncRepeat#constructor",
    "method"
  ],
  [
    "src/async-repeat.js~asyncrepeat#scope",
    "class/src/async-repeat.js~AsyncRepeat.html#instance-member-scope",
    "src/async-repeat.js~AsyncRepeat#scope",
    "member"
  ],
  [
    "src/async-repeat.js~asyncrepeat#until",
    "class/src/async-repeat.js~AsyncRepeat.html#instance-method-until",
    "src/async-repeat.js~AsyncRepeat#until",
    "method"
  ],
  [
    "src/async-switch.js",
    "file/src/async-switch.js.html",
    "src/async-switch.js",
    "file"
  ],
  [
    "src/async-switch.js~asyncswitch#break",
    "class/src/async-switch.js~AsyncSwitch.html#instance-method-break",
    "src/async-switch.js~AsyncSwitch#break",
    "method"
  ],
  [
    "src/async-switch.js~asyncswitch#case",
    "class/src/async-switch.js~AsyncSwitch.html#instance-method-case",
    "src/async-switch.js~AsyncSwitch#case",
    "method"
  ],
  [
    "src/async-switch.js~asyncswitch#constructor",
    "class/src/async-switch.js~AsyncSwitch.html#instance-constructor-constructor",
    "src/async-switch.js~AsyncSwitch#constructor",
    "method"
  ],
  [
    "src/async-switch.js~asyncswitch#default",
    "class/src/async-switch.js~AsyncSwitch.html#instance-method-default",
    "src/async-switch.js~AsyncSwitch#default",
    "method"
  ],
  [
    "src/async-switch.js~asyncswitch#do",
    "class/src/async-switch.js~AsyncSwitch.html#instance-method-do",
    "src/async-switch.js~AsyncSwitch#do",
    "method"
  ],
  [
    "src/async-switch.js~asyncswitch#subject",
    "class/src/async-switch.js~AsyncSwitch.html#instance-member-subject",
    "src/async-switch.js~AsyncSwitch#subject",
    "member"
  ],
  [
    "src/async-while.js",
    "file/src/async-while.js.html",
    "src/async-while.js",
    "file"
  ],
  [
    "src/async-while.js~asyncwhile#constructor",
    "class/src/async-while.js~AsyncWhile.html#instance-constructor-constructor",
    "src/async-while.js~AsyncWhile#constructor",
    "method"
  ],
  [
    "src/async-while.js~asyncwhile#do",
    "class/src/async-while.js~AsyncWhile.html#instance-method-do",
    "src/async-while.js~AsyncWhile#do",
    "method"
  ],
  [
    "src/async-while.js~asyncwhile#evaluator",
    "class/src/async-while.js~AsyncWhile.html#instance-member-evaluator",
    "src/async-while.js~AsyncWhile#evaluator",
    "member"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/utils.js",
    "file/src/utils.js.html",
    "src/utils.js",
    "file"
  ],
  [
    "test/async-and.js",
    "test-file/test/async-and.js.html",
    "test/async-and.js",
    "testFile"
  ],
  [
    "test/async-eq.js",
    "test-file/test/async-eq.js.html",
    "test/async-eq.js",
    "testFile"
  ],
  [
    "test/async-for-each.js",
    "test-file/test/async-for-each.js.html",
    "test/async-for-each.js",
    "testFile"
  ],
  [
    "test/async-ge.js",
    "test-file/test/async-ge.js.html",
    "test/async-ge.js",
    "testFile"
  ],
  [
    "test/async-gt.js",
    "test-file/test/async-gt.js.html",
    "test/async-gt.js",
    "testFile"
  ],
  [
    "test/async-if.js",
    "test-file/test/async-if.js.html",
    "test/async-if.js",
    "testFile"
  ],
  [
    "test/async-le.js",
    "test-file/test/async-le.js.html",
    "test/async-le.js",
    "testFile"
  ],
  [
    "test/async-lt.js",
    "test-file/test/async-lt.js.html",
    "test/async-lt.js",
    "testFile"
  ],
  [
    "test/async-ne.js",
    "test-file/test/async-ne.js.html",
    "test/async-ne.js",
    "testFile"
  ],
  [
    "test/async-not.js",
    "test-file/test/async-not.js.html",
    "test/async-not.js",
    "testFile"
  ],
  [
    "test/async-or.js",
    "test-file/test/async-or.js.html",
    "test/async-or.js",
    "testFile"
  ],
  [
    "test/async-repeat.js",
    "test-file/test/async-repeat.js.html",
    "test/async-repeat.js",
    "testFile"
  ],
  [
    "test/async-switch.js",
    "test-file/test/async-switch.js.html",
    "test/async-switch.js",
    "testFile"
  ],
  [
    "test/async-while.js",
    "test-file/test/async-while.js.html",
    "test/async-while.js",
    "testFile"
  ]
]