window.esdocSearchIndex = [
  [
    "rx-disposable/src/index.js~disposable",
    "class/src/index.js~Disposable.html",
    "<span>Disposable</span> <span class=\"search-result-import-path\">rx-disposable/src/index.js</span>",
    "class"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber6",
    "Disposable",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber12",
    "Disposable #active",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber17",
    "Disposable #active should return false if Disposable is disabled.",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber22",
    "Disposable #active should return true if Disposable is disabled then enabled.",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber34",
    "Disposable #active should return true if Disposable is disabled, disposed, and enabled.",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber28",
    "Disposable #active should return true if Disposable is enabled, disposed, and disabled.",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber13",
    "Disposable #active should return true if Disposable is enabled.",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber142",
    "Disposable #addEventListener",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber150",
    "Disposable #addEventListener should fire the disable listener if the Disposable is disabled",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber156",
    "Disposable #addEventListener should fire the dispose listener if the Disposable is disposed",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber143",
    "Disposable #addEventListener should fire the enable listener if the Disposable is enabled",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber162",
    "Disposable #addEventListener should not fire the dispose listener if the Disposable is already disposed",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber7",
    "Disposable #create",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber8",
    "Disposable #create should create a Disposable",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber74",
    "Disposable #disable",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber79",
    "Disposable #disable should return false if Disposable is disabled already.",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber75",
    "Disposable #disable should return true if Disposable is disabled after being enabled.",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber53",
    "Disposable #dispose",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber57",
    "Disposable #dispose should return false if Disposable has been disposed before.",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber54",
    "Disposable #dispose should return true if Disposable is disposed for the first time.",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber42",
    "Disposable #disposed",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber43",
    "Disposable #disposed should return true if Disposable is disposed.",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber48",
    "Disposable #disposed should return true if Disposable is not disposed.",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber63",
    "Disposable #enable",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber69",
    "Disposable #enable should return false if Disposable is enabled already.",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber64",
    "Disposable #enable should return true if Disposable is enabled after being disabled.",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber121",
    "Disposable #remove",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber122",
    "Disposable #remove should return false if the Disposable given is not the child.",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber127",
    "Disposable #remove should return false if the source is already disposed.",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber133",
    "Disposable #remove should return true if the removal is successful",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber169",
    "Disposable #removeEventListener",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber180",
    "Disposable #removeEventListener should not fire the disable listener if the Disposable is disabled",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber189",
    "Disposable #removeEventListener should not fire the dispose listener if the Disposable is disposed",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber170",
    "Disposable #removeEventListener should not fire the enable listener if the Disposable is enabled",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber85",
    "Disposable #setParent",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber93",
    "Disposable #setParent should return false if the Disposable parent given is a child of the source Disposable",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber90",
    "Disposable #setParent should return false if the Disposable parent given is not a Disposable",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber86",
    "Disposable #setParent should return false if the Disposable parent given is the same as the child",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber99",
    "Disposable #setParent should return false if the Disposable parent is already disposed.",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber113",
    "Disposable #setParent should the children be disabled if the parent is disabled",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber106",
    "Disposable #setParent should the children be disposed if the parent is disposed",
    "test"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/index.js~disposable#active",
    "class/src/index.js~Disposable.html#instance-get-active",
    "src/index.js~Disposable#active",
    "member"
  ],
  [
    "src/index.js~disposable#add",
    "class/src/index.js~Disposable.html#instance-method-add",
    "src/index.js~Disposable#add",
    "method"
  ],
  [
    "src/index.js~disposable#addeventlistener",
    "class/src/index.js~Disposable.html#instance-method-addEventListener",
    "src/index.js~Disposable#addEventListener",
    "method"
  ],
  [
    "src/index.js~disposable#disable",
    "class/src/index.js~Disposable.html#instance-method-disable",
    "src/index.js~Disposable#disable",
    "method"
  ],
  [
    "src/index.js~disposable#dispose",
    "class/src/index.js~Disposable.html#instance-method-dispose",
    "src/index.js~Disposable#dispose",
    "method"
  ],
  [
    "src/index.js~disposable#disposed",
    "class/src/index.js~Disposable.html#instance-get-disposed",
    "src/index.js~Disposable#disposed",
    "member"
  ],
  [
    "src/index.js~disposable#enable",
    "class/src/index.js~Disposable.html#instance-method-enable",
    "src/index.js~Disposable#enable",
    "method"
  ],
  [
    "src/index.js~disposable#isparentto",
    "class/src/index.js~Disposable.html#instance-method-isParentTo",
    "src/index.js~Disposable#isParentTo",
    "method"
  ],
  [
    "src/index.js~disposable#remove",
    "class/src/index.js~Disposable.html#instance-method-remove",
    "src/index.js~Disposable#remove",
    "method"
  ],
  [
    "src/index.js~disposable#removeeventlistener",
    "class/src/index.js~Disposable.html#instance-method-removeEventListener",
    "src/index.js~Disposable#removeEventListener",
    "method"
  ],
  [
    "src/index.js~disposable#removeparent",
    "class/src/index.js~Disposable.html#instance-method-removeParent",
    "src/index.js~Disposable#removeParent",
    "method"
  ],
  [
    "src/index.js~disposable#setparent",
    "class/src/index.js~Disposable.html#instance-method-setParent",
    "src/index.js~Disposable#setParent",
    "method"
  ],
  [
    "src/index.js~disposable.create",
    "class/src/index.js~Disposable.html#static-method-create",
    "src/index.js~Disposable.create",
    "method"
  ],
  [
    "test/index.js",
    "test-file/test/index.js.html",
    "test/index.js",
    "testFile"
  ]
]