window.esdocSearchIndex = [
  [
    "rx-cancellable/src/boolean.js~booleancancellable",
    "class/src/boolean.js~BooleanCancellable.html",
    "<span>BooleanCancellable</span> <span class=\"search-result-import-path\">rx-cancellable/src/boolean.js</span>",
    "class"
  ],
  [
    "rx-cancellable/src/cancelled.js~cancelled",
    "variable/index.html#static-variable-CANCELLED",
    "<span>CANCELLED</span> <span class=\"search-result-import-path\">rx-cancellable/src/cancelled.js</span>",
    "variable"
  ],
  [
    "rx-cancellable/src/cancellable.js~cancellable",
    "class/src/cancellable.js~Cancellable.html",
    "<span>Cancellable</span> <span class=\"search-result-import-path\">rx-cancellable/src/cancellable.js</span>",
    "class"
  ],
  [
    "rx-cancellable/src/cancelled.js~cancelledcancellable",
    "class/src/cancelled.js~CancelledCancellable.html",
    "<span>CancelledCancellable</span> <span class=\"search-result-import-path\">rx-cancellable/src/cancelled.js</span>",
    "class"
  ],
  [
    "rx-cancellable/src/composite.js~compositecancellable",
    "class/src/composite.js~CompositeCancellable.html",
    "<span>CompositeCancellable</span> <span class=\"search-result-import-path\">rx-cancellable/src/composite.js</span>",
    "class"
  ],
  [
    "rx-cancellable/src/linked.js~linkedcancellable",
    "class/src/linked.js~LinkedCancellable.html",
    "<span>LinkedCancellable</span> <span class=\"search-result-import-path\">rx-cancellable/src/linked.js</span>",
    "class"
  ],
  [
    "rx-cancellable/src/uncancelled.js~uncancelled",
    "variable/index.html#static-variable-UNCANCELLED",
    "<span>UNCANCELLED</span> <span class=\"search-result-import-path\">rx-cancellable/src/uncancelled.js</span>",
    "variable"
  ],
  [
    "rx-cancellable/src/uncancelled.js~uncancelledcancellable",
    "class/src/uncancelled.js~UncancelledCancellable.html",
    "<span>UncancelledCancellable</span> <span class=\"search-result-import-path\">rx-cancellable/src/uncancelled.js</span>",
    "class"
  ],
  [
    "",
    "test-file/test/boolean.js.html#lineNumber5",
    "BooleanCancellable",
    "test"
  ],
  [
    "",
    "test-file/test/boolean.js.html#lineNumber6",
    "BooleanCancellable cancel",
    "test"
  ],
  [
    "",
    "test-file/test/boolean.js.html#lineNumber11",
    "BooleanCancellable cancel should return false if instance has been cancelled before.",
    "test"
  ],
  [
    "",
    "test-file/test/boolean.js.html#lineNumber7",
    "BooleanCancellable cancel should return true if instance is never cancelled before",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber5",
    "CancelledCancellable",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber6",
    "CancelledCancellable cancel",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber7",
    "CancelledCancellable cancel should return false since it is always cancelled",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber11",
    "CancelledCancellable cancelled",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber12",
    "CancelledCancellable cancelled should return true since it is always cancelled",
    "test"
  ],
  [
    "",
    "test-file/test/composite.js.html#lineNumber5",
    "CompositeCancellable",
    "test"
  ],
  [
    "",
    "test-file/test/composite.js.html#lineNumber24",
    "CompositeCancellable add",
    "test"
  ],
  [
    "",
    "test-file/test/composite.js.html#lineNumber34",
    "CompositeCancellable add should return false and cancel given instance if source is cancelled.",
    "test"
  ],
  [
    "",
    "test-file/test/composite.js.html#lineNumber30",
    "CompositeCancellable add should return false if given instance is non-Cancellable.",
    "test"
  ],
  [
    "",
    "test-file/test/composite.js.html#lineNumber25",
    "CompositeCancellable add should return true if given instance is Cancellable",
    "test"
  ],
  [
    "",
    "test-file/test/composite.js.html#lineNumber6",
    "CompositeCancellable cancel",
    "test"
  ],
  [
    "",
    "test-file/test/composite.js.html#lineNumber16",
    "CompositeCancellable cancel should cancel the composed instances",
    "test"
  ],
  [
    "",
    "test-file/test/composite.js.html#lineNumber11",
    "CompositeCancellable cancel should return false if instance has been cancelled before.",
    "test"
  ],
  [
    "",
    "test-file/test/composite.js.html#lineNumber7",
    "CompositeCancellable cancel should return true if instance is never cancelled before",
    "test"
  ],
  [
    "",
    "test-file/test/composite.js.html#lineNumber41",
    "CompositeCancellable remove",
    "test"
  ],
  [
    "",
    "test-file/test/composite.js.html#lineNumber48",
    "CompositeCancellable remove should return false if given instance is non-Cancellable.",
    "test"
  ],
  [
    "",
    "test-file/test/composite.js.html#lineNumber52",
    "CompositeCancellable remove should return false if given instance is the same as the source.",
    "test"
  ],
  [
    "",
    "test-file/test/composite.js.html#lineNumber56",
    "CompositeCancellable remove should return false if the given instance is not in the Composite",
    "test"
  ],
  [
    "",
    "test-file/test/composite.js.html#lineNumber42",
    "CompositeCancellable remove should return true if given instance is in the composite",
    "test"
  ],
  [
    "",
    "test-file/test/linked.js.html#lineNumber5",
    "LinkedCancellable",
    "test"
  ],
  [
    "",
    "test-file/test/linked.js.html#lineNumber35",
    "LinkedCancellable cancel",
    "test"
  ],
  [
    "",
    "test-file/test/linked.js.html#lineNumber36",
    "LinkedCancellable cancel should return false if the source is cancelled",
    "test"
  ],
  [
    "",
    "test-file/test/linked.js.html#lineNumber46",
    "LinkedCancellable cancel should return true and cancel the link if there is one",
    "test"
  ],
  [
    "",
    "test-file/test/linked.js.html#lineNumber42",
    "LinkedCancellable cancel should return true if the source was never cancelled before",
    "test"
  ],
  [
    "",
    "test-file/test/linked.js.html#lineNumber65",
    "LinkedCancellable cancelled",
    "test"
  ],
  [
    "",
    "test-file/test/linked.js.html#lineNumber80",
    "LinkedCancellable cancelled should return false if the source was never cancelled",
    "test"
  ],
  [
    "",
    "test-file/test/linked.js.html#lineNumber72",
    "LinkedCancellable cancelled should return true if the link is cancelled",
    "test"
  ],
  [
    "",
    "test-file/test/linked.js.html#lineNumber66",
    "LinkedCancellable cancelled should return true if the source is cancelled",
    "test"
  ],
  [
    "",
    "test-file/test/linked.js.html#lineNumber6",
    "LinkedCancellable link",
    "test"
  ],
  [
    "",
    "test-file/test/linked.js.html#lineNumber21",
    "LinkedCancellable link should return false and cancel the given Cancellable if the source is cancelled",
    "test"
  ],
  [
    "",
    "test-file/test/linked.js.html#lineNumber14",
    "LinkedCancellable link should return false and cancel the source if the given Cancellable is cancelled",
    "test"
  ],
  [
    "",
    "test-file/test/linked.js.html#lineNumber7",
    "LinkedCancellable link should return false if the given argument is a non-Cancellable",
    "test"
  ],
  [
    "",
    "test-file/test/linked.js.html#lineNumber10",
    "LinkedCancellable link should return false if the given argument is the same as the source",
    "test"
  ],
  [
    "",
    "test-file/test/linked.js.html#lineNumber28",
    "LinkedCancellable link should return true if both the source and the given Cancellable are not cancelled",
    "test"
  ],
  [
    "",
    "test-file/test/linked.js.html#lineNumber53",
    "LinkedCancellable unlink",
    "test"
  ],
  [
    "",
    "test-file/test/linked.js.html#lineNumber54",
    "LinkedCancellable unlink should return false if the source is cancelled",
    "test"
  ],
  [
    "",
    "test-file/test/linked.js.html#lineNumber60",
    "LinkedCancellable unlink should return false if there is no link.",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber18",
    "UncancelledCancellable",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber19",
    "UncancelledCancellable cancel",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber20",
    "UncancelledCancellable cancel should return false since it is uncancellable",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber24",
    "UncancelledCancellable cancelled",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber25",
    "UncancelledCancellable cancelled should return false since it is uncancellable",
    "test"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/boolean.js",
    "file/src/boolean.js.html",
    "src/boolean.js",
    "file"
  ],
  [
    "src/boolean.js~booleancancellable#cancel",
    "class/src/boolean.js~BooleanCancellable.html#instance-method-cancel",
    "src/boolean.js~BooleanCancellable#cancel",
    "method"
  ],
  [
    "src/boolean.js~booleancancellable#cancelled",
    "class/src/boolean.js~BooleanCancellable.html#instance-get-cancelled",
    "src/boolean.js~BooleanCancellable#cancelled",
    "member"
  ],
  [
    "src/boolean.js~booleancancellable#constructor",
    "class/src/boolean.js~BooleanCancellable.html#instance-constructor-constructor",
    "src/boolean.js~BooleanCancellable#constructor",
    "method"
  ],
  [
    "src/cancellable.js",
    "file/src/cancellable.js.html",
    "src/cancellable.js",
    "file"
  ],
  [
    "src/cancellable.js~cancellable#addeventlistener",
    "class/src/cancellable.js~Cancellable.html#instance-method-addEventListener",
    "src/cancellable.js~Cancellable#addEventListener",
    "method"
  ],
  [
    "src/cancellable.js~cancellable#cancel",
    "class/src/cancellable.js~Cancellable.html#instance-method-cancel",
    "src/cancellable.js~Cancellable#cancel",
    "method"
  ],
  [
    "src/cancellable.js~cancellable#cancelled",
    "class/src/cancellable.js~Cancellable.html#instance-get-cancelled",
    "src/cancellable.js~Cancellable#cancelled",
    "member"
  ],
  [
    "src/cancellable.js~cancellable#removeeventlistener",
    "class/src/cancellable.js~Cancellable.html#instance-method-removeEventListener",
    "src/cancellable.js~Cancellable#removeEventListener",
    "method"
  ],
  [
    "src/cancelled.js",
    "file/src/cancelled.js.html",
    "src/cancelled.js",
    "file"
  ],
  [
    "src/cancelled.js~cancelledcancellable#cancel",
    "class/src/cancelled.js~CancelledCancellable.html#instance-method-cancel",
    "src/cancelled.js~CancelledCancellable#cancel",
    "method"
  ],
  [
    "src/cancelled.js~cancelledcancellable#cancelled",
    "class/src/cancelled.js~CancelledCancellable.html#instance-get-cancelled",
    "src/cancelled.js~CancelledCancellable#cancelled",
    "member"
  ],
  [
    "src/composite.js",
    "file/src/composite.js.html",
    "src/composite.js",
    "file"
  ],
  [
    "src/composite.js~compositecancellable#add",
    "class/src/composite.js~CompositeCancellable.html#instance-method-add",
    "src/composite.js~CompositeCancellable#add",
    "method"
  ],
  [
    "src/composite.js~compositecancellable#cancel",
    "class/src/composite.js~CompositeCancellable.html#instance-method-cancel",
    "src/composite.js~CompositeCancellable#cancel",
    "method"
  ],
  [
    "src/composite.js~compositecancellable#cancelled",
    "class/src/composite.js~CompositeCancellable.html#instance-get-cancelled",
    "src/composite.js~CompositeCancellable#cancelled",
    "member"
  ],
  [
    "src/composite.js~compositecancellable#constructor",
    "class/src/composite.js~CompositeCancellable.html#instance-constructor-constructor",
    "src/composite.js~CompositeCancellable#constructor",
    "method"
  ],
  [
    "src/composite.js~compositecancellable#remove",
    "class/src/composite.js~CompositeCancellable.html#instance-method-remove",
    "src/composite.js~CompositeCancellable#remove",
    "method"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/linked.js",
    "file/src/linked.js.html",
    "src/linked.js",
    "file"
  ],
  [
    "src/linked.js~linkedcancellable#cancel",
    "class/src/linked.js~LinkedCancellable.html#instance-method-cancel",
    "src/linked.js~LinkedCancellable#cancel",
    "method"
  ],
  [
    "src/linked.js~linkedcancellable#cancelled",
    "class/src/linked.js~LinkedCancellable.html#instance-get-cancelled",
    "src/linked.js~LinkedCancellable#cancelled",
    "member"
  ],
  [
    "src/linked.js~linkedcancellable#constructor",
    "class/src/linked.js~LinkedCancellable.html#instance-constructor-constructor",
    "src/linked.js~LinkedCancellable#constructor",
    "method"
  ],
  [
    "src/linked.js~linkedcancellable#link",
    "class/src/linked.js~LinkedCancellable.html#instance-method-link",
    "src/linked.js~LinkedCancellable#link",
    "method"
  ],
  [
    "src/linked.js~linkedcancellable#unlink",
    "class/src/linked.js~LinkedCancellable.html#instance-method-unlink",
    "src/linked.js~LinkedCancellable#unlink",
    "method"
  ],
  [
    "src/uncancelled.js",
    "file/src/uncancelled.js.html",
    "src/uncancelled.js",
    "file"
  ],
  [
    "src/uncancelled.js~uncancelledcancellable#cancel",
    "class/src/uncancelled.js~UncancelledCancellable.html#instance-method-cancel",
    "src/uncancelled.js~UncancelledCancellable#cancel",
    "method"
  ],
  [
    "src/uncancelled.js~uncancelledcancellable#cancelled",
    "class/src/uncancelled.js~UncancelledCancellable.html#instance-get-cancelled",
    "src/uncancelled.js~UncancelledCancellable#cancelled",
    "member"
  ],
  [
    "src/utils.js",
    "file/src/utils.js.html",
    "src/utils.js",
    "file"
  ],
  [
    "test/boolean.js",
    "test-file/test/boolean.js.html",
    "test/boolean.js",
    "testFile"
  ],
  [
    "test/composite.js",
    "test-file/test/composite.js.html",
    "test/composite.js",
    "testFile"
  ],
  [
    "test/index.js",
    "test-file/test/index.js.html",
    "test/index.js",
    "testFile"
  ],
  [
    "test/linked.js",
    "test-file/test/linked.js.html",
    "test/linked.js",
    "testFile"
  ]
]