window.esdocSearchIndex = [
  [
    "rx-cancellable/src/index.js~cancellable",
    "class/src/index.js~Cancellable.html",
    "<span>Cancellable</span> <span class=\"search-result-import-path\">rx-cancellable/src/index.js</span>",
    "class"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber6",
    "Cancellable",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber12",
    "Cancellable #active",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber17",
    "Cancellable #active should return false if Cancellable is disabled.",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber22",
    "Cancellable #active should return true if Cancellable is disabled then enabled.",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber34",
    "Cancellable #active should return true if Cancellable is disabled, cancelled, and enabled.",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber28",
    "Cancellable #active should return true if Cancellable is enabled, cancelled, and disabled.",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber13",
    "Cancellable #active should return true if Cancellable is enabled.",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber142",
    "Cancellable #addEventListener",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber156",
    "Cancellable #addEventListener should fire the cancel listener if the Cancellable is cancelled",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber150",
    "Cancellable #addEventListener should fire the disable listener if the Cancellable is disabled",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber143",
    "Cancellable #addEventListener should fire the enable listener if the Cancellable is enabled",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber162",
    "Cancellable #addEventListener should not fire the cancel listener if the Cancellable is already cancelled",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber53",
    "Cancellable #cancel",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber57",
    "Cancellable #cancel should return false if Cancellable has been cancelled before.",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber54",
    "Cancellable #cancel should return true if Cancellable is cancelled for the first time.",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber42",
    "Cancellable #cancelled",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber43",
    "Cancellable #cancelled should return true if Cancellable is cancelled.",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber48",
    "Cancellable #cancelled should return true if Cancellable is not cancelled.",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber7",
    "Cancellable #create",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber8",
    "Cancellable #create should create a Cancellable",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber74",
    "Cancellable #disable",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber79",
    "Cancellable #disable should return false if Cancellable is disabled already.",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber75",
    "Cancellable #disable should return true if Cancellable is disabled after being enabled.",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber63",
    "Cancellable #enable",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber69",
    "Cancellable #enable should return false if Cancellable is enabled already.",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber64",
    "Cancellable #enable should return true if Cancellable is enabled after being disabled.",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber121",
    "Cancellable #remove",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber122",
    "Cancellable #remove should return false if the Cancellable given is not the child.",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber127",
    "Cancellable #remove should return false if the source is already cancelled.",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber133",
    "Cancellable #remove should return true if the removal is successful",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber169",
    "Cancellable #removeEventListener",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber189",
    "Cancellable #removeEventListener should not fire the cancel listener if the Cancellable is cancelled",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber180",
    "Cancellable #removeEventListener should not fire the disable listener if the Cancellable is disabled",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber170",
    "Cancellable #removeEventListener should not fire the enable listener if the Cancellable is enabled",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber85",
    "Cancellable #setParent",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber93",
    "Cancellable #setParent should return false if the Cancellable parent given is a child of the source Cancellable",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber90",
    "Cancellable #setParent should return false if the Cancellable parent given is not a Cancellable",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber86",
    "Cancellable #setParent should return false if the Cancellable parent given is the same as the child",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber99",
    "Cancellable #setParent should return false if the Cancellable parent is already cancelled.",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber106",
    "Cancellable #setParent should the children be cancelled if the parent is cancelled",
    "test"
  ],
  [
    "",
    "test-file/test/index.js.html#lineNumber113",
    "Cancellable #setParent should the children be disabled if the parent is disabled",
    "test"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/index.js~cancellable#active",
    "class/src/index.js~Cancellable.html#instance-get-active",
    "src/index.js~Cancellable#active",
    "member"
  ],
  [
    "src/index.js~cancellable#add",
    "class/src/index.js~Cancellable.html#instance-method-add",
    "src/index.js~Cancellable#add",
    "method"
  ],
  [
    "src/index.js~cancellable#addeventlistener",
    "class/src/index.js~Cancellable.html#instance-method-addEventListener",
    "src/index.js~Cancellable#addEventListener",
    "method"
  ],
  [
    "src/index.js~cancellable#cancel",
    "class/src/index.js~Cancellable.html#instance-method-cancel",
    "src/index.js~Cancellable#cancel",
    "method"
  ],
  [
    "src/index.js~cancellable#cancelled",
    "class/src/index.js~Cancellable.html#instance-get-cancelled",
    "src/index.js~Cancellable#cancelled",
    "member"
  ],
  [
    "src/index.js~cancellable#disable",
    "class/src/index.js~Cancellable.html#instance-method-disable",
    "src/index.js~Cancellable#disable",
    "method"
  ],
  [
    "src/index.js~cancellable#enable",
    "class/src/index.js~Cancellable.html#instance-method-enable",
    "src/index.js~Cancellable#enable",
    "method"
  ],
  [
    "src/index.js~cancellable#isparentto",
    "class/src/index.js~Cancellable.html#instance-method-isParentTo",
    "src/index.js~Cancellable#isParentTo",
    "method"
  ],
  [
    "src/index.js~cancellable#remove",
    "class/src/index.js~Cancellable.html#instance-method-remove",
    "src/index.js~Cancellable#remove",
    "method"
  ],
  [
    "src/index.js~cancellable#removeeventlistener",
    "class/src/index.js~Cancellable.html#instance-method-removeEventListener",
    "src/index.js~Cancellable#removeEventListener",
    "method"
  ],
  [
    "src/index.js~cancellable#removeparent",
    "class/src/index.js~Cancellable.html#instance-method-removeParent",
    "src/index.js~Cancellable#removeParent",
    "method"
  ],
  [
    "src/index.js~cancellable#setparent",
    "class/src/index.js~Cancellable.html#instance-method-setParent",
    "src/index.js~Cancellable#setParent",
    "method"
  ],
  [
    "src/index.js~cancellable.create",
    "class/src/index.js~Cancellable.html#static-method-create",
    "src/index.js~Cancellable.create",
    "method"
  ],
  [
    "test/index.js",
    "test-file/test/index.js.html",
    "test/index.js",
    "testFile"
  ]
]