window.esdocSearchIndex = [
  [
    "",
    "test-file/test/amb.js.html#lineNumber8",
    "#amb",
    "test"
  ],
  [
    "",
    "test-file/test/amb.js.html#lineNumber12",
    "#amb should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/amb.js.html#lineNumber29",
    "#amb should signal error from the earliest source.",
    "test"
  ],
  [
    "",
    "test-file/test/amb.js.html#lineNumber49",
    "#amb should signal error if given argument is not Iterable",
    "test"
  ],
  [
    "",
    "test-file/test/amb.js.html#lineNumber39",
    "#amb should signal error if one of the source is non-Single.",
    "test"
  ],
  [
    "",
    "test-file/test/amb.js.html#lineNumber19",
    "#amb should signal success from the earliest source.",
    "test"
  ],
  [
    "",
    "test-file/test/ambArray.js.html#lineNumber8",
    "#ambArray",
    "test"
  ],
  [
    "",
    "test-file/test/ambArray.js.html#lineNumber12",
    "#ambArray should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/ambArray.js.html#lineNumber29",
    "#ambArray should signal error from the earliest source.",
    "test"
  ],
  [
    "",
    "test-file/test/ambArray.js.html#lineNumber49",
    "#ambArray should signal error if given argument is not Iterable",
    "test"
  ],
  [
    "",
    "test-file/test/ambArray.js.html#lineNumber39",
    "#ambArray should signal error if one of the source is non-Single.",
    "test"
  ],
  [
    "",
    "test-file/test/ambArray.js.html#lineNumber19",
    "#ambArray should signal success from the earliest source.",
    "test"
  ],
  [
    "",
    "test-file/test/ambWith.js.html#lineNumber8",
    "#ambWith",
    "test"
  ],
  [
    "",
    "test-file/test/ambWith.js.html#lineNumber12",
    "#ambWith should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/ambWith.js.html#lineNumber19",
    "#ambWith should return the same instance if the other value is non-Single",
    "test"
  ],
  [
    "",
    "test-file/test/ambWith.js.html#lineNumber57",
    "#ambWith should signal error from the other (if earlier).",
    "test"
  ],
  [
    "",
    "test-file/test/ambWith.js.html#lineNumber47",
    "#ambWith should signal error from the source (if earlier).",
    "test"
  ],
  [
    "",
    "test-file/test/ambWith.js.html#lineNumber37",
    "#ambWith should signal success from the other (if earlier).",
    "test"
  ],
  [
    "",
    "test-file/test/ambWith.js.html#lineNumber27",
    "#ambWith should signal success from the source (if earlier)",
    "test"
  ],
  [
    "",
    "test-file/test/cache.js.html#lineNumber8",
    "#cache",
    "test"
  ],
  [
    "",
    "test-file/test/cache.js.html#lineNumber12",
    "#cache should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/cache.js.html#lineNumber39",
    "#cache should signal cached error value",
    "test"
  ],
  [
    "",
    "test-file/test/cache.js.html#lineNumber19",
    "#cache should signal cached success value",
    "test"
  ],
  [
    "",
    "test-file/test/catch.js.html#lineNumber8",
    "#catch",
    "test"
  ],
  [
    "",
    "test-file/test/catch.js.html#lineNumber12",
    "#catch should create a Promise",
    "test"
  ],
  [
    "",
    "test-file/test/compose.js.html#lineNumber8",
    "#compose",
    "test"
  ],
  [
    "",
    "test-file/test/compose.js.html#lineNumber29",
    "#compose should correctly signal the composed Single",
    "test"
  ],
  [
    "",
    "test-file/test/compose.js.html#lineNumber21",
    "#compose should return a Single from the transformer",
    "test"
  ],
  [
    "",
    "test-file/test/compose.js.html#lineNumber12",
    "#compose should return the same instance if no function is provided",
    "test"
  ],
  [
    "",
    "test-file/test/compose.js.html#lineNumber40",
    "#compose should signal error if the transformer function returned a non-Single",
    "test"
  ],
  [
    "",
    "test-file/test/contains.js.html#lineNumber8",
    "#contains",
    "test"
  ],
  [
    "",
    "test-file/test/contains.js.html#lineNumber12",
    "#contains should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/contains.js.html#lineNumber19",
    "#contains should return the same instance if the compared value is undefined",
    "test"
  ],
  [
    "",
    "test-file/test/contains.js.html#lineNumber47",
    "#contains should signal an error if the comparer throws an error.",
    "test"
  ],
  [
    "",
    "test-file/test/contains.js.html#lineNumber37",
    "#contains should signal false if the success value and the compared value are both equal.",
    "test"
  ],
  [
    "",
    "test-file/test/contains.js.html#lineNumber27",
    "#contains should signal true if the success value and the compared value are both equal.",
    "test"
  ],
  [
    "",
    "test-file/test/create.js.html#lineNumber8",
    "#create",
    "test"
  ],
  [
    "",
    "test-file/test/create.js.html#lineNumber53",
    "#create should be cancel successfully if emitter is cancel before any signal.",
    "test"
  ],
  [
    "",
    "test-file/test/create.js.html#lineNumber12",
    "#create should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/create.js.html#lineNumber70",
    "#create should signal error if subscriber throws an error.",
    "test"
  ],
  [
    "",
    "test-file/test/create.js.html#lineNumber20",
    "#create should signal error if the create received a non-function",
    "test"
  ],
  [
    "",
    "test-file/test/create.js.html#lineNumber42",
    "#create should signal error if the emitter signals error with undefined value.",
    "test"
  ],
  [
    "",
    "test-file/test/create.js.html#lineNumber31",
    "#create should signal error if the emitter signals success with undefined value.",
    "test"
  ],
  [
    "",
    "test-file/test/defer.js.html#lineNumber8",
    "#defer",
    "test"
  ],
  [
    "",
    "test-file/test/defer.js.html#lineNumber12",
    "#defer should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/defer.js.html#lineNumber31",
    "#defer should signal error if callable returns a non-Single",
    "test"
  ],
  [
    "",
    "test-file/test/defer.js.html#lineNumber42",
    "#defer should signal error if callable throws an error",
    "test"
  ],
  [
    "",
    "test-file/test/defer.js.html#lineNumber20",
    "#defer should succeed with the given value.",
    "test"
  ],
  [
    "",
    "test-file/test/delay.js.html#lineNumber8",
    "#delay",
    "test"
  ],
  [
    "",
    "test-file/test/delay.js.html#lineNumber12",
    "#delay should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/delay.js.html#lineNumber62",
    "#delay should not signal error if cancelled.",
    "test"
  ],
  [
    "",
    "test-file/test/delay.js.html#lineNumber47",
    "#delay should not signal success if cancelled.",
    "test"
  ],
  [
    "",
    "test-file/test/delay.js.html#lineNumber19",
    "#delay should return the same instance if the amount is not a number.",
    "test"
  ],
  [
    "",
    "test-file/test/delay.js.html#lineNumber37",
    "#delay should signal error with the given value.",
    "test"
  ],
  [
    "",
    "test-file/test/delay.js.html#lineNumber27",
    "#delay should signal success with the given value.",
    "test"
  ],
  [
    "",
    "test-file/test/delaySubscription.js.html#lineNumber8",
    "#delaySubscription",
    "test"
  ],
  [
    "",
    "test-file/test/delaySubscription.js.html#lineNumber12",
    "#delaySubscription should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/delaySubscription.js.html#lineNumber62",
    "#delaySubscription should not signal error if cancelled.",
    "test"
  ],
  [
    "",
    "test-file/test/delaySubscription.js.html#lineNumber47",
    "#delaySubscription should not signal success if cancelled.",
    "test"
  ],
  [
    "",
    "test-file/test/delaySubscription.js.html#lineNumber19",
    "#delaySubscription should return the same instance if the amount is not a number.",
    "test"
  ],
  [
    "",
    "test-file/test/delaySubscription.js.html#lineNumber37",
    "#delaySubscription should signal error with the given value.",
    "test"
  ],
  [
    "",
    "test-file/test/delaySubscription.js.html#lineNumber27",
    "#delaySubscription should signal success with the given value.",
    "test"
  ],
  [
    "",
    "test-file/test/delayUntil.js.html#lineNumber8",
    "#delayUntil",
    "test"
  ],
  [
    "",
    "test-file/test/delayUntil.js.html#lineNumber12",
    "#delayUntil should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/delayUntil.js.html#lineNumber72",
    "#delayUntil should not signal error if cancelled.",
    "test"
  ],
  [
    "",
    "test-file/test/delayUntil.js.html#lineNumber57",
    "#delayUntil should not signal success if cancelled.",
    "test"
  ],
  [
    "",
    "test-file/test/delayUntil.js.html#lineNumber19",
    "#delayUntil should return the same instance if the provided value is not a Single.",
    "test"
  ],
  [
    "",
    "test-file/test/delayUntil.js.html#lineNumber47",
    "#delayUntil should signal error if other Single signals error.",
    "test"
  ],
  [
    "",
    "test-file/test/delayUntil.js.html#lineNumber37",
    "#delayUntil should signal error with the given value.",
    "test"
  ],
  [
    "",
    "test-file/test/delayUntil.js.html#lineNumber27",
    "#delayUntil should signal success with the given value.",
    "test"
  ],
  [
    "",
    "test-file/test/doAfterSuccess.js.html#lineNumber8",
    "#doAfterSuccess",
    "test"
  ],
  [
    "",
    "test-file/test/doAfterSuccess.js.html#lineNumber27",
    "#doAfterSuccess should call the given function after success.",
    "test"
  ],
  [
    "",
    "test-file/test/doAfterSuccess.js.html#lineNumber12",
    "#doAfterSuccess should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/doAfterSuccess.js.html#lineNumber19",
    "#doAfterSuccess should return the same instance if the method received a non-function parameter.",
    "test"
  ],
  [
    "",
    "test-file/test/doAfterTerminate.js.html#lineNumber8",
    "#doAfterTerminate",
    "test"
  ],
  [
    "",
    "test-file/test/doAfterTerminate.js.html#lineNumber39",
    "#doAfterTerminate should call the given function after error.",
    "test"
  ],
  [
    "",
    "test-file/test/doAfterTerminate.js.html#lineNumber27",
    "#doAfterTerminate should call the given function after success.",
    "test"
  ],
  [
    "",
    "test-file/test/doAfterTerminate.js.html#lineNumber12",
    "#doAfterTerminate should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/doAfterTerminate.js.html#lineNumber19",
    "#doAfterTerminate should return the same instance if the method received a non-function parameter.",
    "test"
  ],
  [
    "",
    "test-file/test/doFinally.js.html#lineNumber8",
    "#doFinally",
    "test"
  ],
  [
    "",
    "test-file/test/doFinally.js.html#lineNumber39",
    "#doFinally should call the given function after error.",
    "test"
  ],
  [
    "",
    "test-file/test/doFinally.js.html#lineNumber27",
    "#doFinally should call the given function after success.",
    "test"
  ],
  [
    "",
    "test-file/test/doFinally.js.html#lineNumber51",
    "#doFinally should call the given function on cancel.",
    "test"
  ],
  [
    "",
    "test-file/test/doFinally.js.html#lineNumber12",
    "#doFinally should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/doFinally.js.html#lineNumber19",
    "#doFinally should return the same instance if the method received a non-function parameter.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnError.js.html#lineNumber8",
    "#doOnError",
    "test"
  ],
  [
    "",
    "test-file/test/doOnError.js.html#lineNumber27",
    "#doOnError should call the given function on error.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnError.js.html#lineNumber12",
    "#doOnError should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/doOnError.js.html#lineNumber19",
    "#doOnError should return the same instance if the method received a non-function parameter.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnEvent.js.html#lineNumber8",
    "#doOnEvent",
    "test"
  ],
  [
    "",
    "test-file/test/doOnEvent.js.html#lineNumber39",
    "#doOnEvent should call the given function on error.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnEvent.js.html#lineNumber27",
    "#doOnEvent should call the given function on success.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnEvent.js.html#lineNumber12",
    "#doOnEvent should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/doOnEvent.js.html#lineNumber19",
    "#doOnEvent should return the same instance if the method received a non-function parameter.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnSubscribe.js.html#lineNumber8",
    "#doOnSubscribe",
    "test"
  ],
  [
    "",
    "test-file/test/doOnSubscribe.js.html#lineNumber27",
    "#doOnSubscribe should be called before actual subscription.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnSubscribe.js.html#lineNumber12",
    "#doOnSubscribe should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/doOnSubscribe.js.html#lineNumber19",
    "#doOnSubscribe should return the same instance if no function is passed",
    "test"
  ],
  [
    "",
    "test-file/test/doOnSuccess.js.html#lineNumber8",
    "#doOnSuccess",
    "test"
  ],
  [
    "",
    "test-file/test/doOnSuccess.js.html#lineNumber27",
    "#doOnSuccess should call the given function on success.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnSuccess.js.html#lineNumber12",
    "#doOnSuccess should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/doOnSuccess.js.html#lineNumber19",
    "#doOnSuccess should return the same instance if the method received a non-function parameter.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnTerminate.js.html#lineNumber8",
    "#doOnTerminate",
    "test"
  ],
  [
    "",
    "test-file/test/doOnTerminate.js.html#lineNumber39",
    "#doOnTerminate should call the given function on error.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnTerminate.js.html#lineNumber27",
    "#doOnTerminate should call the given function on success.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnTerminate.js.html#lineNumber12",
    "#doOnTerminate should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/doOnTerminate.js.html#lineNumber19",
    "#doOnTerminate should return the same instance if the method received a non-function parameter.",
    "test"
  ],
  [
    "",
    "test-file/test/error.js.html#lineNumber8",
    "#error",
    "test"
  ],
  [
    "",
    "test-file/test/error.js.html#lineNumber12",
    "#error should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/error.js.html#lineNumber53",
    "#error should error if the callable throws an error.",
    "test"
  ],
  [
    "",
    "test-file/test/error.js.html#lineNumber42",
    "#error should error with the a message if the callable returned undefined",
    "test"
  ],
  [
    "",
    "test-file/test/error.js.html#lineNumber31",
    "#error should error with the a message if the given value is undefined",
    "test"
  ],
  [
    "",
    "test-file/test/error.js.html#lineNumber20",
    "#error should error with the given value.",
    "test"
  ],
  [
    "",
    "test-file/test/flatMap.js.html#lineNumber8",
    "#flatMap",
    "test"
  ],
  [
    "",
    "test-file/test/flatMap.js.html#lineNumber12",
    "#flatMap should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/flatMap.js.html#lineNumber20",
    "#flatMap should return the same instance if the method received a non-function parameter.",
    "test"
  ],
  [
    "",
    "test-file/test/flatMap.js.html#lineNumber28",
    "#flatMap should signal error if mapper returns a non-Single",
    "test"
  ],
  [
    "",
    "test-file/test/flatMap.js.html#lineNumber39",
    "#flatMap should signal success of the returned Single",
    "test"
  ],
  [
    "",
    "test-file/test/fromCallable.js.html#lineNumber8",
    "#fromCallable",
    "test"
  ],
  [
    "",
    "test-file/test/fromCallable.js.html#lineNumber12",
    "#fromCallable should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/fromCallable.js.html#lineNumber54",
    "#fromCallable should signal an error if the callable is not a function",
    "test"
  ],
  [
    "",
    "test-file/test/fromCallable.js.html#lineNumber43",
    "#fromCallable should signal an error if the callable returns a rejected Promise.",
    "test"
  ],
  [
    "",
    "test-file/test/fromCallable.js.html#lineNumber30",
    "#fromCallable should signal an error if the callable throws an error.",
    "test"
  ],
  [
    "",
    "test-file/test/fromCallable.js.html#lineNumber19",
    "#fromCallable should succeed with the given value.",
    "test"
  ],
  [
    "",
    "test-file/test/fromPromise.js.html#lineNumber8",
    "#fromPromise",
    "test"
  ],
  [
    "",
    "test-file/test/fromPromise.js.html#lineNumber12",
    "#fromPromise should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/fromPromise.js.html#lineNumber31",
    "#fromPromise should signal error if the given value is not Promise like",
    "test"
  ],
  [
    "",
    "test-file/test/fromPromise.js.html#lineNumber19",
    "#fromPromise should succeed with the given value.",
    "test"
  ],
  [
    "",
    "test-file/test/fromResolvable.js.html#lineNumber8",
    "#fromResolvable",
    "test"
  ],
  [
    "",
    "test-file/test/fromResolvable.js.html#lineNumber12",
    "#fromResolvable should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/fromResolvable.js.html#lineNumber30",
    "#fromResolvable should error with the given error.",
    "test"
  ],
  [
    "",
    "test-file/test/fromResolvable.js.html#lineNumber41",
    "#fromResolvable should signal error if the given value is not a function",
    "test"
  ],
  [
    "",
    "test-file/test/fromResolvable.js.html#lineNumber19",
    "#fromResolvable should succeed with the given value.",
    "test"
  ],
  [
    "",
    "test-file/test/just.js.html#lineNumber8",
    "#just",
    "test"
  ],
  [
    "",
    "test-file/test/just.js.html#lineNumber12",
    "#just should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/just.js.html#lineNumber31",
    "#just should emit error if value is undefined.",
    "test"
  ],
  [
    "",
    "test-file/test/just.js.html#lineNumber20",
    "#just should succeed with the given value.",
    "test"
  ],
  [
    "",
    "test-file/test/lift.js.html#lineNumber8",
    "#lift",
    "test"
  ],
  [
    "",
    "test-file/test/lift.js.html#lineNumber12",
    "#lift should return the same instance if no function is provided",
    "test"
  ],
  [
    "",
    "test-file/test/lift.js.html#lineNumber21",
    "#lift should signal an error if the lift operator returned a non-Observer",
    "test"
  ],
  [
    "",
    "test-file/test/lift.js.html#lineNumber32",
    "#lift should subscribe successfully",
    "test"
  ],
  [
    "",
    "test-file/test/map.js.html#lineNumber8",
    "#map",
    "test"
  ],
  [
    "",
    "test-file/test/map.js.html#lineNumber12",
    "#map should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/map.js.html#lineNumber54",
    "#map should retain the value if no function is supplied.",
    "test"
  ],
  [
    "",
    "test-file/test/map.js.html#lineNumber30",
    "#map should signal an error if the mapper throws an error",
    "test"
  ],
  [
    "",
    "test-file/test/map.js.html#lineNumber43",
    "#map should signal an error if the mapper throws an error",
    "test"
  ],
  [
    "",
    "test-file/test/map.js.html#lineNumber19",
    "#map should succeed with the given value.",
    "test"
  ],
  [
    "",
    "test-file/test/merge.js.html#lineNumber8",
    "#merge",
    "test"
  ],
  [
    "",
    "test-file/test/merge.js.html#lineNumber12",
    "#merge should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/merge.js.html#lineNumber20",
    "#merge should signal error if no source is provided",
    "test"
  ],
  [
    "",
    "test-file/test/merge.js.html#lineNumber31",
    "#merge should signal error if source emitted a non-Single",
    "test"
  ],
  [
    "",
    "test-file/test/merge.js.html#lineNumber42",
    "#merge should signal success of the signaled Single",
    "test"
  ],
  [
    "",
    "test-file/test/never.js.html#lineNumber8",
    "#never",
    "test"
  ],
  [
    "",
    "test-file/test/never.js.html#lineNumber12",
    "#never should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/never.js.html#lineNumber19",
    "#never should not signal.",
    "test"
  ],
  [
    "",
    "test-file/test/observeOn.js.html#lineNumber6",
    "#observeOn",
    "test"
  ],
  [
    "",
    "test-file/test/observeOn.js.html#lineNumber64",
    "#observeOn should be asynchronous with Scheduler.async",
    "test"
  ],
  [
    "",
    "test-file/test/observeOn.js.html#lineNumber86",
    "#observeOn should be asynchronous with Scheduler.immediate",
    "test"
  ],
  [
    "",
    "test-file/test/observeOn.js.html#lineNumber42",
    "#observeOn should be asynchronous with Scheduler.tick",
    "test"
  ],
  [
    "",
    "test-file/test/observeOn.js.html#lineNumber108",
    "#observeOn should be asynchronous with Scheduler.timeout",
    "test"
  ],
  [
    "",
    "test-file/test/observeOn.js.html#lineNumber26",
    "#observeOn should be synchronous with Scheduler.current",
    "test"
  ],
  [
    "",
    "test-file/test/observeOn.js.html#lineNumber10",
    "#observeOn should be synchronous with non-Scheduler",
    "test"
  ],
  [
    "",
    "test-file/test/observeOn.js.html#lineNumber7",
    "#observeOn should return a Single",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorResumeNext.js.html#lineNumber8",
    "#onErrorResumeNext",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorResumeNext.js.html#lineNumber12",
    "#onErrorResumeNext should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorResumeNext.js.html#lineNumber57",
    "#onErrorResumeNext should emit error if provide function returns non-Single.",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorResumeNext.js.html#lineNumber47",
    "#onErrorResumeNext should emit error if provide function throws error.",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorResumeNext.js.html#lineNumber19",
    "#onErrorResumeNext should return the same instance if parameter passed is not a Single or a function",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorResumeNext.js.html#lineNumber27",
    "#onErrorResumeNext should subscribe to the given Single",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorResumeNext.js.html#lineNumber37",
    "#onErrorResumeNext should subscribe to the given Single-producing Function",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorReturn.js.html#lineNumber8",
    "#onErrorReturn",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorReturn.js.html#lineNumber12",
    "#onErrorReturn should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorReturn.js.html#lineNumber48",
    "#onErrorReturn should emit error if provide function returns undefined.",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorReturn.js.html#lineNumber38",
    "#onErrorReturn should emit error if provide function throws error.",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorReturn.js.html#lineNumber27",
    "#onErrorReturn should emit the supplied item by the given function in case of error",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorReturn.js.html#lineNumber19",
    "#onErrorReturn should return the same instance if parameter passed is not a Single or a function",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorReturnItem.js.html#lineNumber8",
    "#onErrorReturnItem",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorReturnItem.js.html#lineNumber12",
    "#onErrorReturnItem should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorReturnItem.js.html#lineNumber27",
    "#onErrorReturnItem should emit the given item in case of error",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorReturnItem.js.html#lineNumber19",
    "#onErrorReturnItem should return the same instance if parameter passed is not a Single or a function",
    "test"
  ],
  [
    "",
    "test-file/test/retry.js.html#lineNumber8",
    "#retry",
    "test"
  ],
  [
    "",
    "test-file/test/retry.js.html#lineNumber12",
    "#retry should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/retry.js.html#lineNumber31",
    "#retry should retry if there is an error and if it passes the predicate",
    "test"
  ],
  [
    "",
    "test-file/test/retry.js.html#lineNumber20",
    "#retry should signal a success if no error",
    "test"
  ],
  [
    "",
    "test-file/test/retry.js.html#lineNumber48",
    "#retry should signal an error if predicate is false",
    "test"
  ],
  [
    "",
    "test-file/test/subscribeOn.js.html#lineNumber6",
    "#subscribeOn",
    "test"
  ],
  [
    "",
    "test-file/test/subscribeOn.js.html#lineNumber64",
    "#subscribeOn should be asynchronous with Scheduler.async",
    "test"
  ],
  [
    "",
    "test-file/test/subscribeOn.js.html#lineNumber86",
    "#subscribeOn should be asynchronous with Scheduler.immediate",
    "test"
  ],
  [
    "",
    "test-file/test/subscribeOn.js.html#lineNumber42",
    "#subscribeOn should be asynchronous with Scheduler.tick",
    "test"
  ],
  [
    "",
    "test-file/test/subscribeOn.js.html#lineNumber108",
    "#subscribeOn should be asynchronous with Scheduler.timeout",
    "test"
  ],
  [
    "",
    "test-file/test/subscribeOn.js.html#lineNumber26",
    "#subscribeOn should be synchronous with Scheduler.current",
    "test"
  ],
  [
    "",
    "test-file/test/subscribeOn.js.html#lineNumber10",
    "#subscribeOn should be synchronous with non-Scheduler",
    "test"
  ],
  [
    "",
    "test-file/test/subscribeOn.js.html#lineNumber7",
    "#subscribeOn should return a Single",
    "test"
  ],
  [
    "",
    "test-file/test/takeUntil.js.html#lineNumber8",
    "#takeUntil",
    "test"
  ],
  [
    "",
    "test-file/test/takeUntil.js.html#lineNumber12",
    "#takeUntil should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/takeUntil.js.html#lineNumber20",
    "#takeUntil should return the same instance if no other Single is provided",
    "test"
  ],
  [
    "",
    "test-file/test/takeUntil.js.html#lineNumber51",
    "#takeUntil should signal error if other Single has emitted a success signal",
    "test"
  ],
  [
    "",
    "test-file/test/takeUntil.js.html#lineNumber62",
    "#takeUntil should signal error if other Single has emitted an error signal",
    "test"
  ],
  [
    "",
    "test-file/test/takeUntil.js.html#lineNumber73",
    "#takeUntil should signal error if source signals error, nonetheless",
    "test"
  ],
  [
    "",
    "test-file/test/takeUntil.js.html#lineNumber29",
    "#takeUntil should signal success if other Single has not emitted a success signal",
    "test"
  ],
  [
    "",
    "test-file/test/takeUntil.js.html#lineNumber40",
    "#takeUntil should signal success if other Single has not emitted an error signal",
    "test"
  ],
  [
    "",
    "test-file/test/then.js.html#lineNumber8",
    "#then",
    "test"
  ],
  [
    "",
    "test-file/test/then.js.html#lineNumber12",
    "#then should create a Promise",
    "test"
  ],
  [
    "",
    "test-file/test/timeout.js.html#lineNumber8",
    "#timeout",
    "test"
  ],
  [
    "",
    "test-file/test/timeout.js.html#lineNumber12",
    "#timeout should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/timeout.js.html#lineNumber72",
    "#timeout should not signal error if cancelled.",
    "test"
  ],
  [
    "",
    "test-file/test/timeout.js.html#lineNumber57",
    "#timeout should not signal success if cancelled.",
    "test"
  ],
  [
    "",
    "test-file/test/timeout.js.html#lineNumber19",
    "#timeout should return the same instance if the amount is not a number.",
    "test"
  ],
  [
    "",
    "test-file/test/timeout.js.html#lineNumber47",
    "#timeout should signal error if the Single does not emit item within the given timeout.",
    "test"
  ],
  [
    "",
    "test-file/test/timeout.js.html#lineNumber37",
    "#timeout should signal error with the given value.",
    "test"
  ],
  [
    "",
    "test-file/test/timeout.js.html#lineNumber27",
    "#timeout should signal success with the given value.",
    "test"
  ],
  [
    "",
    "test-file/test/timer.js.html#lineNumber8",
    "#timer",
    "test"
  ],
  [
    "",
    "test-file/test/timer.js.html#lineNumber12",
    "#timer should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/timer.js.html#lineNumber40",
    "#timer should not signal success if cancelled.",
    "test"
  ],
  [
    "",
    "test-file/test/timer.js.html#lineNumber19",
    "#timer should signal error if amount is not a number.",
    "test"
  ],
  [
    "",
    "test-file/test/timer.js.html#lineNumber30",
    "#timer should signal success 0",
    "test"
  ],
  [
    "",
    "test-file/test/toPromise.js.html#lineNumber8",
    "#toPromise",
    "test"
  ],
  [
    "",
    "test-file/test/toPromise.js.html#lineNumber12",
    "#toPromise should create a Promise",
    "test"
  ],
  [
    "",
    "test-file/test/zip.js.html#lineNumber8",
    "#zip",
    "test"
  ],
  [
    "",
    "test-file/test/zip.js.html#lineNumber12",
    "#zip should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/zip.js.html#lineNumber90",
    "#zip should not signal success if cancelled.",
    "test"
  ],
  [
    "",
    "test-file/test/zip.js.html#lineNumber39",
    "#zip should signal an error if the zipper throws an error",
    "test"
  ],
  [
    "",
    "test-file/test/zip.js.html#lineNumber80",
    "#zip should signal error if a source throws error.",
    "test"
  ],
  [
    "",
    "test-file/test/zip.js.html#lineNumber70",
    "#zip should signal error if one of the sources is a non-Single.",
    "test"
  ],
  [
    "",
    "test-file/test/zip.js.html#lineNumber29",
    "#zip should signal error if source is empty iterable.",
    "test"
  ],
  [
    "",
    "test-file/test/zip.js.html#lineNumber19",
    "#zip should signal error if sources is not iterable.",
    "test"
  ],
  [
    "",
    "test-file/test/zip.js.html#lineNumber50",
    "#zip should signal success with an array (no zipper function).",
    "test"
  ],
  [
    "",
    "test-file/test/zip.js.html#lineNumber60",
    "#zip should signal success with an array with the correct values (no zipper function).",
    "test"
  ],
  [
    "",
    "test-file/test/zipArray.js.html#lineNumber8",
    "#zipArray",
    "test"
  ],
  [
    "",
    "test-file/test/zipArray.js.html#lineNumber12",
    "#zipArray should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/zipArray.js.html#lineNumber90",
    "#zipArray should not signal success if cancelled.",
    "test"
  ],
  [
    "",
    "test-file/test/zipArray.js.html#lineNumber39",
    "#zipArray should signal an error if the zipper throws an error",
    "test"
  ],
  [
    "",
    "test-file/test/zipArray.js.html#lineNumber80",
    "#zipArray should signal error if a source throws error.",
    "test"
  ],
  [
    "",
    "test-file/test/zipArray.js.html#lineNumber70",
    "#zipArray should signal error if one of the sources is a non-Single.",
    "test"
  ],
  [
    "",
    "test-file/test/zipArray.js.html#lineNumber29",
    "#zipArray should signal error if source is empty iterable.",
    "test"
  ],
  [
    "",
    "test-file/test/zipArray.js.html#lineNumber19",
    "#zipArray should signal error if sources is not iterable.",
    "test"
  ],
  [
    "",
    "test-file/test/zipArray.js.html#lineNumber50",
    "#zipArray should signal success with an array (no zipper function).",
    "test"
  ],
  [
    "",
    "test-file/test/zipArray.js.html#lineNumber60",
    "#zipArray should signal success with an array with the correct values (no zipper function).",
    "test"
  ],
  [
    "",
    "test-file/test/zipWith.js.html#lineNumber8",
    "#zipWith",
    "test"
  ],
  [
    "",
    "test-file/test/zipWith.js.html#lineNumber12",
    "#zipWith should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/zipWith.js.html#lineNumber89",
    "#zipWith should not signal success if cancelled.",
    "test"
  ],
  [
    "",
    "test-file/test/zipWith.js.html#lineNumber19",
    "#zipWith should return the same instance if the other parameter is non-Single",
    "test"
  ],
  [
    "",
    "test-file/test/zipWith.js.html#lineNumber27",
    "#zipWith should signal an error if the zipper returns undefined",
    "test"
  ],
  [
    "",
    "test-file/test/zipWith.js.html#lineNumber38",
    "#zipWith should signal an error if the zipper returns undefined",
    "test"
  ],
  [
    "",
    "test-file/test/zipWith.js.html#lineNumber79",
    "#zipWith should signal error if other Single throws error.",
    "test"
  ],
  [
    "",
    "test-file/test/zipWith.js.html#lineNumber69",
    "#zipWith should signal error if source throws error.",
    "test"
  ],
  [
    "",
    "test-file/test/zipWith.js.html#lineNumber49",
    "#zipWith should signal success with an array (no zipper function).",
    "test"
  ],
  [
    "",
    "test-file/test/zipWith.js.html#lineNumber59",
    "#zipWith should signal success with an array with the correct values (no zipper function).",
    "test"
  ],
  [
    "rx-single/src/single.js~single",
    "class/src/single.js~Single.html",
    "<span>Single</span> <span class=\"search-result-import-path\">rx-single/src/single.js</span>",
    "class"
  ],
  [
    "rx-single/src/emitter.js~singleemitter",
    "class/src/emitter.js~SingleEmitter.html",
    "<span>SingleEmitter</span> <span class=\"search-result-import-path\">rx-single/src/emitter.js</span>",
    "class"
  ],
  [
    "rx-single/src/observer.js~singleobserver",
    "class/src/observer.js~SingleObserver.html",
    "<span>SingleObserver</span> <span class=\"search-result-import-path\">rx-single/src/observer.js</span>",
    "class"
  ],
  [
    "",
    "test-file/test/doOnCancel.js.html#lineNumber8",
    "Single",
    "test"
  ],
  [
    "",
    "test-file/test/doOnCancel.js.html#lineNumber12",
    "Single #doOnCancel",
    "test"
  ],
  [
    "",
    "test-file/test/doOnCancel.js.html#lineNumber59",
    "Single #doOnCancel should call the given function on cancel.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnCancel.js.html#lineNumber16",
    "Single #doOnCancel should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/doOnCancel.js.html#lineNumber23",
    "Single #doOnCancel should return the same instance if the method received a non-function parameter.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnCancel.js.html#lineNumber45",
    "Single #doOnCancel should signal the error value then fire cancel callback.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnCancel.js.html#lineNumber31",
    "Single #doOnCancel should signal the success value then fire cancel callback.",
    "test"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/emitter.js",
    "file/src/emitter.js.html",
    "src/emitter.js",
    "file"
  ],
  [
    "src/emitter.js~singleemitter#cancel",
    "class/src/emitter.js~SingleEmitter.html#instance-method-cancel",
    "src/emitter.js~SingleEmitter#cancel",
    "method"
  ],
  [
    "src/emitter.js~singleemitter#cancelled",
    "class/src/emitter.js~SingleEmitter.html#instance-get-cancelled",
    "src/emitter.js~SingleEmitter#cancelled",
    "member"
  ],
  [
    "src/emitter.js~singleemitter#constructor",
    "class/src/emitter.js~SingleEmitter.html#instance-constructor-constructor",
    "src/emitter.js~SingleEmitter#constructor",
    "method"
  ],
  [
    "src/emitter.js~singleemitter#onerror",
    "class/src/emitter.js~SingleEmitter.html#instance-method-onError",
    "src/emitter.js~SingleEmitter#onError",
    "method"
  ],
  [
    "src/emitter.js~singleemitter#onsuccess",
    "class/src/emitter.js~SingleEmitter.html#instance-method-onSuccess",
    "src/emitter.js~SingleEmitter#onSuccess",
    "method"
  ],
  [
    "src/emitter.js~singleemitter#setcancellable",
    "class/src/emitter.js~SingleEmitter.html#instance-method-setCancellable",
    "src/emitter.js~SingleEmitter#setCancellable",
    "method"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/internal/is.js",
    "file/src/internal/is.js.html",
    "src/internal/is.js",
    "file"
  ],
  [
    "src/internal/operators.js",
    "file/src/internal/operators.js.html",
    "src/internal/operators.js",
    "file"
  ],
  [
    "src/internal/operators/amb.js",
    "file/src/internal/operators/amb.js.html",
    "src/internal/operators/amb.js",
    "file"
  ],
  [
    "src/internal/operators/ambarray.js",
    "file/src/internal/operators/ambArray.js.html",
    "src/internal/operators/ambArray.js",
    "file"
  ],
  [
    "src/internal/operators/ambwith.js",
    "file/src/internal/operators/ambWith.js.html",
    "src/internal/operators/ambWith.js",
    "file"
  ],
  [
    "src/internal/operators/cache.js",
    "file/src/internal/operators/cache.js.html",
    "src/internal/operators/cache.js",
    "file"
  ],
  [
    "src/internal/operators/compose.js",
    "file/src/internal/operators/compose.js.html",
    "src/internal/operators/compose.js",
    "file"
  ],
  [
    "src/internal/operators/contains.js",
    "file/src/internal/operators/contains.js.html",
    "src/internal/operators/contains.js",
    "file"
  ],
  [
    "src/internal/operators/create.js",
    "file/src/internal/operators/create.js.html",
    "src/internal/operators/create.js",
    "file"
  ],
  [
    "src/internal/operators/defer.js",
    "file/src/internal/operators/defer.js.html",
    "src/internal/operators/defer.js",
    "file"
  ],
  [
    "src/internal/operators/delay.js",
    "file/src/internal/operators/delay.js.html",
    "src/internal/operators/delay.js",
    "file"
  ],
  [
    "src/internal/operators/delaysubscription.js",
    "file/src/internal/operators/delaySubscription.js.html",
    "src/internal/operators/delaySubscription.js",
    "file"
  ],
  [
    "src/internal/operators/delayuntil.js",
    "file/src/internal/operators/delayUntil.js.html",
    "src/internal/operators/delayUntil.js",
    "file"
  ],
  [
    "src/internal/operators/doaftersuccess.js",
    "file/src/internal/operators/doAfterSuccess.js.html",
    "src/internal/operators/doAfterSuccess.js",
    "file"
  ],
  [
    "src/internal/operators/doafterterminate.js",
    "file/src/internal/operators/doAfterTerminate.js.html",
    "src/internal/operators/doAfterTerminate.js",
    "file"
  ],
  [
    "src/internal/operators/dofinally.js",
    "file/src/internal/operators/doFinally.js.html",
    "src/internal/operators/doFinally.js",
    "file"
  ],
  [
    "src/internal/operators/dooncancel.js",
    "file/src/internal/operators/doOnCancel.js.html",
    "src/internal/operators/doOnCancel.js",
    "file"
  ],
  [
    "src/internal/operators/doonerror.js",
    "file/src/internal/operators/doOnError.js.html",
    "src/internal/operators/doOnError.js",
    "file"
  ],
  [
    "src/internal/operators/doonevent.js",
    "file/src/internal/operators/doOnEvent.js.html",
    "src/internal/operators/doOnEvent.js",
    "file"
  ],
  [
    "src/internal/operators/doonsubscribe.js",
    "file/src/internal/operators/doOnSubscribe.js.html",
    "src/internal/operators/doOnSubscribe.js",
    "file"
  ],
  [
    "src/internal/operators/doonsuccess.js",
    "file/src/internal/operators/doOnSuccess.js.html",
    "src/internal/operators/doOnSuccess.js",
    "file"
  ],
  [
    "src/internal/operators/doonterminate.js",
    "file/src/internal/operators/doOnTerminate.js.html",
    "src/internal/operators/doOnTerminate.js",
    "file"
  ],
  [
    "src/internal/operators/error.js",
    "file/src/internal/operators/error.js.html",
    "src/internal/operators/error.js",
    "file"
  ],
  [
    "src/internal/operators/flatmap.js",
    "file/src/internal/operators/flatMap.js.html",
    "src/internal/operators/flatMap.js",
    "file"
  ],
  [
    "src/internal/operators/fromcallable.js",
    "file/src/internal/operators/fromCallable.js.html",
    "src/internal/operators/fromCallable.js",
    "file"
  ],
  [
    "src/internal/operators/frompromise.js",
    "file/src/internal/operators/fromPromise.js.html",
    "src/internal/operators/fromPromise.js",
    "file"
  ],
  [
    "src/internal/operators/fromresolvable.js",
    "file/src/internal/operators/fromResolvable.js.html",
    "src/internal/operators/fromResolvable.js",
    "file"
  ],
  [
    "src/internal/operators/just.js",
    "file/src/internal/operators/just.js.html",
    "src/internal/operators/just.js",
    "file"
  ],
  [
    "src/internal/operators/lift.js",
    "file/src/internal/operators/lift.js.html",
    "src/internal/operators/lift.js",
    "file"
  ],
  [
    "src/internal/operators/map.js",
    "file/src/internal/operators/map.js.html",
    "src/internal/operators/map.js",
    "file"
  ],
  [
    "src/internal/operators/merge.js",
    "file/src/internal/operators/merge.js.html",
    "src/internal/operators/merge.js",
    "file"
  ],
  [
    "src/internal/operators/never.js",
    "file/src/internal/operators/never.js.html",
    "src/internal/operators/never.js",
    "file"
  ],
  [
    "src/internal/operators/observeon.js",
    "file/src/internal/operators/observeOn.js.html",
    "src/internal/operators/observeOn.js",
    "file"
  ],
  [
    "src/internal/operators/onerrorresumenext.js",
    "file/src/internal/operators/onErrorResumeNext.js.html",
    "src/internal/operators/onErrorResumeNext.js",
    "file"
  ],
  [
    "src/internal/operators/onerrorreturn.js",
    "file/src/internal/operators/onErrorReturn.js.html",
    "src/internal/operators/onErrorReturn.js",
    "file"
  ],
  [
    "src/internal/operators/onerrorreturnitem.js",
    "file/src/internal/operators/onErrorReturnItem.js.html",
    "src/internal/operators/onErrorReturnItem.js",
    "file"
  ],
  [
    "src/internal/operators/retry.js",
    "file/src/internal/operators/retry.js.html",
    "src/internal/operators/retry.js",
    "file"
  ],
  [
    "src/internal/operators/subscribeon.js",
    "file/src/internal/operators/subscribeOn.js.html",
    "src/internal/operators/subscribeOn.js",
    "file"
  ],
  [
    "src/internal/operators/takeuntil.js",
    "file/src/internal/operators/takeUntil.js.html",
    "src/internal/operators/takeUntil.js",
    "file"
  ],
  [
    "src/internal/operators/timeout.js",
    "file/src/internal/operators/timeout.js.html",
    "src/internal/operators/timeout.js",
    "file"
  ],
  [
    "src/internal/operators/timer.js",
    "file/src/internal/operators/timer.js.html",
    "src/internal/operators/timer.js",
    "file"
  ],
  [
    "src/internal/operators/zip.js",
    "file/src/internal/operators/zip.js.html",
    "src/internal/operators/zip.js",
    "file"
  ],
  [
    "src/internal/operators/ziparray.js",
    "file/src/internal/operators/zipArray.js.html",
    "src/internal/operators/zipArray.js",
    "file"
  ],
  [
    "src/internal/operators/zipwith.js",
    "file/src/internal/operators/zipWith.js.html",
    "src/internal/operators/zipWith.js",
    "file"
  ],
  [
    "src/internal/utils.js",
    "file/src/internal/utils.js.html",
    "src/internal/utils.js",
    "file"
  ],
  [
    "src/observer.js",
    "file/src/observer.js.html",
    "src/observer.js",
    "file"
  ],
  [
    "src/observer.js~singleobserver#onerror",
    "class/src/observer.js~SingleObserver.html#instance-method-onError",
    "src/observer.js~SingleObserver#onError",
    "method"
  ],
  [
    "src/observer.js~singleobserver#onsubscribe",
    "class/src/observer.js~SingleObserver.html#instance-method-onSubscribe",
    "src/observer.js~SingleObserver#onSubscribe",
    "method"
  ],
  [
    "src/observer.js~singleobserver#onsuccess",
    "class/src/observer.js~SingleObserver.html#instance-method-onSuccess",
    "src/observer.js~SingleObserver#onSuccess",
    "method"
  ],
  [
    "src/single.js",
    "file/src/single.js.html",
    "src/single.js",
    "file"
  ],
  [
    "src/single.js~cancellable",
    "https://lxsmnsyc.github.io/rx-cancellable/",
    "src/single.js~Cancellable",
    "external"
  ],
  [
    "src/single.js~iterable",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols",
    "src/single.js~Iterable",
    "external"
  ],
  [
    "src/single.js~promiselike",
    "https://promisesaplus.com/",
    "src/single.js~PromiseLike",
    "external"
  ],
  [
    "src/single.js~scheduler",
    "https://lxsmnsyc.github.io/rx-scheduler/",
    "src/single.js~Scheduler",
    "external"
  ],
  [
    "src/single.js~single#ambwith",
    "class/src/single.js~Single.html#instance-method-ambWith",
    "src/single.js~Single#ambWith",
    "method"
  ],
  [
    "src/single.js~single#cache",
    "class/src/single.js~Single.html#instance-method-cache",
    "src/single.js~Single#cache",
    "method"
  ],
  [
    "src/single.js~single#catch",
    "class/src/single.js~Single.html#instance-method-catch",
    "src/single.js~Single#catch",
    "method"
  ],
  [
    "src/single.js~single#compose",
    "class/src/single.js~Single.html#instance-method-compose",
    "src/single.js~Single#compose",
    "method"
  ],
  [
    "src/single.js~single#contains",
    "class/src/single.js~Single.html#instance-method-contains",
    "src/single.js~Single#contains",
    "method"
  ],
  [
    "src/single.js~single#delay",
    "class/src/single.js~Single.html#instance-method-delay",
    "src/single.js~Single#delay",
    "method"
  ],
  [
    "src/single.js~single#delaysubscription",
    "class/src/single.js~Single.html#instance-method-delaySubscription",
    "src/single.js~Single#delaySubscription",
    "method"
  ],
  [
    "src/single.js~single#delayuntil",
    "class/src/single.js~Single.html#instance-method-delayUntil",
    "src/single.js~Single#delayUntil",
    "method"
  ],
  [
    "src/single.js~single#doaftersuccess",
    "class/src/single.js~Single.html#instance-method-doAfterSuccess",
    "src/single.js~Single#doAfterSuccess",
    "method"
  ],
  [
    "src/single.js~single#doafterterminate",
    "class/src/single.js~Single.html#instance-method-doAfterTerminate",
    "src/single.js~Single#doAfterTerminate",
    "method"
  ],
  [
    "src/single.js~single#dofinally",
    "class/src/single.js~Single.html#instance-method-doFinally",
    "src/single.js~Single#doFinally",
    "method"
  ],
  [
    "src/single.js~single#dooncancel",
    "class/src/single.js~Single.html#instance-method-doOnCancel",
    "src/single.js~Single#doOnCancel",
    "method"
  ],
  [
    "src/single.js~single#doonerror",
    "class/src/single.js~Single.html#instance-method-doOnError",
    "src/single.js~Single#doOnError",
    "method"
  ],
  [
    "src/single.js~single#doonevent",
    "class/src/single.js~Single.html#instance-method-doOnEvent",
    "src/single.js~Single#doOnEvent",
    "method"
  ],
  [
    "src/single.js~single#doonsubscribe",
    "class/src/single.js~Single.html#instance-method-doOnSubscribe",
    "src/single.js~Single#doOnSubscribe",
    "method"
  ],
  [
    "src/single.js~single#doonsuccess",
    "class/src/single.js~Single.html#instance-method-doOnSuccess",
    "src/single.js~Single#doOnSuccess",
    "method"
  ],
  [
    "src/single.js~single#doonterminate",
    "class/src/single.js~Single.html#instance-method-doOnTerminate",
    "src/single.js~Single#doOnTerminate",
    "method"
  ],
  [
    "src/single.js~single#flatmap",
    "class/src/single.js~Single.html#instance-method-flatMap",
    "src/single.js~Single#flatMap",
    "method"
  ],
  [
    "src/single.js~single#lift",
    "class/src/single.js~Single.html#instance-method-lift",
    "src/single.js~Single#lift",
    "method"
  ],
  [
    "src/single.js~single#map",
    "class/src/single.js~Single.html#instance-method-map",
    "src/single.js~Single#map",
    "method"
  ],
  [
    "src/single.js~single#observeon",
    "class/src/single.js~Single.html#instance-method-observeOn",
    "src/single.js~Single#observeOn",
    "method"
  ],
  [
    "src/single.js~single#onerrorresumenext",
    "class/src/single.js~Single.html#instance-method-onErrorResumeNext",
    "src/single.js~Single#onErrorResumeNext",
    "method"
  ],
  [
    "src/single.js~single#onerrorreturn",
    "class/src/single.js~Single.html#instance-method-onErrorReturn",
    "src/single.js~Single#onErrorReturn",
    "method"
  ],
  [
    "src/single.js~single#onerrorreturnitem",
    "class/src/single.js~Single.html#instance-method-onErrorReturnItem",
    "src/single.js~Single#onErrorReturnItem",
    "method"
  ],
  [
    "src/single.js~single#retry",
    "class/src/single.js~Single.html#instance-method-retry",
    "src/single.js~Single#retry",
    "method"
  ],
  [
    "src/single.js~single#subscribe",
    "class/src/single.js~Single.html#instance-method-subscribe",
    "src/single.js~Single#subscribe",
    "method"
  ],
  [
    "src/single.js~single#subscribeactual",
    "class/src/single.js~Single.html#instance-member-subscribeActual",
    "src/single.js~Single#subscribeActual",
    "member"
  ],
  [
    "src/single.js~single#subscribeon",
    "class/src/single.js~Single.html#instance-method-subscribeOn",
    "src/single.js~Single#subscribeOn",
    "method"
  ],
  [
    "src/single.js~single#subscribewith",
    "class/src/single.js~Single.html#instance-method-subscribeWith",
    "src/single.js~Single#subscribeWith",
    "method"
  ],
  [
    "src/single.js~single#takeuntil",
    "class/src/single.js~Single.html#instance-method-takeUntil",
    "src/single.js~Single#takeUntil",
    "method"
  ],
  [
    "src/single.js~single#then",
    "class/src/single.js~Single.html#instance-method-then",
    "src/single.js~Single#then",
    "method"
  ],
  [
    "src/single.js~single#timeout",
    "class/src/single.js~Single.html#instance-method-timeout",
    "src/single.js~Single#timeout",
    "method"
  ],
  [
    "src/single.js~single#topromise",
    "class/src/single.js~Single.html#instance-method-toPromise",
    "src/single.js~Single#toPromise",
    "method"
  ],
  [
    "src/single.js~single#zipwith",
    "class/src/single.js~Single.html#instance-method-zipWith",
    "src/single.js~Single#zipWith",
    "method"
  ],
  [
    "src/single.js~single.amb",
    "class/src/single.js~Single.html#static-method-amb",
    "src/single.js~Single.amb",
    "method"
  ],
  [
    "src/single.js~single.ambarray",
    "class/src/single.js~Single.html#static-method-ambArray",
    "src/single.js~Single.ambArray",
    "method"
  ],
  [
    "src/single.js~single.create",
    "class/src/single.js~Single.html#static-method-create",
    "src/single.js~Single.create",
    "method"
  ],
  [
    "src/single.js~single.defer",
    "class/src/single.js~Single.html#static-method-defer",
    "src/single.js~Single.defer",
    "method"
  ],
  [
    "src/single.js~single.error",
    "class/src/single.js~Single.html#static-method-error",
    "src/single.js~Single.error",
    "method"
  ],
  [
    "src/single.js~single.fromcallable",
    "class/src/single.js~Single.html#static-method-fromCallable",
    "src/single.js~Single.fromCallable",
    "method"
  ],
  [
    "src/single.js~single.frompromise",
    "class/src/single.js~Single.html#static-method-fromPromise",
    "src/single.js~Single.fromPromise",
    "method"
  ],
  [
    "src/single.js~single.fromresolvable",
    "class/src/single.js~Single.html#static-method-fromResolvable",
    "src/single.js~Single.fromResolvable",
    "method"
  ],
  [
    "src/single.js~single.just",
    "class/src/single.js~Single.html#static-method-just",
    "src/single.js~Single.just",
    "method"
  ],
  [
    "src/single.js~single.merge",
    "class/src/single.js~Single.html#static-method-merge",
    "src/single.js~Single.merge",
    "method"
  ],
  [
    "src/single.js~single.never",
    "class/src/single.js~Single.html#static-method-never",
    "src/single.js~Single.never",
    "method"
  ],
  [
    "src/single.js~single.timer",
    "class/src/single.js~Single.html#static-method-timer",
    "src/single.js~Single.timer",
    "method"
  ],
  [
    "src/single.js~single.zip",
    "class/src/single.js~Single.html#static-method-zip",
    "src/single.js~Single.zip",
    "method"
  ],
  [
    "src/single.js~single.ziparray",
    "class/src/single.js~Single.html#static-method-zipArray",
    "src/single.js~Single.zipArray",
    "method"
  ],
  [
    "src/single.js~thennable",
    "https://promisesaplus.com/",
    "src/single.js~Thennable",
    "external"
  ],
  [
    "test/amb.js",
    "test-file/test/amb.js.html",
    "test/amb.js",
    "testFile"
  ],
  [
    "test/ambarray.js",
    "test-file/test/ambArray.js.html",
    "test/ambArray.js",
    "testFile"
  ],
  [
    "test/ambwith.js",
    "test-file/test/ambWith.js.html",
    "test/ambWith.js",
    "testFile"
  ],
  [
    "test/cache.js",
    "test-file/test/cache.js.html",
    "test/cache.js",
    "testFile"
  ],
  [
    "test/catch.js",
    "test-file/test/catch.js.html",
    "test/catch.js",
    "testFile"
  ],
  [
    "test/compose.js",
    "test-file/test/compose.js.html",
    "test/compose.js",
    "testFile"
  ],
  [
    "test/contains.js",
    "test-file/test/contains.js.html",
    "test/contains.js",
    "testFile"
  ],
  [
    "test/create.js",
    "test-file/test/create.js.html",
    "test/create.js",
    "testFile"
  ],
  [
    "test/defer.js",
    "test-file/test/defer.js.html",
    "test/defer.js",
    "testFile"
  ],
  [
    "test/delay.js",
    "test-file/test/delay.js.html",
    "test/delay.js",
    "testFile"
  ],
  [
    "test/delaysubscription.js",
    "test-file/test/delaySubscription.js.html",
    "test/delaySubscription.js",
    "testFile"
  ],
  [
    "test/delayuntil.js",
    "test-file/test/delayUntil.js.html",
    "test/delayUntil.js",
    "testFile"
  ],
  [
    "test/doaftersuccess.js",
    "test-file/test/doAfterSuccess.js.html",
    "test/doAfterSuccess.js",
    "testFile"
  ],
  [
    "test/doafterterminate.js",
    "test-file/test/doAfterTerminate.js.html",
    "test/doAfterTerminate.js",
    "testFile"
  ],
  [
    "test/dofinally.js",
    "test-file/test/doFinally.js.html",
    "test/doFinally.js",
    "testFile"
  ],
  [
    "test/dooncancel.js",
    "test-file/test/doOnCancel.js.html",
    "test/doOnCancel.js",
    "testFile"
  ],
  [
    "test/doonerror.js",
    "test-file/test/doOnError.js.html",
    "test/doOnError.js",
    "testFile"
  ],
  [
    "test/doonevent.js",
    "test-file/test/doOnEvent.js.html",
    "test/doOnEvent.js",
    "testFile"
  ],
  [
    "test/doonsubscribe.js",
    "test-file/test/doOnSubscribe.js.html",
    "test/doOnSubscribe.js",
    "testFile"
  ],
  [
    "test/doonsuccess.js",
    "test-file/test/doOnSuccess.js.html",
    "test/doOnSuccess.js",
    "testFile"
  ],
  [
    "test/doonterminate.js",
    "test-file/test/doOnTerminate.js.html",
    "test/doOnTerminate.js",
    "testFile"
  ],
  [
    "test/error.js",
    "test-file/test/error.js.html",
    "test/error.js",
    "testFile"
  ],
  [
    "test/flatmap.js",
    "test-file/test/flatMap.js.html",
    "test/flatMap.js",
    "testFile"
  ],
  [
    "test/fromcallable.js",
    "test-file/test/fromCallable.js.html",
    "test/fromCallable.js",
    "testFile"
  ],
  [
    "test/frompromise.js",
    "test-file/test/fromPromise.js.html",
    "test/fromPromise.js",
    "testFile"
  ],
  [
    "test/fromresolvable.js",
    "test-file/test/fromResolvable.js.html",
    "test/fromResolvable.js",
    "testFile"
  ],
  [
    "test/just.js",
    "test-file/test/just.js.html",
    "test/just.js",
    "testFile"
  ],
  [
    "test/lift.js",
    "test-file/test/lift.js.html",
    "test/lift.js",
    "testFile"
  ],
  [
    "test/map.js",
    "test-file/test/map.js.html",
    "test/map.js",
    "testFile"
  ],
  [
    "test/merge.js",
    "test-file/test/merge.js.html",
    "test/merge.js",
    "testFile"
  ],
  [
    "test/never.js",
    "test-file/test/never.js.html",
    "test/never.js",
    "testFile"
  ],
  [
    "test/observeon.js",
    "test-file/test/observeOn.js.html",
    "test/observeOn.js",
    "testFile"
  ],
  [
    "test/onerrorresumenext.js",
    "test-file/test/onErrorResumeNext.js.html",
    "test/onErrorResumeNext.js",
    "testFile"
  ],
  [
    "test/onerrorreturn.js",
    "test-file/test/onErrorReturn.js.html",
    "test/onErrorReturn.js",
    "testFile"
  ],
  [
    "test/onerrorreturnitem.js",
    "test-file/test/onErrorReturnItem.js.html",
    "test/onErrorReturnItem.js",
    "testFile"
  ],
  [
    "test/retry.js",
    "test-file/test/retry.js.html",
    "test/retry.js",
    "testFile"
  ],
  [
    "test/subscribeon.js",
    "test-file/test/subscribeOn.js.html",
    "test/subscribeOn.js",
    "testFile"
  ],
  [
    "test/takeuntil.js",
    "test-file/test/takeUntil.js.html",
    "test/takeUntil.js",
    "testFile"
  ],
  [
    "test/then.js",
    "test-file/test/then.js.html",
    "test/then.js",
    "testFile"
  ],
  [
    "test/timeout.js",
    "test-file/test/timeout.js.html",
    "test/timeout.js",
    "testFile"
  ],
  [
    "test/timer.js",
    "test-file/test/timer.js.html",
    "test/timer.js",
    "testFile"
  ],
  [
    "test/topromise.js",
    "test-file/test/toPromise.js.html",
    "test/toPromise.js",
    "testFile"
  ],
  [
    "test/zip.js",
    "test-file/test/zip.js.html",
    "test/zip.js",
    "testFile"
  ],
  [
    "test/ziparray.js",
    "test-file/test/zipArray.js.html",
    "test/zipArray.js",
    "testFile"
  ],
  [
    "test/zipwith.js",
    "test-file/test/zipWith.js.html",
    "test/zipWith.js",
    "testFile"
  ]
]