window.esdocSearchIndex = [
  [
    "rx-single/src/emitter.js~emitter",
    "class/src/emitter.js~Emitter.html",
    "<span>Emitter</span> <span class=\"search-result-import-path\">rx-single/src/emitter.js</span>",
    "class"
  ],
  [
    "rx-single/src/observer.js~observer",
    "class/src/observer.js~Observer.html",
    "<span>Observer</span> <span class=\"search-result-import-path\">rx-single/src/observer.js</span>",
    "class"
  ],
  [
    "rx-single/src/single.js~single",
    "class/src/single.js~Single.html",
    "<span>Single</span> <span class=\"search-result-import-path\">rx-single/src/single.js</span>",
    "class"
  ],
  [
    "",
    "test-file/test/amb.js.html#lineNumber8",
    "Single",
    "test"
  ],
  [
    "",
    "test-file/test/doOnError.js.html#lineNumber8",
    "Single",
    "test"
  ],
  [
    "",
    "test-file/test/doOnEvent.js.html#lineNumber8",
    "Single",
    "test"
  ],
  [
    "",
    "test-file/test/doOnSubscribe.js.html#lineNumber8",
    "Single",
    "test"
  ],
  [
    "",
    "test-file/test/doOnSuccess.js.html#lineNumber8",
    "Single",
    "test"
  ],
  [
    "",
    "test-file/test/doOnTerminate.js.html#lineNumber8",
    "Single",
    "test"
  ],
  [
    "",
    "test-file/test/error.js.html#lineNumber8",
    "Single",
    "test"
  ],
  [
    "",
    "test-file/test/flatMap.js.html#lineNumber8",
    "Single",
    "test"
  ],
  [
    "",
    "test-file/test/fromCallable.js.html#lineNumber8",
    "Single",
    "test"
  ],
  [
    "",
    "test-file/test/fromPromise.js.html#lineNumber8",
    "Single",
    "test"
  ],
  [
    "",
    "test-file/test/cache.js.html#lineNumber8",
    "Single",
    "test"
  ],
  [
    "",
    "test-file/test/fromResolvable.js.html#lineNumber8",
    "Single",
    "test"
  ],
  [
    "",
    "test-file/test/just.js.html#lineNumber8",
    "Single",
    "test"
  ],
  [
    "",
    "test-file/test/lift.js.html#lineNumber7",
    "Single",
    "test"
  ],
  [
    "",
    "test-file/test/map.js.html#lineNumber8",
    "Single",
    "test"
  ],
  [
    "",
    "test-file/test/merge.js.html#lineNumber8",
    "Single",
    "test"
  ],
  [
    "",
    "test-file/test/never.js.html#lineNumber8",
    "Single",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorResumeNext.js.html#lineNumber8",
    "Single",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorReturn.js.html#lineNumber8",
    "Single",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorReturnItem.js.html#lineNumber8",
    "Single",
    "test"
  ],
  [
    "",
    "test-file/test/catch.js.html#lineNumber8",
    "Single",
    "test"
  ],
  [
    "",
    "test-file/test/retry.js.html#lineNumber8",
    "Single",
    "test"
  ],
  [
    "",
    "test-file/test/takeUntil.js.html#lineNumber8",
    "Single",
    "test"
  ],
  [
    "",
    "test-file/test/then.js.html#lineNumber8",
    "Single",
    "test"
  ],
  [
    "",
    "test-file/test/timeout.js.html#lineNumber8",
    "Single",
    "test"
  ],
  [
    "",
    "test-file/test/compose.js.html#lineNumber8",
    "Single",
    "test"
  ],
  [
    "",
    "test-file/test/timer.js.html#lineNumber8",
    "Single",
    "test"
  ],
  [
    "",
    "test-file/test/toPromise.js.html#lineNumber8",
    "Single",
    "test"
  ],
  [
    "",
    "test-file/test/zip.js.html#lineNumber8",
    "Single",
    "test"
  ],
  [
    "",
    "test-file/test/zipWith.js.html#lineNumber8",
    "Single",
    "test"
  ],
  [
    "",
    "test-file/test/contains.js.html#lineNumber8",
    "Single",
    "test"
  ],
  [
    "",
    "test-file/test/create.js.html#lineNumber8",
    "Single",
    "test"
  ],
  [
    "",
    "test-file/test/defer.js.html#lineNumber8",
    "Single",
    "test"
  ],
  [
    "",
    "test-file/test/delay.js.html#lineNumber8",
    "Single",
    "test"
  ],
  [
    "",
    "test-file/test/delaySubscription.js.html#lineNumber8",
    "Single",
    "test"
  ],
  [
    "",
    "test-file/test/delayUntil.js.html#lineNumber8",
    "Single",
    "test"
  ],
  [
    "",
    "test-file/test/ambWith.js.html#lineNumber8",
    "Single",
    "test"
  ],
  [
    "",
    "test-file/test/doAfterSuccess.js.html#lineNumber8",
    "Single",
    "test"
  ],
  [
    "",
    "test-file/test/doAfterTerminate.js.html#lineNumber8",
    "Single",
    "test"
  ],
  [
    "",
    "test-file/test/doFinally.js.html#lineNumber8",
    "Single",
    "test"
  ],
  [
    "",
    "test-file/test/doOnAbort.js.html#lineNumber8",
    "Single",
    "test"
  ],
  [
    "",
    "test-file/test/amb.js.html#lineNumber12",
    "Single #amb",
    "test"
  ],
  [
    "",
    "test-file/test/amb.js.html#lineNumber16",
    "Single #amb should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/amb.js.html#lineNumber33",
    "Single #amb should signal error from the earliest source.",
    "test"
  ],
  [
    "",
    "test-file/test/amb.js.html#lineNumber53",
    "Single #amb should signal error if given argument is not Iterable",
    "test"
  ],
  [
    "",
    "test-file/test/amb.js.html#lineNumber43",
    "Single #amb should signal error if one of the source is non-Single.",
    "test"
  ],
  [
    "",
    "test-file/test/amb.js.html#lineNumber23",
    "Single #amb should signal success from the earliest source.",
    "test"
  ],
  [
    "",
    "test-file/test/ambWith.js.html#lineNumber12",
    "Single #ambWith",
    "test"
  ],
  [
    "",
    "test-file/test/ambWith.js.html#lineNumber16",
    "Single #ambWith should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/ambWith.js.html#lineNumber23",
    "Single #ambWith should return the same instance if the other value is non-Single",
    "test"
  ],
  [
    "",
    "test-file/test/ambWith.js.html#lineNumber61",
    "Single #ambWith should signal error from the other (if earlier).",
    "test"
  ],
  [
    "",
    "test-file/test/ambWith.js.html#lineNumber51",
    "Single #ambWith should signal error from the source (if earlier).",
    "test"
  ],
  [
    "",
    "test-file/test/ambWith.js.html#lineNumber41",
    "Single #ambWith should signal success from the other (if earlier).",
    "test"
  ],
  [
    "",
    "test-file/test/ambWith.js.html#lineNumber31",
    "Single #ambWith should signal success from the source (if earlier)",
    "test"
  ],
  [
    "",
    "test-file/test/cache.js.html#lineNumber12",
    "Single #cache",
    "test"
  ],
  [
    "",
    "test-file/test/cache.js.html#lineNumber16",
    "Single #cache should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/cache.js.html#lineNumber43",
    "Single #cache should signal cached error value",
    "test"
  ],
  [
    "",
    "test-file/test/cache.js.html#lineNumber23",
    "Single #cache should signal cached success value",
    "test"
  ],
  [
    "",
    "test-file/test/catch.js.html#lineNumber12",
    "Single #catch",
    "test"
  ],
  [
    "",
    "test-file/test/catch.js.html#lineNumber16",
    "Single #catch should create a Promise",
    "test"
  ],
  [
    "",
    "test-file/test/compose.js.html#lineNumber12",
    "Single #compose",
    "test"
  ],
  [
    "",
    "test-file/test/compose.js.html#lineNumber33",
    "Single #compose should correctly signal the composed Single",
    "test"
  ],
  [
    "",
    "test-file/test/compose.js.html#lineNumber25",
    "Single #compose should return a Single from the transformer",
    "test"
  ],
  [
    "",
    "test-file/test/compose.js.html#lineNumber16",
    "Single #compose should return the same instance if no function is provided",
    "test"
  ],
  [
    "",
    "test-file/test/compose.js.html#lineNumber44",
    "Single #compose should signal error if the transformer function returned a non-Single",
    "test"
  ],
  [
    "",
    "test-file/test/contains.js.html#lineNumber12",
    "Single #contains",
    "test"
  ],
  [
    "",
    "test-file/test/contains.js.html#lineNumber16",
    "Single #contains should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/contains.js.html#lineNumber23",
    "Single #contains should return the same instance if the compared value is undefined",
    "test"
  ],
  [
    "",
    "test-file/test/contains.js.html#lineNumber51",
    "Single #contains should signal an error if the comparer throws an error.",
    "test"
  ],
  [
    "",
    "test-file/test/contains.js.html#lineNumber41",
    "Single #contains should signal false if the success value and the compared value are both equal.",
    "test"
  ],
  [
    "",
    "test-file/test/contains.js.html#lineNumber31",
    "Single #contains should signal true if the success value and the compared value are both equal.",
    "test"
  ],
  [
    "",
    "test-file/test/create.js.html#lineNumber12",
    "Single #create",
    "test"
  ],
  [
    "",
    "test-file/test/create.js.html#lineNumber57",
    "Single #create should be aborted successfully if emitter is aborted before any signal.",
    "test"
  ],
  [
    "",
    "test-file/test/create.js.html#lineNumber16",
    "Single #create should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/create.js.html#lineNumber74",
    "Single #create should signal error if subscriber throws an error.",
    "test"
  ],
  [
    "",
    "test-file/test/create.js.html#lineNumber24",
    "Single #create should signal error if the create received a non-function",
    "test"
  ],
  [
    "",
    "test-file/test/create.js.html#lineNumber46",
    "Single #create should signal error if the emitter signals error with undefined value.",
    "test"
  ],
  [
    "",
    "test-file/test/create.js.html#lineNumber35",
    "Single #create should signal error if the emitter signals success with undefined value.",
    "test"
  ],
  [
    "",
    "test-file/test/defer.js.html#lineNumber12",
    "Single #defer",
    "test"
  ],
  [
    "",
    "test-file/test/defer.js.html#lineNumber16",
    "Single #defer should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/defer.js.html#lineNumber35",
    "Single #defer should signal error if callable returns a non-Single",
    "test"
  ],
  [
    "",
    "test-file/test/defer.js.html#lineNumber46",
    "Single #defer should signal error if callable throws an error",
    "test"
  ],
  [
    "",
    "test-file/test/defer.js.html#lineNumber24",
    "Single #defer should succeed with the given value.",
    "test"
  ],
  [
    "",
    "test-file/test/delay.js.html#lineNumber12",
    "Single #delay",
    "test"
  ],
  [
    "",
    "test-file/test/delay.js.html#lineNumber16",
    "Single #delay should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/delay.js.html#lineNumber66",
    "Single #delay should not signal error if aborted.",
    "test"
  ],
  [
    "",
    "test-file/test/delay.js.html#lineNumber51",
    "Single #delay should not signal success if aborted.",
    "test"
  ],
  [
    "",
    "test-file/test/delay.js.html#lineNumber23",
    "Single #delay should return the same instance if the amount is not a number.",
    "test"
  ],
  [
    "",
    "test-file/test/delay.js.html#lineNumber41",
    "Single #delay should signal error with the given value.",
    "test"
  ],
  [
    "",
    "test-file/test/delay.js.html#lineNumber31",
    "Single #delay should signal success with the given value.",
    "test"
  ],
  [
    "",
    "test-file/test/delaySubscription.js.html#lineNumber12",
    "Single #delaySubscription",
    "test"
  ],
  [
    "",
    "test-file/test/delaySubscription.js.html#lineNumber16",
    "Single #delaySubscription should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/delaySubscription.js.html#lineNumber66",
    "Single #delaySubscription should not signal error if aborted.",
    "test"
  ],
  [
    "",
    "test-file/test/delaySubscription.js.html#lineNumber51",
    "Single #delaySubscription should not signal success if aborted.",
    "test"
  ],
  [
    "",
    "test-file/test/delaySubscription.js.html#lineNumber23",
    "Single #delaySubscription should return the same instance if the amount is not a number.",
    "test"
  ],
  [
    "",
    "test-file/test/delaySubscription.js.html#lineNumber41",
    "Single #delaySubscription should signal error with the given value.",
    "test"
  ],
  [
    "",
    "test-file/test/delaySubscription.js.html#lineNumber31",
    "Single #delaySubscription should signal success with the given value.",
    "test"
  ],
  [
    "",
    "test-file/test/delayUntil.js.html#lineNumber12",
    "Single #delayUntil",
    "test"
  ],
  [
    "",
    "test-file/test/delayUntil.js.html#lineNumber16",
    "Single #delayUntil should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/delayUntil.js.html#lineNumber76",
    "Single #delayUntil should not signal error if aborted.",
    "test"
  ],
  [
    "",
    "test-file/test/delayUntil.js.html#lineNumber61",
    "Single #delayUntil should not signal success if aborted.",
    "test"
  ],
  [
    "",
    "test-file/test/delayUntil.js.html#lineNumber23",
    "Single #delayUntil should return the same instance if the provided value is not a Single.",
    "test"
  ],
  [
    "",
    "test-file/test/delayUntil.js.html#lineNumber51",
    "Single #delayUntil should signal error if other Single signals error.",
    "test"
  ],
  [
    "",
    "test-file/test/delayUntil.js.html#lineNumber41",
    "Single #delayUntil should signal error with the given value.",
    "test"
  ],
  [
    "",
    "test-file/test/delayUntil.js.html#lineNumber31",
    "Single #delayUntil should signal success with the given value.",
    "test"
  ],
  [
    "",
    "test-file/test/doAfterSuccess.js.html#lineNumber12",
    "Single #doAfterSuccess",
    "test"
  ],
  [
    "",
    "test-file/test/doAfterSuccess.js.html#lineNumber31",
    "Single #doAfterSuccess should call the given function after success.",
    "test"
  ],
  [
    "",
    "test-file/test/doAfterSuccess.js.html#lineNumber16",
    "Single #doAfterSuccess should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/doAfterSuccess.js.html#lineNumber23",
    "Single #doAfterSuccess should return the same instance if the method received a non-function parameter.",
    "test"
  ],
  [
    "",
    "test-file/test/doAfterTerminate.js.html#lineNumber12",
    "Single #doAfterTerminate",
    "test"
  ],
  [
    "",
    "test-file/test/doAfterTerminate.js.html#lineNumber43",
    "Single #doAfterTerminate should call the given function after error.",
    "test"
  ],
  [
    "",
    "test-file/test/doAfterTerminate.js.html#lineNumber31",
    "Single #doAfterTerminate should call the given function after success.",
    "test"
  ],
  [
    "",
    "test-file/test/doAfterTerminate.js.html#lineNumber16",
    "Single #doAfterTerminate should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/doAfterTerminate.js.html#lineNumber23",
    "Single #doAfterTerminate should return the same instance if the method received a non-function parameter.",
    "test"
  ],
  [
    "",
    "test-file/test/doFinally.js.html#lineNumber12",
    "Single #doFinally",
    "test"
  ],
  [
    "",
    "test-file/test/doFinally.js.html#lineNumber43",
    "Single #doFinally should call the given function after error.",
    "test"
  ],
  [
    "",
    "test-file/test/doFinally.js.html#lineNumber31",
    "Single #doFinally should call the given function after success.",
    "test"
  ],
  [
    "",
    "test-file/test/doFinally.js.html#lineNumber55",
    "Single #doFinally should call the given function on dispose.",
    "test"
  ],
  [
    "",
    "test-file/test/doFinally.js.html#lineNumber16",
    "Single #doFinally should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/doFinally.js.html#lineNumber23",
    "Single #doFinally should return the same instance if the method received a non-function parameter.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnAbort.js.html#lineNumber12",
    "Single #doOnAbort",
    "test"
  ],
  [
    "",
    "test-file/test/doOnAbort.js.html#lineNumber59",
    "Single #doOnAbort should call the given function on abort.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnAbort.js.html#lineNumber16",
    "Single #doOnAbort should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/doOnAbort.js.html#lineNumber23",
    "Single #doOnAbort should return the same instance if the method received a non-function parameter.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnAbort.js.html#lineNumber45",
    "Single #doOnAbort should signal the error value then fire abort callback.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnAbort.js.html#lineNumber31",
    "Single #doOnAbort should signal the success value then fire abort callback.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnError.js.html#lineNumber12",
    "Single #doOnError",
    "test"
  ],
  [
    "",
    "test-file/test/doOnError.js.html#lineNumber31",
    "Single #doOnError should call the given function on error.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnError.js.html#lineNumber16",
    "Single #doOnError should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/doOnError.js.html#lineNumber23",
    "Single #doOnError should return the same instance if the method received a non-function parameter.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnEvent.js.html#lineNumber12",
    "Single #doOnEvent",
    "test"
  ],
  [
    "",
    "test-file/test/doOnEvent.js.html#lineNumber43",
    "Single #doOnEvent should call the given function on error.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnEvent.js.html#lineNumber31",
    "Single #doOnEvent should call the given function on success.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnEvent.js.html#lineNumber16",
    "Single #doOnEvent should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/doOnEvent.js.html#lineNumber23",
    "Single #doOnEvent should return the same instance if the method received a non-function parameter.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnSubscribe.js.html#lineNumber12",
    "Single #doOnSubscribe",
    "test"
  ],
  [
    "",
    "test-file/test/doOnSubscribe.js.html#lineNumber31",
    "Single #doOnSubscribe should be called before actual subscription.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnSubscribe.js.html#lineNumber16",
    "Single #doOnSubscribe should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/doOnSubscribe.js.html#lineNumber23",
    "Single #doOnSubscribe should return the same instance if no function is passed",
    "test"
  ],
  [
    "",
    "test-file/test/doOnSuccess.js.html#lineNumber12",
    "Single #doOnSuccess",
    "test"
  ],
  [
    "",
    "test-file/test/doOnSuccess.js.html#lineNumber31",
    "Single #doOnSuccess should call the given function on success.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnSuccess.js.html#lineNumber16",
    "Single #doOnSuccess should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/doOnSuccess.js.html#lineNumber23",
    "Single #doOnSuccess should return the same instance if the method received a non-function parameter.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnTerminate.js.html#lineNumber12",
    "Single #doOnTerminate",
    "test"
  ],
  [
    "",
    "test-file/test/doOnTerminate.js.html#lineNumber43",
    "Single #doOnTerminate should call the given function on error.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnTerminate.js.html#lineNumber31",
    "Single #doOnTerminate should call the given function on success.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnTerminate.js.html#lineNumber16",
    "Single #doOnTerminate should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/doOnTerminate.js.html#lineNumber23",
    "Single #doOnTerminate should return the same instance if the method received a non-function parameter.",
    "test"
  ],
  [
    "",
    "test-file/test/error.js.html#lineNumber12",
    "Single #error",
    "test"
  ],
  [
    "",
    "test-file/test/error.js.html#lineNumber16",
    "Single #error should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/error.js.html#lineNumber57",
    "Single #error should error if the callable throws an error.",
    "test"
  ],
  [
    "",
    "test-file/test/error.js.html#lineNumber46",
    "Single #error should error with the a message if the callable returned undefined",
    "test"
  ],
  [
    "",
    "test-file/test/error.js.html#lineNumber35",
    "Single #error should error with the a message if the given value is undefined",
    "test"
  ],
  [
    "",
    "test-file/test/error.js.html#lineNumber24",
    "Single #error should error with the given value.",
    "test"
  ],
  [
    "",
    "test-file/test/flatMap.js.html#lineNumber12",
    "Single #flatMap",
    "test"
  ],
  [
    "",
    "test-file/test/flatMap.js.html#lineNumber16",
    "Single #flatMap should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/flatMap.js.html#lineNumber24",
    "Single #flatMap should return the same instance if the method received a non-function parameter.",
    "test"
  ],
  [
    "",
    "test-file/test/flatMap.js.html#lineNumber32",
    "Single #flatMap should signal error if mapper returns a non-Single",
    "test"
  ],
  [
    "",
    "test-file/test/flatMap.js.html#lineNumber43",
    "Single #flatMap should signal success of the returned Single",
    "test"
  ],
  [
    "",
    "test-file/test/fromCallable.js.html#lineNumber12",
    "Single #fromCallable",
    "test"
  ],
  [
    "",
    "test-file/test/fromCallable.js.html#lineNumber16",
    "Single #fromCallable should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/fromCallable.js.html#lineNumber58",
    "Single #fromCallable should signal an error if the callable is not a function",
    "test"
  ],
  [
    "",
    "test-file/test/fromCallable.js.html#lineNumber47",
    "Single #fromCallable should signal an error if the callable returns a rejected Promise.",
    "test"
  ],
  [
    "",
    "test-file/test/fromCallable.js.html#lineNumber34",
    "Single #fromCallable should signal an error if the callable throws an error.",
    "test"
  ],
  [
    "",
    "test-file/test/fromCallable.js.html#lineNumber23",
    "Single #fromCallable should succeed with the given value.",
    "test"
  ],
  [
    "",
    "test-file/test/fromPromise.js.html#lineNumber12",
    "Single #fromPromise",
    "test"
  ],
  [
    "",
    "test-file/test/fromPromise.js.html#lineNumber16",
    "Single #fromPromise should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/fromPromise.js.html#lineNumber35",
    "Single #fromPromise should signal error if the given value is not Promise like",
    "test"
  ],
  [
    "",
    "test-file/test/fromPromise.js.html#lineNumber23",
    "Single #fromPromise should succeed with the given value.",
    "test"
  ],
  [
    "",
    "test-file/test/fromResolvable.js.html#lineNumber12",
    "Single #fromResolvable",
    "test"
  ],
  [
    "",
    "test-file/test/fromResolvable.js.html#lineNumber16",
    "Single #fromResolvable should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/fromResolvable.js.html#lineNumber34",
    "Single #fromResolvable should signal error if the given value is not a function",
    "test"
  ],
  [
    "",
    "test-file/test/fromResolvable.js.html#lineNumber23",
    "Single #fromResolvable should succeed with the given value.",
    "test"
  ],
  [
    "",
    "test-file/test/just.js.html#lineNumber12",
    "Single #just",
    "test"
  ],
  [
    "",
    "test-file/test/just.js.html#lineNumber16",
    "Single #just should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/just.js.html#lineNumber35",
    "Single #just should emit error if value is undefined.",
    "test"
  ],
  [
    "",
    "test-file/test/just.js.html#lineNumber24",
    "Single #just should succeed with the given value.",
    "test"
  ],
  [
    "",
    "test-file/test/lift.js.html#lineNumber11",
    "Single #lift",
    "test"
  ],
  [
    "",
    "test-file/test/lift.js.html#lineNumber15",
    "Single #lift should return the same instance if no function is provided",
    "test"
  ],
  [
    "",
    "test-file/test/lift.js.html#lineNumber24",
    "Single #lift should signal an error if the lift operator returned a non-Observer",
    "test"
  ],
  [
    "",
    "test-file/test/lift.js.html#lineNumber35",
    "Single #lift should subscribe successfully",
    "test"
  ],
  [
    "",
    "test-file/test/map.js.html#lineNumber12",
    "Single #map",
    "test"
  ],
  [
    "",
    "test-file/test/map.js.html#lineNumber16",
    "Single #map should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/map.js.html#lineNumber58",
    "Single #map should retain the value if no function is supplied.",
    "test"
  ],
  [
    "",
    "test-file/test/map.js.html#lineNumber34",
    "Single #map should signal an error if the mapper throws an error",
    "test"
  ],
  [
    "",
    "test-file/test/map.js.html#lineNumber47",
    "Single #map should signal an error if the mapper throws an error",
    "test"
  ],
  [
    "",
    "test-file/test/map.js.html#lineNumber23",
    "Single #map should succeed with the given value.",
    "test"
  ],
  [
    "",
    "test-file/test/merge.js.html#lineNumber12",
    "Single #merge",
    "test"
  ],
  [
    "",
    "test-file/test/merge.js.html#lineNumber16",
    "Single #merge should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/merge.js.html#lineNumber24",
    "Single #merge should signal error if no source is provided",
    "test"
  ],
  [
    "",
    "test-file/test/merge.js.html#lineNumber35",
    "Single #merge should signal error if source emitted a non-Single",
    "test"
  ],
  [
    "",
    "test-file/test/merge.js.html#lineNumber46",
    "Single #merge should signal success of the signaled Single",
    "test"
  ],
  [
    "",
    "test-file/test/never.js.html#lineNumber12",
    "Single #never",
    "test"
  ],
  [
    "",
    "test-file/test/never.js.html#lineNumber16",
    "Single #never should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/never.js.html#lineNumber23",
    "Single #never should not signal.",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorResumeNext.js.html#lineNumber12",
    "Single #onErrorResumeNext",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorResumeNext.js.html#lineNumber16",
    "Single #onErrorResumeNext should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorResumeNext.js.html#lineNumber61",
    "Single #onErrorResumeNext should emit error if provide function returns non-Single.",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorResumeNext.js.html#lineNumber51",
    "Single #onErrorResumeNext should emit error if provide function throws error.",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorResumeNext.js.html#lineNumber23",
    "Single #onErrorResumeNext should return the same instance if parameter passed is not a Single or a function",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorResumeNext.js.html#lineNumber31",
    "Single #onErrorResumeNext should subscribe to the given Single",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorResumeNext.js.html#lineNumber41",
    "Single #onErrorResumeNext should subscribe to the given Single-producing Function",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorReturn.js.html#lineNumber12",
    "Single #onErrorReturn",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorReturn.js.html#lineNumber16",
    "Single #onErrorReturn should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorReturn.js.html#lineNumber52",
    "Single #onErrorReturn should emit error if provide function returns undefined.",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorReturn.js.html#lineNumber42",
    "Single #onErrorReturn should emit error if provide function throws error.",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorReturn.js.html#lineNumber31",
    "Single #onErrorReturn should emit the supplied item by the given function in case of error",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorReturn.js.html#lineNumber23",
    "Single #onErrorReturn should return the same instance if parameter passed is not a Single or a function",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorReturnItem.js.html#lineNumber12",
    "Single #onErrorReturnItem",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorReturnItem.js.html#lineNumber16",
    "Single #onErrorReturnItem should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorReturnItem.js.html#lineNumber31",
    "Single #onErrorReturnItem should emit the given item in case of error",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorReturnItem.js.html#lineNumber23",
    "Single #onErrorReturnItem should return the same instance if parameter passed is not a Single or a function",
    "test"
  ],
  [
    "",
    "test-file/test/retry.js.html#lineNumber12",
    "Single #retry",
    "test"
  ],
  [
    "",
    "test-file/test/retry.js.html#lineNumber16",
    "Single #retry should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/retry.js.html#lineNumber35",
    "Single #retry should retry if there is an error and if it passes the predicate",
    "test"
  ],
  [
    "",
    "test-file/test/retry.js.html#lineNumber24",
    "Single #retry should signal a success if no error",
    "test"
  ],
  [
    "",
    "test-file/test/retry.js.html#lineNumber52",
    "Single #retry should signal an error if predicate is false",
    "test"
  ],
  [
    "",
    "test-file/test/takeUntil.js.html#lineNumber12",
    "Single #takeUntil",
    "test"
  ],
  [
    "",
    "test-file/test/takeUntil.js.html#lineNumber16",
    "Single #takeUntil should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/takeUntil.js.html#lineNumber24",
    "Single #takeUntil should return the same instance if no other Single is provided",
    "test"
  ],
  [
    "",
    "test-file/test/takeUntil.js.html#lineNumber55",
    "Single #takeUntil should signal error if other Single has emitted a success signal",
    "test"
  ],
  [
    "",
    "test-file/test/takeUntil.js.html#lineNumber66",
    "Single #takeUntil should signal error if other Single has emitted an error signal",
    "test"
  ],
  [
    "",
    "test-file/test/takeUntil.js.html#lineNumber77",
    "Single #takeUntil should signal error if source signals error, nonetheless",
    "test"
  ],
  [
    "",
    "test-file/test/takeUntil.js.html#lineNumber33",
    "Single #takeUntil should signal success if other Single has not emitted a success signal",
    "test"
  ],
  [
    "",
    "test-file/test/takeUntil.js.html#lineNumber44",
    "Single #takeUntil should signal success if other Single has not emitted an error signal",
    "test"
  ],
  [
    "",
    "test-file/test/then.js.html#lineNumber12",
    "Single #then",
    "test"
  ],
  [
    "",
    "test-file/test/then.js.html#lineNumber16",
    "Single #then should create a Promise",
    "test"
  ],
  [
    "",
    "test-file/test/timeout.js.html#lineNumber12",
    "Single #timeout",
    "test"
  ],
  [
    "",
    "test-file/test/timeout.js.html#lineNumber16",
    "Single #timeout should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/timeout.js.html#lineNumber76",
    "Single #timeout should not signal error if aborted.",
    "test"
  ],
  [
    "",
    "test-file/test/timeout.js.html#lineNumber61",
    "Single #timeout should not signal success if aborted.",
    "test"
  ],
  [
    "",
    "test-file/test/timeout.js.html#lineNumber23",
    "Single #timeout should return the same instance if the amount is not a number.",
    "test"
  ],
  [
    "",
    "test-file/test/timeout.js.html#lineNumber51",
    "Single #timeout should signal error if the Single does not emit item within the given timeout.",
    "test"
  ],
  [
    "",
    "test-file/test/timeout.js.html#lineNumber41",
    "Single #timeout should signal error with the given value.",
    "test"
  ],
  [
    "",
    "test-file/test/timeout.js.html#lineNumber31",
    "Single #timeout should signal success with the given value.",
    "test"
  ],
  [
    "",
    "test-file/test/timer.js.html#lineNumber12",
    "Single #timer",
    "test"
  ],
  [
    "",
    "test-file/test/timer.js.html#lineNumber16",
    "Single #timer should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/timer.js.html#lineNumber44",
    "Single #timer should not signal success if aborted.",
    "test"
  ],
  [
    "",
    "test-file/test/timer.js.html#lineNumber23",
    "Single #timer should signal error if amount is not a number.",
    "test"
  ],
  [
    "",
    "test-file/test/timer.js.html#lineNumber34",
    "Single #timer should signal success 0",
    "test"
  ],
  [
    "",
    "test-file/test/toPromise.js.html#lineNumber12",
    "Single #toPromise",
    "test"
  ],
  [
    "",
    "test-file/test/toPromise.js.html#lineNumber16",
    "Single #toPromise should create a Promise",
    "test"
  ],
  [
    "",
    "test-file/test/zip.js.html#lineNumber12",
    "Single #zip",
    "test"
  ],
  [
    "",
    "test-file/test/zip.js.html#lineNumber16",
    "Single #zip should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/zip.js.html#lineNumber104",
    "Single #zip should not signal success if aborted.",
    "test"
  ],
  [
    "",
    "test-file/test/zip.js.html#lineNumber43",
    "Single #zip should signal an error if the zipper throws an error",
    "test"
  ],
  [
    "",
    "test-file/test/zip.js.html#lineNumber94",
    "Single #zip should signal error if a source throws error.",
    "test"
  ],
  [
    "",
    "test-file/test/zip.js.html#lineNumber84",
    "Single #zip should signal error if one of the sources is undefined.",
    "test"
  ],
  [
    "",
    "test-file/test/zip.js.html#lineNumber33",
    "Single #zip should signal error if source is empty iterable.",
    "test"
  ],
  [
    "",
    "test-file/test/zip.js.html#lineNumber23",
    "Single #zip should signal error if sources is not iterable.",
    "test"
  ],
  [
    "",
    "test-file/test/zip.js.html#lineNumber54",
    "Single #zip should signal success with an array (no zipper function).",
    "test"
  ],
  [
    "",
    "test-file/test/zip.js.html#lineNumber64",
    "Single #zip should signal success with an array with the correct values (no zipper function).",
    "test"
  ],
  [
    "",
    "test-file/test/zip.js.html#lineNumber74",
    "Single #zip should signal success with an array with the correct values, consider non-Single (no zipper function).",
    "test"
  ],
  [
    "",
    "test-file/test/zipWith.js.html#lineNumber12",
    "Single #zipWith",
    "test"
  ],
  [
    "",
    "test-file/test/zipWith.js.html#lineNumber16",
    "Single #zipWith should create a Single",
    "test"
  ],
  [
    "",
    "test-file/test/zipWith.js.html#lineNumber93",
    "Single #zipWith should not signal success if aborted.",
    "test"
  ],
  [
    "",
    "test-file/test/zipWith.js.html#lineNumber23",
    "Single #zipWith should return the same instance if the other parameter is non-Single",
    "test"
  ],
  [
    "",
    "test-file/test/zipWith.js.html#lineNumber31",
    "Single #zipWith should signal an error if the zipper returns undefined",
    "test"
  ],
  [
    "",
    "test-file/test/zipWith.js.html#lineNumber42",
    "Single #zipWith should signal an error if the zipper returns undefined",
    "test"
  ],
  [
    "",
    "test-file/test/zipWith.js.html#lineNumber83",
    "Single #zipWith should signal error if other Single throws error.",
    "test"
  ],
  [
    "",
    "test-file/test/zipWith.js.html#lineNumber73",
    "Single #zipWith should signal error if source throws error.",
    "test"
  ],
  [
    "",
    "test-file/test/zipWith.js.html#lineNumber53",
    "Single #zipWith should signal success with an array (no zipper function).",
    "test"
  ],
  [
    "",
    "test-file/test/zipWith.js.html#lineNumber63",
    "Single #zipWith should signal success with an array with the correct values (no zipper function).",
    "test"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/emitter.js",
    "file/src/emitter.js.html",
    "src/emitter.js",
    "file"
  ],
  [
    "src/emitter.js~emitter#onerror",
    "class/src/emitter.js~Emitter.html#instance-method-onError",
    "src/emitter.js~Emitter#onError",
    "method"
  ],
  [
    "src/emitter.js~emitter#onsuccess",
    "class/src/emitter.js~Emitter.html#instance-method-onSuccess",
    "src/emitter.js~Emitter#onSuccess",
    "method"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/internal/operators.js",
    "file/src/internal/operators.js.html",
    "src/internal/operators.js",
    "file"
  ],
  [
    "src/internal/operators/amb.js",
    "file/src/internal/operators/amb.js.html",
    "src/internal/operators/amb.js",
    "file"
  ],
  [
    "src/internal/operators/ambwith.js",
    "file/src/internal/operators/ambWith.js.html",
    "src/internal/operators/ambWith.js",
    "file"
  ],
  [
    "src/internal/operators/cache.js",
    "file/src/internal/operators/cache.js.html",
    "src/internal/operators/cache.js",
    "file"
  ],
  [
    "src/internal/operators/compose.js",
    "file/src/internal/operators/compose.js.html",
    "src/internal/operators/compose.js",
    "file"
  ],
  [
    "src/internal/operators/contains.js",
    "file/src/internal/operators/contains.js.html",
    "src/internal/operators/contains.js",
    "file"
  ],
  [
    "src/internal/operators/create.js",
    "file/src/internal/operators/create.js.html",
    "src/internal/operators/create.js",
    "file"
  ],
  [
    "src/internal/operators/defer.js",
    "file/src/internal/operators/defer.js.html",
    "src/internal/operators/defer.js",
    "file"
  ],
  [
    "src/internal/operators/delay.js",
    "file/src/internal/operators/delay.js.html",
    "src/internal/operators/delay.js",
    "file"
  ],
  [
    "src/internal/operators/delaysubscription.js",
    "file/src/internal/operators/delaySubscription.js.html",
    "src/internal/operators/delaySubscription.js",
    "file"
  ],
  [
    "src/internal/operators/delayuntil.js",
    "file/src/internal/operators/delayUntil.js.html",
    "src/internal/operators/delayUntil.js",
    "file"
  ],
  [
    "src/internal/operators/doaftersuccess.js",
    "file/src/internal/operators/doAfterSuccess.js.html",
    "src/internal/operators/doAfterSuccess.js",
    "file"
  ],
  [
    "src/internal/operators/doafterterminate.js",
    "file/src/internal/operators/doAfterTerminate.js.html",
    "src/internal/operators/doAfterTerminate.js",
    "file"
  ],
  [
    "src/internal/operators/dofinally.js",
    "file/src/internal/operators/doFinally.js.html",
    "src/internal/operators/doFinally.js",
    "file"
  ],
  [
    "src/internal/operators/doonabort.js",
    "file/src/internal/operators/doOnAbort.js.html",
    "src/internal/operators/doOnAbort.js",
    "file"
  ],
  [
    "src/internal/operators/doonerror.js",
    "file/src/internal/operators/doOnError.js.html",
    "src/internal/operators/doOnError.js",
    "file"
  ],
  [
    "src/internal/operators/doonevent.js",
    "file/src/internal/operators/doOnEvent.js.html",
    "src/internal/operators/doOnEvent.js",
    "file"
  ],
  [
    "src/internal/operators/doonsubscribe.js",
    "file/src/internal/operators/doOnSubscribe.js.html",
    "src/internal/operators/doOnSubscribe.js",
    "file"
  ],
  [
    "src/internal/operators/doonsuccess.js",
    "file/src/internal/operators/doOnSuccess.js.html",
    "src/internal/operators/doOnSuccess.js",
    "file"
  ],
  [
    "src/internal/operators/doonterminate.js",
    "file/src/internal/operators/doOnTerminate.js.html",
    "src/internal/operators/doOnTerminate.js",
    "file"
  ],
  [
    "src/internal/operators/error.js",
    "file/src/internal/operators/error.js.html",
    "src/internal/operators/error.js",
    "file"
  ],
  [
    "src/internal/operators/flatmap.js",
    "file/src/internal/operators/flatMap.js.html",
    "src/internal/operators/flatMap.js",
    "file"
  ],
  [
    "src/internal/operators/fromcallable.js",
    "file/src/internal/operators/fromCallable.js.html",
    "src/internal/operators/fromCallable.js",
    "file"
  ],
  [
    "src/internal/operators/frompromise.js",
    "file/src/internal/operators/fromPromise.js.html",
    "src/internal/operators/fromPromise.js",
    "file"
  ],
  [
    "src/internal/operators/fromresolvable.js",
    "file/src/internal/operators/fromResolvable.js.html",
    "src/internal/operators/fromResolvable.js",
    "file"
  ],
  [
    "src/internal/operators/just.js",
    "file/src/internal/operators/just.js.html",
    "src/internal/operators/just.js",
    "file"
  ],
  [
    "src/internal/operators/lift.js",
    "file/src/internal/operators/lift.js.html",
    "src/internal/operators/lift.js",
    "file"
  ],
  [
    "src/internal/operators/map.js",
    "file/src/internal/operators/map.js.html",
    "src/internal/operators/map.js",
    "file"
  ],
  [
    "src/internal/operators/merge.js",
    "file/src/internal/operators/merge.js.html",
    "src/internal/operators/merge.js",
    "file"
  ],
  [
    "src/internal/operators/never.js",
    "file/src/internal/operators/never.js.html",
    "src/internal/operators/never.js",
    "file"
  ],
  [
    "src/internal/operators/onerrorresumenext.js",
    "file/src/internal/operators/onErrorResumeNext.js.html",
    "src/internal/operators/onErrorResumeNext.js",
    "file"
  ],
  [
    "src/internal/operators/onerrorreturn.js",
    "file/src/internal/operators/onErrorReturn.js.html",
    "src/internal/operators/onErrorReturn.js",
    "file"
  ],
  [
    "src/internal/operators/onerrorreturnitem.js",
    "file/src/internal/operators/onErrorReturnItem.js.html",
    "src/internal/operators/onErrorReturnItem.js",
    "file"
  ],
  [
    "src/internal/operators/retry.js",
    "file/src/internal/operators/retry.js.html",
    "src/internal/operators/retry.js",
    "file"
  ],
  [
    "src/internal/operators/takeuntil.js",
    "file/src/internal/operators/takeUntil.js.html",
    "src/internal/operators/takeUntil.js",
    "file"
  ],
  [
    "src/internal/operators/timeout.js",
    "file/src/internal/operators/timeout.js.html",
    "src/internal/operators/timeout.js",
    "file"
  ],
  [
    "src/internal/operators/timer.js",
    "file/src/internal/operators/timer.js.html",
    "src/internal/operators/timer.js",
    "file"
  ],
  [
    "src/internal/operators/zip.js",
    "file/src/internal/operators/zip.js.html",
    "src/internal/operators/zip.js",
    "file"
  ],
  [
    "src/internal/operators/zipwith.js",
    "file/src/internal/operators/zipWith.js.html",
    "src/internal/operators/zipWith.js",
    "file"
  ],
  [
    "src/internal/utils.js",
    "file/src/internal/utils.js.html",
    "src/internal/utils.js",
    "file"
  ],
  [
    "src/observer.js",
    "file/src/observer.js.html",
    "src/observer.js",
    "file"
  ],
  [
    "src/observer.js~observer#onerror",
    "class/src/observer.js~Observer.html#instance-method-onError",
    "src/observer.js~Observer#onError",
    "method"
  ],
  [
    "src/observer.js~observer#onsubscribe",
    "class/src/observer.js~Observer.html#instance-method-onSubscribe",
    "src/observer.js~Observer#onSubscribe",
    "method"
  ],
  [
    "src/observer.js~observer#onsuccess",
    "class/src/observer.js~Observer.html#instance-method-onSuccess",
    "src/observer.js~Observer#onSuccess",
    "method"
  ],
  [
    "src/single.js",
    "file/src/single.js.html",
    "src/single.js",
    "file"
  ],
  [
    "src/single.js~abortcontroller",
    "https://developer.mozilla.org/en-US/docs/Web/API/AbortController",
    "src/single.js~AbortController",
    "external"
  ],
  [
    "src/single.js~iterable",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols",
    "src/single.js~Iterable",
    "external"
  ],
  [
    "src/single.js~promiselike",
    "https://promisesaplus.com/",
    "src/single.js~PromiseLike",
    "external"
  ],
  [
    "src/single.js~single#ambwith",
    "class/src/single.js~Single.html#instance-method-ambWith",
    "src/single.js~Single#ambWith",
    "method"
  ],
  [
    "src/single.js~single#cache",
    "class/src/single.js~Single.html#instance-method-cache",
    "src/single.js~Single#cache",
    "method"
  ],
  [
    "src/single.js~single#catch",
    "class/src/single.js~Single.html#instance-method-catch",
    "src/single.js~Single#catch",
    "method"
  ],
  [
    "src/single.js~single#compose",
    "class/src/single.js~Single.html#instance-method-compose",
    "src/single.js~Single#compose",
    "method"
  ],
  [
    "src/single.js~single#contains",
    "class/src/single.js~Single.html#instance-method-contains",
    "src/single.js~Single#contains",
    "method"
  ],
  [
    "src/single.js~single#delay",
    "class/src/single.js~Single.html#instance-method-delay",
    "src/single.js~Single#delay",
    "method"
  ],
  [
    "src/single.js~single#delaysubscription",
    "class/src/single.js~Single.html#instance-method-delaySubscription",
    "src/single.js~Single#delaySubscription",
    "method"
  ],
  [
    "src/single.js~single#delayuntil",
    "class/src/single.js~Single.html#instance-method-delayUntil",
    "src/single.js~Single#delayUntil",
    "method"
  ],
  [
    "src/single.js~single#doaftersuccess",
    "class/src/single.js~Single.html#instance-method-doAfterSuccess",
    "src/single.js~Single#doAfterSuccess",
    "method"
  ],
  [
    "src/single.js~single#doafterterminate",
    "class/src/single.js~Single.html#instance-method-doAfterTerminate",
    "src/single.js~Single#doAfterTerminate",
    "method"
  ],
  [
    "src/single.js~single#dofinally",
    "class/src/single.js~Single.html#instance-method-doFinally",
    "src/single.js~Single#doFinally",
    "method"
  ],
  [
    "src/single.js~single#doonabort",
    "class/src/single.js~Single.html#instance-method-doOnAbort",
    "src/single.js~Single#doOnAbort",
    "method"
  ],
  [
    "src/single.js~single#doonerror",
    "class/src/single.js~Single.html#instance-method-doOnError",
    "src/single.js~Single#doOnError",
    "method"
  ],
  [
    "src/single.js~single#doonevent",
    "class/src/single.js~Single.html#instance-method-doOnEvent",
    "src/single.js~Single#doOnEvent",
    "method"
  ],
  [
    "src/single.js~single#doonsubscribe",
    "class/src/single.js~Single.html#instance-method-doOnSubscribe",
    "src/single.js~Single#doOnSubscribe",
    "method"
  ],
  [
    "src/single.js~single#doonsuccess",
    "class/src/single.js~Single.html#instance-method-doOnSuccess",
    "src/single.js~Single#doOnSuccess",
    "method"
  ],
  [
    "src/single.js~single#doonterminate",
    "class/src/single.js~Single.html#instance-method-doOnTerminate",
    "src/single.js~Single#doOnTerminate",
    "method"
  ],
  [
    "src/single.js~single#flatmap",
    "class/src/single.js~Single.html#instance-method-flatMap",
    "src/single.js~Single#flatMap",
    "method"
  ],
  [
    "src/single.js~single#lift",
    "class/src/single.js~Single.html#instance-method-lift",
    "src/single.js~Single#lift",
    "method"
  ],
  [
    "src/single.js~single#map",
    "class/src/single.js~Single.html#instance-method-map",
    "src/single.js~Single#map",
    "method"
  ],
  [
    "src/single.js~single#onerrorresumenext",
    "class/src/single.js~Single.html#instance-method-onErrorResumeNext",
    "src/single.js~Single#onErrorResumeNext",
    "method"
  ],
  [
    "src/single.js~single#onerrorreturn",
    "class/src/single.js~Single.html#instance-method-onErrorReturn",
    "src/single.js~Single#onErrorReturn",
    "method"
  ],
  [
    "src/single.js~single#onerrorreturnitem",
    "class/src/single.js~Single.html#instance-method-onErrorReturnItem",
    "src/single.js~Single#onErrorReturnItem",
    "method"
  ],
  [
    "src/single.js~single#retry",
    "class/src/single.js~Single.html#instance-method-retry",
    "src/single.js~Single#retry",
    "method"
  ],
  [
    "src/single.js~single#subscribe",
    "class/src/single.js~Single.html#instance-method-subscribe",
    "src/single.js~Single#subscribe",
    "method"
  ],
  [
    "src/single.js~single#subscribewith",
    "class/src/single.js~Single.html#instance-method-subscribeWith",
    "src/single.js~Single#subscribeWith",
    "method"
  ],
  [
    "src/single.js~single#takeuntil",
    "class/src/single.js~Single.html#instance-method-takeUntil",
    "src/single.js~Single#takeUntil",
    "method"
  ],
  [
    "src/single.js~single#then",
    "class/src/single.js~Single.html#instance-method-then",
    "src/single.js~Single#then",
    "method"
  ],
  [
    "src/single.js~single#timeout",
    "class/src/single.js~Single.html#instance-method-timeout",
    "src/single.js~Single#timeout",
    "method"
  ],
  [
    "src/single.js~single#topromise",
    "class/src/single.js~Single.html#instance-method-toPromise",
    "src/single.js~Single#toPromise",
    "method"
  ],
  [
    "src/single.js~single#zipwith",
    "class/src/single.js~Single.html#instance-method-zipWith",
    "src/single.js~Single#zipWith",
    "method"
  ],
  [
    "src/single.js~single.amb",
    "class/src/single.js~Single.html#static-method-amb",
    "src/single.js~Single.amb",
    "method"
  ],
  [
    "src/single.js~single.create",
    "class/src/single.js~Single.html#static-method-create",
    "src/single.js~Single.create",
    "method"
  ],
  [
    "src/single.js~single.defer",
    "class/src/single.js~Single.html#static-method-defer",
    "src/single.js~Single.defer",
    "method"
  ],
  [
    "src/single.js~single.error",
    "class/src/single.js~Single.html#static-method-error",
    "src/single.js~Single.error",
    "method"
  ],
  [
    "src/single.js~single.fromcallable",
    "class/src/single.js~Single.html#static-method-fromCallable",
    "src/single.js~Single.fromCallable",
    "method"
  ],
  [
    "src/single.js~single.frompromise",
    "class/src/single.js~Single.html#static-method-fromPromise",
    "src/single.js~Single.fromPromise",
    "method"
  ],
  [
    "src/single.js~single.fromresolvable",
    "class/src/single.js~Single.html#static-method-fromResolvable",
    "src/single.js~Single.fromResolvable",
    "method"
  ],
  [
    "src/single.js~single.just",
    "class/src/single.js~Single.html#static-method-just",
    "src/single.js~Single.just",
    "method"
  ],
  [
    "src/single.js~single.merge",
    "class/src/single.js~Single.html#static-method-merge",
    "src/single.js~Single.merge",
    "method"
  ],
  [
    "src/single.js~single.never",
    "class/src/single.js~Single.html#static-method-never",
    "src/single.js~Single.never",
    "method"
  ],
  [
    "src/single.js~single.timer",
    "class/src/single.js~Single.html#static-method-timer",
    "src/single.js~Single.timer",
    "method"
  ],
  [
    "src/single.js~single.zip",
    "class/src/single.js~Single.html#static-method-zip",
    "src/single.js~Single.zip",
    "method"
  ],
  [
    "src/single.js~thennable",
    "https://promisesaplus.com/",
    "src/single.js~Thennable",
    "external"
  ],
  [
    "test/amb.js",
    "test-file/test/amb.js.html",
    "test/amb.js",
    "testFile"
  ],
  [
    "test/ambwith.js",
    "test-file/test/ambWith.js.html",
    "test/ambWith.js",
    "testFile"
  ],
  [
    "test/cache.js",
    "test-file/test/cache.js.html",
    "test/cache.js",
    "testFile"
  ],
  [
    "test/catch.js",
    "test-file/test/catch.js.html",
    "test/catch.js",
    "testFile"
  ],
  [
    "test/compose.js",
    "test-file/test/compose.js.html",
    "test/compose.js",
    "testFile"
  ],
  [
    "test/contains.js",
    "test-file/test/contains.js.html",
    "test/contains.js",
    "testFile"
  ],
  [
    "test/create.js",
    "test-file/test/create.js.html",
    "test/create.js",
    "testFile"
  ],
  [
    "test/defer.js",
    "test-file/test/defer.js.html",
    "test/defer.js",
    "testFile"
  ],
  [
    "test/delay.js",
    "test-file/test/delay.js.html",
    "test/delay.js",
    "testFile"
  ],
  [
    "test/delaysubscription.js",
    "test-file/test/delaySubscription.js.html",
    "test/delaySubscription.js",
    "testFile"
  ],
  [
    "test/delayuntil.js",
    "test-file/test/delayUntil.js.html",
    "test/delayUntil.js",
    "testFile"
  ],
  [
    "test/doaftersuccess.js",
    "test-file/test/doAfterSuccess.js.html",
    "test/doAfterSuccess.js",
    "testFile"
  ],
  [
    "test/doafterterminate.js",
    "test-file/test/doAfterTerminate.js.html",
    "test/doAfterTerminate.js",
    "testFile"
  ],
  [
    "test/dofinally.js",
    "test-file/test/doFinally.js.html",
    "test/doFinally.js",
    "testFile"
  ],
  [
    "test/doonabort.js",
    "test-file/test/doOnAbort.js.html",
    "test/doOnAbort.js",
    "testFile"
  ],
  [
    "test/doonerror.js",
    "test-file/test/doOnError.js.html",
    "test/doOnError.js",
    "testFile"
  ],
  [
    "test/doonevent.js",
    "test-file/test/doOnEvent.js.html",
    "test/doOnEvent.js",
    "testFile"
  ],
  [
    "test/doonsubscribe.js",
    "test-file/test/doOnSubscribe.js.html",
    "test/doOnSubscribe.js",
    "testFile"
  ],
  [
    "test/doonsuccess.js",
    "test-file/test/doOnSuccess.js.html",
    "test/doOnSuccess.js",
    "testFile"
  ],
  [
    "test/doonterminate.js",
    "test-file/test/doOnTerminate.js.html",
    "test/doOnTerminate.js",
    "testFile"
  ],
  [
    "test/error.js",
    "test-file/test/error.js.html",
    "test/error.js",
    "testFile"
  ],
  [
    "test/flatmap.js",
    "test-file/test/flatMap.js.html",
    "test/flatMap.js",
    "testFile"
  ],
  [
    "test/fromcallable.js",
    "test-file/test/fromCallable.js.html",
    "test/fromCallable.js",
    "testFile"
  ],
  [
    "test/frompromise.js",
    "test-file/test/fromPromise.js.html",
    "test/fromPromise.js",
    "testFile"
  ],
  [
    "test/fromresolvable.js",
    "test-file/test/fromResolvable.js.html",
    "test/fromResolvable.js",
    "testFile"
  ],
  [
    "test/just.js",
    "test-file/test/just.js.html",
    "test/just.js",
    "testFile"
  ],
  [
    "test/lift.js",
    "test-file/test/lift.js.html",
    "test/lift.js",
    "testFile"
  ],
  [
    "test/map.js",
    "test-file/test/map.js.html",
    "test/map.js",
    "testFile"
  ],
  [
    "test/merge.js",
    "test-file/test/merge.js.html",
    "test/merge.js",
    "testFile"
  ],
  [
    "test/never.js",
    "test-file/test/never.js.html",
    "test/never.js",
    "testFile"
  ],
  [
    "test/onerrorresumenext.js",
    "test-file/test/onErrorResumeNext.js.html",
    "test/onErrorResumeNext.js",
    "testFile"
  ],
  [
    "test/onerrorreturn.js",
    "test-file/test/onErrorReturn.js.html",
    "test/onErrorReturn.js",
    "testFile"
  ],
  [
    "test/onerrorreturnitem.js",
    "test-file/test/onErrorReturnItem.js.html",
    "test/onErrorReturnItem.js",
    "testFile"
  ],
  [
    "test/retry.js",
    "test-file/test/retry.js.html",
    "test/retry.js",
    "testFile"
  ],
  [
    "test/takeuntil.js",
    "test-file/test/takeUntil.js.html",
    "test/takeUntil.js",
    "testFile"
  ],
  [
    "test/then.js",
    "test-file/test/then.js.html",
    "test/then.js",
    "testFile"
  ],
  [
    "test/timeout.js",
    "test-file/test/timeout.js.html",
    "test/timeout.js",
    "testFile"
  ],
  [
    "test/timer.js",
    "test-file/test/timer.js.html",
    "test/timer.js",
    "testFile"
  ],
  [
    "test/topromise.js",
    "test-file/test/toPromise.js.html",
    "test/toPromise.js",
    "testFile"
  ],
  [
    "test/zip.js",
    "test-file/test/zip.js.html",
    "test/zip.js",
    "testFile"
  ],
  [
    "test/zipwith.js",
    "test-file/test/zipWith.js.html",
    "test/zipWith.js",
    "testFile"
  ]
]