window.esdocSearchIndex = [
  [
    "parexgram-js/src/alternation.js~alternation",
    "class/src/alternation.js~Alternation.html",
    "<span>Alternation</span> <span class=\"search-result-import-path\">parexgram-js/src/alternation.js</span>",
    "class"
  ],
  [
    "parexgram-js/src/charset.js~charset",
    "class/src/charset.js~CharSet.html",
    "<span>CharSet</span> <span class=\"search-result-import-path\">parexgram-js/src/charset.js</span>",
    "class"
  ],
  [
    "parexgram-js/src/feed.js~feed",
    "class/src/feed.js~Feed.html",
    "<span>Feed</span> <span class=\"search-result-import-path\">parexgram-js/src/feed.js</span>",
    "class"
  ],
  [
    "parexgram-js/src/matcher.js~matcher",
    "class/src/matcher.js~Matcher.html",
    "<span>Matcher</span> <span class=\"search-result-import-path\">parexgram-js/src/matcher.js</span>",
    "class"
  ],
  [
    "parexgram-js/src/quantifier.js~quantifier",
    "class/src/quantifier.js~Quantifier.html",
    "<span>Quantifier</span> <span class=\"search-result-import-path\">parexgram-js/src/quantifier.js</span>",
    "class"
  ],
  [
    "parexgram-js/src/range.js~range",
    "class/src/range.js~Range.html",
    "<span>Range</span> <span class=\"search-result-import-path\">parexgram-js/src/range.js</span>",
    "class"
  ],
  [
    "parexgram-js/src/sequence.js~sequence",
    "class/src/sequence.js~Sequence.html",
    "<span>Sequence</span> <span class=\"search-result-import-path\">parexgram-js/src/sequence.js</span>",
    "class"
  ],
  [
    "",
    "test-file/test/alternation.js.html#lineNumber8",
    "Alternation",
    "test"
  ],
  [
    "",
    "test-file/test/alternation.js.html#lineNumber12",
    "Alternation #parse",
    "test"
  ],
  [
    "",
    "test-file/test/alternation.js.html#lineNumber16",
    "Alternation #parse should return an Array if a matcher returns an Array",
    "test"
  ],
  [
    "",
    "test-file/test/alternation.js.html#lineNumber31",
    "Alternation #parse should return an String if a matcher returns a String",
    "test"
  ],
  [
    "",
    "test-file/test/alternation.js.html#lineNumber68",
    "Alternation #parse should return the other matches if the previous matches fails",
    "test"
  ],
  [
    "",
    "test-file/test/alternation.js.html#lineNumber42",
    "Alternation #parse should return undefined if there are no matchers",
    "test"
  ],
  [
    "",
    "test-file/test/alternation.js.html#lineNumber53",
    "Alternation #parse should return undefined if there are no matchers",
    "test"
  ],
  [
    "",
    "test-file/test/charset.js.html#lineNumber5",
    "CharSet",
    "test"
  ],
  [
    "",
    "test-file/test/charset.js.html#lineNumber9",
    "CharSet #parse",
    "test"
  ],
  [
    "",
    "test-file/test/charset.js.html#lineNumber13",
    "CharSet #parse should return a String",
    "test"
  ],
  [
    "",
    "test-file/test/charset.js.html#lineNumber22",
    "CharSet #parse should return a String equal to the CharSet if successful",
    "test"
  ],
  [
    "",
    "test-file/test/charset.js.html#lineNumber40",
    "CharSet #parse should return a undefined if a non-Feed is received",
    "test"
  ],
  [
    "",
    "test-file/test/charset.js.html#lineNumber31",
    "CharSet #parse should return a undefined if unsuccessful",
    "test"
  ],
  [
    "",
    "test-file/test/feed.js.html#lineNumber8",
    "Feed",
    "test"
  ],
  [
    "",
    "test-file/test/feed.js.html#lineNumber39",
    "Feed #eat",
    "test"
  ],
  [
    "",
    "test-file/test/feed.js.html#lineNumber43",
    "Feed #eat should return a Boolean",
    "test"
  ],
  [
    "",
    "test-file/test/feed.js.html#lineNumber65",
    "Feed #eat should return false if the given string is not a prefix of the Feed.",
    "test"
  ],
  [
    "",
    "test-file/test/feed.js.html#lineNumber54",
    "Feed #eat should return true if the given string is a prefix of the Feed.",
    "test"
  ],
  [
    "",
    "test-file/test/feed.js.html#lineNumber12",
    "Feed #peek",
    "test"
  ],
  [
    "",
    "test-file/test/feed.js.html#lineNumber16",
    "Feed #peek should return a String",
    "test"
  ],
  [
    "",
    "test-file/test/feed.js.html#lineNumber27",
    "Feed #peek should return the correct string",
    "test"
  ],
  [
    "",
    "test-file/test/feed.js.html#lineNumber77",
    "Feed #revert",
    "test"
  ],
  [
    "",
    "test-file/test/feed.js.html#lineNumber81",
    "Feed #revert should revert successfully.",
    "test"
  ],
  [
    "",
    "test-file/test/feed.js.html#lineNumber94",
    "Feed #size",
    "test"
  ],
  [
    "",
    "test-file/test/feed.js.html#lineNumber98",
    "Feed #size should return a Number",
    "test"
  ],
  [
    "",
    "test-file/test/feed.js.html#lineNumber122",
    "Feed #size should return the correct size if #eat is not called.",
    "test"
  ],
  [
    "",
    "test-file/test/feed.js.html#lineNumber109",
    "Feed #size should return the size equal to the received string of the Feed, if #eat is not called.",
    "test"
  ],
  [
    "",
    "test-file/test/quantifier.js.html#lineNumber8",
    "Quantifier",
    "test"
  ],
  [
    "",
    "test-file/test/quantifier.js.html#lineNumber12",
    "Quantifier #parse",
    "test"
  ],
  [
    "",
    "test-file/test/quantifier.js.html#lineNumber16",
    "Quantifier #parse should return a undefined if a non-Feed is received",
    "test"
  ],
  [
    "",
    "test-file/test/quantifier.js.html#lineNumber31",
    "Quantifier #parse should return a undefined if there is no matcher",
    "test"
  ],
  [
    "",
    "test-file/test/quantifier.js.html#lineNumber45",
    "Quantifier #parse should return an empty array if Quantifier(match, 0) matches no result",
    "test"
  ],
  [
    "",
    "test-file/test/quantifier.js.html#lineNumber37",
    "Quantifier #parse should return the correct sequence",
    "test"
  ],
  [
    "",
    "test-file/test/quantifier.js.html#lineNumber52",
    "Quantifier #parse should return undefiend if the required matches is not met",
    "test"
  ],
  [
    "",
    "test-file/test/range.js.html#lineNumber5",
    "Range",
    "test"
  ],
  [
    "",
    "test-file/test/range.js.html#lineNumber6",
    "Range #parse",
    "test"
  ],
  [
    "",
    "test-file/test/range.js.html#lineNumber7",
    "Range #parse should return a String",
    "test"
  ],
  [
    "",
    "test-file/test/range.js.html#lineNumber16",
    "Range #parse should return a String equal to the CharSet if successful",
    "test"
  ],
  [
    "",
    "test-file/test/range.js.html#lineNumber34",
    "Range #parse should return a undefined if a non-Feed is received",
    "test"
  ],
  [
    "",
    "test-file/test/range.js.html#lineNumber25",
    "Range #parse should return a undefined if unsuccessful",
    "test"
  ],
  [
    "",
    "test-file/test/sequence.js.html#lineNumber6",
    "Sequence",
    "test"
  ],
  [
    "",
    "test-file/test/sequence.js.html#lineNumber10",
    "Sequence #parse",
    "test"
  ],
  [
    "",
    "test-file/test/sequence.js.html#lineNumber14",
    "Sequence #parse should return an Array",
    "test"
  ],
  [
    "",
    "test-file/test/sequence.js.html#lineNumber23",
    "Sequence #parse should return an Array equal to the Matchers if successful",
    "test"
  ],
  [
    "",
    "test-file/test/sequence.js.html#lineNumber36",
    "Sequence #parse should return undefined if no matchers were passed",
    "test"
  ],
  [
    "",
    "test-file/test/sequence.js.html#lineNumber46",
    "Sequence #parse should return undefined if one of the matchers fails",
    "test"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/alternation.js",
    "file/src/alternation.js.html",
    "src/alternation.js",
    "file"
  ],
  [
    "src/alternation.js~alternation#constructor",
    "class/src/alternation.js~Alternation.html#instance-constructor-constructor",
    "src/alternation.js~Alternation#constructor",
    "method"
  ],
  [
    "src/alternation.js~alternation#matchers",
    "class/src/alternation.js~Alternation.html#instance-member-matchers",
    "src/alternation.js~Alternation#matchers",
    "member"
  ],
  [
    "src/alternation.js~alternation#parse",
    "class/src/alternation.js~Alternation.html#instance-method-parse",
    "src/alternation.js~Alternation#parse",
    "method"
  ],
  [
    "src/charset.js",
    "file/src/charset.js.html",
    "src/charset.js",
    "file"
  ],
  [
    "src/charset.js~charset#constructor",
    "class/src/charset.js~CharSet.html#instance-constructor-constructor",
    "src/charset.js~CharSet#constructor",
    "method"
  ],
  [
    "src/charset.js~charset#parse",
    "class/src/charset.js~CharSet.html#instance-method-parse",
    "src/charset.js~CharSet#parse",
    "method"
  ],
  [
    "src/feed.js",
    "file/src/feed.js.html",
    "src/feed.js",
    "file"
  ],
  [
    "src/feed.js~feed#constructor",
    "class/src/feed.js~Feed.html#instance-constructor-constructor",
    "src/feed.js~Feed#constructor",
    "method"
  ],
  [
    "src/feed.js~feed#eat",
    "class/src/feed.js~Feed.html#instance-method-eat",
    "src/feed.js~Feed#eat",
    "method"
  ],
  [
    "src/feed.js~feed#peek",
    "class/src/feed.js~Feed.html#instance-method-peek",
    "src/feed.js~Feed#peek",
    "method"
  ],
  [
    "src/feed.js~feed#revert",
    "class/src/feed.js~Feed.html#instance-method-revert",
    "src/feed.js~Feed#revert",
    "method"
  ],
  [
    "src/feed.js~feed#size",
    "class/src/feed.js~Feed.html#instance-get-size",
    "src/feed.js~Feed#size",
    "member"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/matcher.js",
    "file/src/matcher.js.html",
    "src/matcher.js",
    "file"
  ],
  [
    "src/matcher.js~matcher#parse",
    "class/src/matcher.js~Matcher.html#instance-method-parse",
    "src/matcher.js~Matcher#parse",
    "method"
  ],
  [
    "src/quantifier.js",
    "file/src/quantifier.js.html",
    "src/quantifier.js",
    "file"
  ],
  [
    "src/quantifier.js~quantifier#constructor",
    "class/src/quantifier.js~Quantifier.html#instance-constructor-constructor",
    "src/quantifier.js~Quantifier#constructor",
    "method"
  ],
  [
    "src/quantifier.js~quantifier#parse",
    "class/src/quantifier.js~Quantifier.html#instance-method-parse",
    "src/quantifier.js~Quantifier#parse",
    "method"
  ],
  [
    "src/range.js",
    "file/src/range.js.html",
    "src/range.js",
    "file"
  ],
  [
    "src/range.js~range#constructor",
    "class/src/range.js~Range.html#instance-constructor-constructor",
    "src/range.js~Range#constructor",
    "method"
  ],
  [
    "src/range.js~range#parse",
    "class/src/range.js~Range.html#instance-method-parse",
    "src/range.js~Range#parse",
    "method"
  ],
  [
    "src/sequence.js",
    "file/src/sequence.js.html",
    "src/sequence.js",
    "file"
  ],
  [
    "src/sequence.js~sequence#constructor",
    "class/src/sequence.js~Sequence.html#instance-constructor-constructor",
    "src/sequence.js~Sequence#constructor",
    "method"
  ],
  [
    "src/sequence.js~sequence#matchers",
    "class/src/sequence.js~Sequence.html#instance-member-matchers",
    "src/sequence.js~Sequence#matchers",
    "member"
  ],
  [
    "src/sequence.js~sequence#parse",
    "class/src/sequence.js~Sequence.html#instance-method-parse",
    "src/sequence.js~Sequence#parse",
    "method"
  ],
  [
    "src/utils.js",
    "file/src/utils.js.html",
    "src/utils.js",
    "file"
  ],
  [
    "test/alternation.js",
    "test-file/test/alternation.js.html",
    "test/alternation.js",
    "testFile"
  ],
  [
    "test/charset.js",
    "test-file/test/charset.js.html",
    "test/charset.js",
    "testFile"
  ],
  [
    "test/feed.js",
    "test-file/test/feed.js.html",
    "test/feed.js",
    "testFile"
  ],
  [
    "test/quantifier.js",
    "test-file/test/quantifier.js.html",
    "test/quantifier.js",
    "testFile"
  ],
  [
    "test/range.js",
    "test-file/test/range.js.html",
    "test/range.js",
    "testFile"
  ],
  [
    "test/sequence.js",
    "test-file/test/sequence.js.html",
    "test/sequence.js",
    "testFile"
  ]
]