window.esdocSearchIndex = [
  [
    "",
    "test-file/test/amb.js.html#lineNumber8",
    "#amb",
    "test"
  ],
  [
    "",
    "test-file/test/amb.js.html#lineNumber12",
    "#amb should create a Completable",
    "test"
  ],
  [
    "",
    "test-file/test/amb.js.html#lineNumber19",
    "#amb should signal complete from the earliest source.",
    "test"
  ],
  [
    "",
    "test-file/test/amb.js.html#lineNumber29",
    "#amb should signal error from the earliest source.",
    "test"
  ],
  [
    "",
    "test-file/test/amb.js.html#lineNumber49",
    "#amb should signal error if given argument is not Iterable",
    "test"
  ],
  [
    "",
    "test-file/test/amb.js.html#lineNumber39",
    "#amb should signal error if one of the source is non-Completable.",
    "test"
  ],
  [
    "",
    "test-file/test/ambWith.js.html#lineNumber8",
    "#ambWith",
    "test"
  ],
  [
    "",
    "test-file/test/ambWith.js.html#lineNumber12",
    "#ambWith should create a Completable",
    "test"
  ],
  [
    "",
    "test-file/test/ambWith.js.html#lineNumber19",
    "#ambWith should return the same instance if the other value is non-Completable",
    "test"
  ],
  [
    "",
    "test-file/test/ambWith.js.html#lineNumber37",
    "#ambWith should signal complete from the other (if earlier).",
    "test"
  ],
  [
    "",
    "test-file/test/ambWith.js.html#lineNumber27",
    "#ambWith should signal complete from the source (if earlier)",
    "test"
  ],
  [
    "",
    "test-file/test/ambWith.js.html#lineNumber57",
    "#ambWith should signal error from the other (if earlier).",
    "test"
  ],
  [
    "",
    "test-file/test/ambWith.js.html#lineNumber47",
    "#ambWith should signal error from the source (if earlier).",
    "test"
  ],
  [
    "",
    "test-file/test/andThen.js.html#lineNumber8",
    "#andThen",
    "test"
  ],
  [
    "",
    "test-file/test/andThen.js.html#lineNumber12",
    "#andThen should create a Completable",
    "test"
  ],
  [
    "",
    "test-file/test/andThen.js.html#lineNumber41",
    "#andThen should error with the other Completable if the other throws an error",
    "test"
  ],
  [
    "",
    "test-file/test/andThen.js.html#lineNumber54",
    "#andThen should error with the source Completable if the source throws an error",
    "test"
  ],
  [
    "",
    "test-file/test/andThen.js.html#lineNumber20",
    "#andThen should return the same instance if the given completable is a non-Completable",
    "test"
  ],
  [
    "",
    "test-file/test/andThen.js.html#lineNumber28",
    "#andThen should start with the source Completable.",
    "test"
  ],
  [
    "",
    "test-file/test/cache.js.html#lineNumber8",
    "#cache",
    "test"
  ],
  [
    "",
    "test-file/test/cache.js.html#lineNumber12",
    "#cache should create a Completable",
    "test"
  ],
  [
    "",
    "test-file/test/cache.js.html#lineNumber19",
    "#cache should signal cached complete",
    "test"
  ],
  [
    "",
    "test-file/test/cache.js.html#lineNumber39",
    "#cache should signal cached error value",
    "test"
  ],
  [
    "",
    "test-file/test/catch.js.html#lineNumber8",
    "#catch",
    "test"
  ],
  [
    "",
    "test-file/test/catch.js.html#lineNumber12",
    "#catch should create a Promise",
    "test"
  ],
  [
    "",
    "test-file/test/compose.js.html#lineNumber8",
    "#compose",
    "test"
  ],
  [
    "",
    "test-file/test/compose.js.html#lineNumber29",
    "#compose should correctly signal the composed Completable",
    "test"
  ],
  [
    "",
    "test-file/test/compose.js.html#lineNumber21",
    "#compose should return a Completable from the transformer",
    "test"
  ],
  [
    "",
    "test-file/test/compose.js.html#lineNumber12",
    "#compose should return the same instance if no function is provided",
    "test"
  ],
  [
    "",
    "test-file/test/compose.js.html#lineNumber40",
    "#compose should signal error if the transformer function returned a non-Completable",
    "test"
  ],
  [
    "",
    "test-file/test/concat.js.html#lineNumber8",
    "#concat",
    "test"
  ],
  [
    "",
    "test-file/test/concat.js.html#lineNumber12",
    "#concat should create a Completable",
    "test"
  ],
  [
    "",
    "test-file/test/concat.js.html#lineNumber33",
    "#concat should signal error from the first",
    "test"
  ],
  [
    "",
    "test-file/test/concat.js.html#lineNumber53",
    "#concat should signal error if given argument is not Iterable",
    "test"
  ],
  [
    "",
    "test-file/test/concat.js.html#lineNumber43",
    "#concat should signal error if one of the source is non-Completable.",
    "test"
  ],
  [
    "",
    "test-file/test/concat.js.html#lineNumber19",
    "#concat should start with the from left to right",
    "test"
  ],
  [
    "",
    "test-file/test/concatWith.js.html#lineNumber8",
    "#concatWith",
    "test"
  ],
  [
    "",
    "test-file/test/concatWith.js.html#lineNumber12",
    "#concatWith should create a Completable",
    "test"
  ],
  [
    "",
    "test-file/test/concatWith.js.html#lineNumber41",
    "#concatWith should error with the other Completable if the other throws an error",
    "test"
  ],
  [
    "",
    "test-file/test/concatWith.js.html#lineNumber54",
    "#concatWith should error with the source Completable if the source throws an error",
    "test"
  ],
  [
    "",
    "test-file/test/concatWith.js.html#lineNumber20",
    "#concatWith should return the same instance if the given completable is a non-Completable",
    "test"
  ],
  [
    "",
    "test-file/test/concatWith.js.html#lineNumber28",
    "#concatWith should start with the source Completable.",
    "test"
  ],
  [
    "",
    "test-file/test/create.js.html#lineNumber8",
    "#create",
    "test"
  ],
  [
    "",
    "test-file/test/create.js.html#lineNumber53",
    "#create should be aborted successfully if emitter is aborted before any signal.",
    "test"
  ],
  [
    "",
    "test-file/test/create.js.html#lineNumber12",
    "#create should create a Completable",
    "test"
  ],
  [
    "",
    "test-file/test/create.js.html#lineNumber70",
    "#create should signal error if subscriber throws an error.",
    "test"
  ],
  [
    "",
    "test-file/test/create.js.html#lineNumber20",
    "#create should signal error if the create received a non-function",
    "test"
  ],
  [
    "",
    "test-file/test/create.js.html#lineNumber31",
    "#create should signal error if the emitter signals complete.",
    "test"
  ],
  [
    "",
    "test-file/test/create.js.html#lineNumber42",
    "#create should signal error if the emitter signals error with undefined value.",
    "test"
  ],
  [
    "",
    "test-file/test/defer.js.html#lineNumber8",
    "#defer",
    "test"
  ],
  [
    "",
    "test-file/test/defer.js.html#lineNumber12",
    "#defer should create a Completable",
    "test"
  ],
  [
    "",
    "test-file/test/defer.js.html#lineNumber31",
    "#defer should signal error if callable returns a non-Completable",
    "test"
  ],
  [
    "",
    "test-file/test/defer.js.html#lineNumber42",
    "#defer should signal error if callable throws an error",
    "test"
  ],
  [
    "",
    "test-file/test/defer.js.html#lineNumber20",
    "#defer should succeed with the given value.",
    "test"
  ],
  [
    "",
    "test-file/test/delay.js.html#lineNumber8",
    "#delay",
    "test"
  ],
  [
    "",
    "test-file/test/delay.js.html#lineNumber12",
    "#delay should create a Completable",
    "test"
  ],
  [
    "",
    "test-file/test/delay.js.html#lineNumber47",
    "#delay should not signal complete if aborted.",
    "test"
  ],
  [
    "",
    "test-file/test/delay.js.html#lineNumber62",
    "#delay should not signal error if aborted.",
    "test"
  ],
  [
    "",
    "test-file/test/delay.js.html#lineNumber19",
    "#delay should return the same instance if the amount is not a number.",
    "test"
  ],
  [
    "",
    "test-file/test/delay.js.html#lineNumber27",
    "#delay should signal complete.",
    "test"
  ],
  [
    "",
    "test-file/test/delay.js.html#lineNumber37",
    "#delay should signal error with the given value.",
    "test"
  ],
  [
    "",
    "test-file/test/delaySubscription.js.html#lineNumber8",
    "#delaySubscription",
    "test"
  ],
  [
    "",
    "test-file/test/delaySubscription.js.html#lineNumber12",
    "#delaySubscription should create a Completable",
    "test"
  ],
  [
    "",
    "test-file/test/delaySubscription.js.html#lineNumber47",
    "#delaySubscription should not signal complete if aborted.",
    "test"
  ],
  [
    "",
    "test-file/test/delaySubscription.js.html#lineNumber62",
    "#delaySubscription should not signal error if aborted.",
    "test"
  ],
  [
    "",
    "test-file/test/delaySubscription.js.html#lineNumber19",
    "#delaySubscription should return the same instance if the amount is not a number.",
    "test"
  ],
  [
    "",
    "test-file/test/delaySubscription.js.html#lineNumber27",
    "#delaySubscription should signal complete.",
    "test"
  ],
  [
    "",
    "test-file/test/delaySubscription.js.html#lineNumber37",
    "#delaySubscription should signal error with the given value.",
    "test"
  ],
  [
    "",
    "test-file/test/doAfterTerminate.js.html#lineNumber8",
    "#doAfterTerminate",
    "test"
  ],
  [
    "",
    "test-file/test/doAfterTerminate.js.html#lineNumber27",
    "#doAfterTerminate should call the given function after complete.",
    "test"
  ],
  [
    "",
    "test-file/test/doAfterTerminate.js.html#lineNumber39",
    "#doAfterTerminate should call the given function after error.",
    "test"
  ],
  [
    "",
    "test-file/test/doAfterTerminate.js.html#lineNumber12",
    "#doAfterTerminate should create a Completable",
    "test"
  ],
  [
    "",
    "test-file/test/doAfterTerminate.js.html#lineNumber19",
    "#doAfterTerminate should return the same instance if the method received a non-function parameter.",
    "test"
  ],
  [
    "",
    "test-file/test/doFinally.js.html#lineNumber8",
    "#doFinally",
    "test"
  ],
  [
    "",
    "test-file/test/doFinally.js.html#lineNumber27",
    "#doFinally should call the given function after complete.",
    "test"
  ],
  [
    "",
    "test-file/test/doFinally.js.html#lineNumber39",
    "#doFinally should call the given function after error.",
    "test"
  ],
  [
    "",
    "test-file/test/doFinally.js.html#lineNumber51",
    "#doFinally should call the given function on dispose.",
    "test"
  ],
  [
    "",
    "test-file/test/doFinally.js.html#lineNumber12",
    "#doFinally should create a Completable",
    "test"
  ],
  [
    "",
    "test-file/test/doFinally.js.html#lineNumber19",
    "#doFinally should return the same instance if the method received a non-function parameter.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnAbort.js.html#lineNumber8",
    "#doOnAbort",
    "test"
  ],
  [
    "",
    "test-file/test/doOnAbort.js.html#lineNumber55",
    "#doOnAbort should call the given function on abort.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnAbort.js.html#lineNumber12",
    "#doOnAbort should create a Completable",
    "test"
  ],
  [
    "",
    "test-file/test/doOnAbort.js.html#lineNumber19",
    "#doOnAbort should return the same instance if the method received a non-function parameter.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnAbort.js.html#lineNumber27",
    "#doOnAbort should signal the complete then fire abort callback.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnAbort.js.html#lineNumber41",
    "#doOnAbort should signal the error value then fire abort callback.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnComplete.js.html#lineNumber8",
    "#doOnComplete",
    "test"
  ],
  [
    "",
    "test-file/test/doOnComplete.js.html#lineNumber27",
    "#doOnComplete should call the given function on error.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnComplete.js.html#lineNumber12",
    "#doOnComplete should create a Completable",
    "test"
  ],
  [
    "",
    "test-file/test/doOnComplete.js.html#lineNumber19",
    "#doOnComplete should return the same instance if the method received a non-function parameter.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnError.js.html#lineNumber8",
    "#doOnError",
    "test"
  ],
  [
    "",
    "test-file/test/doOnError.js.html#lineNumber27",
    "#doOnError should call the given function on error.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnError.js.html#lineNumber12",
    "#doOnError should create a Completable",
    "test"
  ],
  [
    "",
    "test-file/test/doOnError.js.html#lineNumber19",
    "#doOnError should return the same instance if the method received a non-function parameter.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnEvent.js.html#lineNumber8",
    "#doOnEvent",
    "test"
  ],
  [
    "",
    "test-file/test/doOnEvent.js.html#lineNumber27",
    "#doOnEvent should call the given function on complete.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnEvent.js.html#lineNumber39",
    "#doOnEvent should call the given function on error.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnEvent.js.html#lineNumber12",
    "#doOnEvent should create a Completable",
    "test"
  ],
  [
    "",
    "test-file/test/doOnEvent.js.html#lineNumber19",
    "#doOnEvent should return the same instance if the method received a non-function parameter.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnSubscribe.js.html#lineNumber8",
    "#doOnSubscribe",
    "test"
  ],
  [
    "",
    "test-file/test/doOnSubscribe.js.html#lineNumber27",
    "#doOnSubscribe should be called before actual subscription.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnSubscribe.js.html#lineNumber12",
    "#doOnSubscribe should create a Completable",
    "test"
  ],
  [
    "",
    "test-file/test/doOnSubscribe.js.html#lineNumber19",
    "#doOnSubscribe should return the same instance if no function is passed",
    "test"
  ],
  [
    "",
    "test-file/test/doOnTerminate.js.html#lineNumber8",
    "#doOnTerminate",
    "test"
  ],
  [
    "",
    "test-file/test/doOnTerminate.js.html#lineNumber27",
    "#doOnTerminate should call the given function on complete.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnTerminate.js.html#lineNumber39",
    "#doOnTerminate should call the given function on error.",
    "test"
  ],
  [
    "",
    "test-file/test/doOnTerminate.js.html#lineNumber12",
    "#doOnTerminate should create a Completable",
    "test"
  ],
  [
    "",
    "test-file/test/doOnTerminate.js.html#lineNumber19",
    "#doOnTerminate should return the same instance if the method received a non-function parameter.",
    "test"
  ],
  [
    "",
    "test-file/test/error.js.html#lineNumber8",
    "#error",
    "test"
  ],
  [
    "",
    "test-file/test/error.js.html#lineNumber12",
    "#error should create a Completable",
    "test"
  ],
  [
    "",
    "test-file/test/error.js.html#lineNumber53",
    "#error should error if the callable throws an error.",
    "test"
  ],
  [
    "",
    "test-file/test/error.js.html#lineNumber42",
    "#error should error with the a message if the callable returned undefined",
    "test"
  ],
  [
    "",
    "test-file/test/error.js.html#lineNumber31",
    "#error should error with the a message if the given value is undefined",
    "test"
  ],
  [
    "",
    "test-file/test/error.js.html#lineNumber20",
    "#error should error with the given value.",
    "test"
  ],
  [
    "",
    "test-file/test/fromCallable.js.html#lineNumber8",
    "#fromCallable",
    "test"
  ],
  [
    "",
    "test-file/test/fromCallable.js.html#lineNumber12",
    "#fromCallable should create a Completable",
    "test"
  ],
  [
    "",
    "test-file/test/fromCallable.js.html#lineNumber54",
    "#fromCallable should signal an error if the callable is not a function",
    "test"
  ],
  [
    "",
    "test-file/test/fromCallable.js.html#lineNumber43",
    "#fromCallable should signal an error if the callable returns a rejected Promise.",
    "test"
  ],
  [
    "",
    "test-file/test/fromCallable.js.html#lineNumber30",
    "#fromCallable should signal an error if the callable throws an error.",
    "test"
  ],
  [
    "",
    "test-file/test/fromCallable.js.html#lineNumber19",
    "#fromCallable should succeed with the given value.",
    "test"
  ],
  [
    "",
    "test-file/test/fromPromise.js.html#lineNumber8",
    "#fromPromise",
    "test"
  ],
  [
    "",
    "test-file/test/fromPromise.js.html#lineNumber12",
    "#fromPromise should create a Completable",
    "test"
  ],
  [
    "",
    "test-file/test/fromPromise.js.html#lineNumber30",
    "#fromPromise should signal error if the given value is not Promise like",
    "test"
  ],
  [
    "",
    "test-file/test/fromPromise.js.html#lineNumber19",
    "#fromPromise should succeed with the given value.",
    "test"
  ],
  [
    "",
    "test-file/test/fromResolvable.js.html#lineNumber8",
    "#fromResolvable",
    "test"
  ],
  [
    "",
    "test-file/test/fromResolvable.js.html#lineNumber12",
    "#fromResolvable should create a Completable",
    "test"
  ],
  [
    "",
    "test-file/test/fromResolvable.js.html#lineNumber30",
    "#fromResolvable should signal error if the given value is not a function",
    "test"
  ],
  [
    "",
    "test-file/test/fromResolvable.js.html#lineNumber19",
    "#fromResolvable should succeed with the given value.",
    "test"
  ],
  [
    "",
    "test-file/test/lift.js.html#lineNumber7",
    "#lift",
    "test"
  ],
  [
    "",
    "test-file/test/lift.js.html#lineNumber11",
    "#lift should return the same instance if no function is provided",
    "test"
  ],
  [
    "",
    "test-file/test/lift.js.html#lineNumber20",
    "#lift should signal an error if the lift operator returned a non-Observer",
    "test"
  ],
  [
    "",
    "test-file/test/lift.js.html#lineNumber31",
    "#lift should subscribe successfully",
    "test"
  ],
  [
    "",
    "test-file/test/merge.js.html#lineNumber8",
    "#merge",
    "test"
  ],
  [
    "",
    "test-file/test/merge.js.html#lineNumber12",
    "#merge should create a Completable",
    "test"
  ],
  [
    "",
    "test-file/test/merge.js.html#lineNumber33",
    "#merge should signal error from the first",
    "test"
  ],
  [
    "",
    "test-file/test/merge.js.html#lineNumber53",
    "#merge should signal error if given argument is not Iterable",
    "test"
  ],
  [
    "",
    "test-file/test/merge.js.html#lineNumber43",
    "#merge should signal error if one of the source is non-Completable.",
    "test"
  ],
  [
    "",
    "test-file/test/merge.js.html#lineNumber19",
    "#merge should start with the from the first completion to the last completion",
    "test"
  ],
  [
    "",
    "test-file/test/mergeWith.js.html#lineNumber8",
    "#mergeWith",
    "test"
  ],
  [
    "",
    "test-file/test/mergeWith.js.html#lineNumber12",
    "#mergeWith should create a Completable",
    "test"
  ],
  [
    "",
    "test-file/test/mergeWith.js.html#lineNumber41",
    "#mergeWith should error with the other Completable if the other throws an error",
    "test"
  ],
  [
    "",
    "test-file/test/mergeWith.js.html#lineNumber54",
    "#mergeWith should error with the source Completable if the source throws an error",
    "test"
  ],
  [
    "",
    "test-file/test/mergeWith.js.html#lineNumber20",
    "#mergeWith should return the same instance if the given completable is a non-Completable",
    "test"
  ],
  [
    "",
    "test-file/test/mergeWith.js.html#lineNumber28",
    "#mergeWith should start with the other Completable.",
    "test"
  ],
  [
    "",
    "test-file/test/never.js.html#lineNumber8",
    "#never",
    "test"
  ],
  [
    "",
    "test-file/test/never.js.html#lineNumber12",
    "#never should create a Completable",
    "test"
  ],
  [
    "",
    "test-file/test/never.js.html#lineNumber19",
    "#never should not signal.",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorComplete.js.html#lineNumber8",
    "#onErrorComplete",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorComplete.js.html#lineNumber12",
    "#onErrorComplete should create a Completable",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorComplete.js.html#lineNumber48",
    "#onErrorComplete should emit error if provide function returns undefined.",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorComplete.js.html#lineNumber38",
    "#onErrorComplete should emit error if provide function throws error.",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorComplete.js.html#lineNumber27",
    "#onErrorComplete should emit the supplied item by the given function in case of error",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorComplete.js.html#lineNumber19",
    "#onErrorComplete should return the same instance if parameter passed is not a Completable or a function",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorResumeNext.js.html#lineNumber8",
    "#onErrorResumeNext",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorResumeNext.js.html#lineNumber12",
    "#onErrorResumeNext should create a Completable",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorResumeNext.js.html#lineNumber57",
    "#onErrorResumeNext should emit error if provide function returns non-Completable.",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorResumeNext.js.html#lineNumber47",
    "#onErrorResumeNext should emit error if provide function throws error.",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorResumeNext.js.html#lineNumber67",
    "#onErrorResumeNext should not resume if source does not throw error",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorResumeNext.js.html#lineNumber19",
    "#onErrorResumeNext should return the same instance if parameter passed is not a Completable or a function",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorResumeNext.js.html#lineNumber27",
    "#onErrorResumeNext should subscribe to the given Completable",
    "test"
  ],
  [
    "",
    "test-file/test/onErrorResumeNext.js.html#lineNumber37",
    "#onErrorResumeNext should subscribe to the given Completable-producing Function",
    "test"
  ],
  [
    "",
    "test-file/test/repeat.js.html#lineNumber9",
    "#repeat",
    "test"
  ],
  [
    "",
    "test-file/test/repeat.js.html#lineNumber13",
    "#repeat should create a Completable",
    "test"
  ],
  [
    "",
    "test-file/test/repeat.js.html#lineNumber48",
    "#repeat should emit error",
    "test"
  ],
  [
    "",
    "test-file/test/repeat.js.html#lineNumber36",
    "#repeat should repeat with the given amount and completes",
    "test"
  ],
  [
    "",
    "test-file/test/repeat.js.html#lineNumber28",
    "#repeat should return the same instance if the amount is a number and not positive",
    "test"
  ],
  [
    "",
    "test-file/test/repeat.js.html#lineNumber20",
    "#repeat should return the same instance if the amount is not a number and not undefined.",
    "test"
  ],
  [
    "",
    "test-file/test/repeatUntil.js.html#lineNumber9",
    "#repeatUntil",
    "test"
  ],
  [
    "",
    "test-file/test/repeatUntil.js.html#lineNumber13",
    "#repeatUntil should create a Completable",
    "test"
  ],
  [
    "",
    "test-file/test/repeatUntil.js.html#lineNumber32",
    "#repeatUntil should emit error",
    "test"
  ],
  [
    "",
    "test-file/test/repeatUntil.js.html#lineNumber20",
    "#repeatUntil should repeatUntil with the predicate returns true",
    "test"
  ],
  [
    "",
    "test-file/test/retry.js.html#lineNumber8",
    "#retry",
    "test"
  ],
  [
    "",
    "test-file/test/retry.js.html#lineNumber12",
    "#retry should create a Completable",
    "test"
  ],
  [
    "",
    "test-file/test/retry.js.html#lineNumber31",
    "#retry should retry if there is an error and if it passes the predicate",
    "test"
  ],
  [
    "",
    "test-file/test/retry.js.html#lineNumber20",
    "#retry should signal a complete if no error",
    "test"
  ],
  [
    "",
    "test-file/test/retry.js.html#lineNumber48",
    "#retry should signal an error if predicate is false",
    "test"
  ],
  [
    "",
    "test-file/test/startWith.js.html#lineNumber8",
    "#startWith",
    "test"
  ],
  [
    "",
    "test-file/test/startWith.js.html#lineNumber12",
    "#startWith should create a Completable",
    "test"
  ],
  [
    "",
    "test-file/test/startWith.js.html#lineNumber41",
    "#startWith should error with the other Completable if the other throws an error",
    "test"
  ],
  [
    "",
    "test-file/test/startWith.js.html#lineNumber54",
    "#startWith should error with the source Completable if the source throws an error",
    "test"
  ],
  [
    "",
    "test-file/test/startWith.js.html#lineNumber20",
    "#startWith should return the same instance if the given completable is a non-Completable",
    "test"
  ],
  [
    "",
    "test-file/test/startWith.js.html#lineNumber28",
    "#startWith should start with the other Completable.",
    "test"
  ],
  [
    "",
    "test-file/test/takeUntil.js.html#lineNumber8",
    "#takeUntil",
    "test"
  ],
  [
    "",
    "test-file/test/takeUntil.js.html#lineNumber12",
    "#takeUntil should create a Completable",
    "test"
  ],
  [
    "",
    "test-file/test/takeUntil.js.html#lineNumber20",
    "#takeUntil should return the same instance if no other Completable is provided",
    "test"
  ],
  [
    "",
    "test-file/test/takeUntil.js.html#lineNumber29",
    "#takeUntil should signal complete if other Completable has not emitted a complete signal",
    "test"
  ],
  [
    "",
    "test-file/test/takeUntil.js.html#lineNumber40",
    "#takeUntil should signal complete if other Completable has not emitted an error signal",
    "test"
  ],
  [
    "",
    "test-file/test/takeUntil.js.html#lineNumber51",
    "#takeUntil should signal error if other Completable has emitted a complete signal",
    "test"
  ],
  [
    "",
    "test-file/test/takeUntil.js.html#lineNumber62",
    "#takeUntil should signal error if other Completable has emitted an error signal",
    "test"
  ],
  [
    "",
    "test-file/test/takeUntil.js.html#lineNumber73",
    "#takeUntil should signal error if source signals error, nonetheless",
    "test"
  ],
  [
    "",
    "test-file/test/then.js.html#lineNumber8",
    "#then",
    "test"
  ],
  [
    "",
    "test-file/test/then.js.html#lineNumber12",
    "#then should create a Promise",
    "test"
  ],
  [
    "",
    "test-file/test/timeout.js.html#lineNumber9",
    "#timeout",
    "test"
  ],
  [
    "",
    "test-file/test/timeout.js.html#lineNumber13",
    "#timeout should create a Completable",
    "test"
  ],
  [
    "",
    "test-file/test/timeout.js.html#lineNumber58",
    "#timeout should not signal complete if aborted.",
    "test"
  ],
  [
    "",
    "test-file/test/timeout.js.html#lineNumber73",
    "#timeout should not signal error if aborted.",
    "test"
  ],
  [
    "",
    "test-file/test/timeout.js.html#lineNumber20",
    "#timeout should return the same instance if the amount is not a number.",
    "test"
  ],
  [
    "",
    "test-file/test/timeout.js.html#lineNumber28",
    "#timeout should signal complete with the given value.",
    "test"
  ],
  [
    "",
    "test-file/test/timeout.js.html#lineNumber48",
    "#timeout should signal error if the Completable does complete after the given timeout.",
    "test"
  ],
  [
    "",
    "test-file/test/timeout.js.html#lineNumber38",
    "#timeout should signal error with the given value.",
    "test"
  ],
  [
    "",
    "test-file/test/timer.js.html#lineNumber8",
    "#timer",
    "test"
  ],
  [
    "",
    "test-file/test/timer.js.html#lineNumber12",
    "#timer should create a Completable",
    "test"
  ],
  [
    "",
    "test-file/test/timer.js.html#lineNumber40",
    "#timer should not signal complete if aborted.",
    "test"
  ],
  [
    "",
    "test-file/test/timer.js.html#lineNumber30",
    "#timer should signal complete",
    "test"
  ],
  [
    "",
    "test-file/test/timer.js.html#lineNumber19",
    "#timer should signal error if amount is not a number.",
    "test"
  ],
  [
    "",
    "test-file/test/toPromise.js.html#lineNumber8",
    "#toPromise",
    "test"
  ],
  [
    "",
    "test-file/test/toPromise.js.html#lineNumber12",
    "#toPromise should create a Promise",
    "test"
  ],
  [
    "rx-completable/src/completable.js~completable",
    "class/src/completable.js~Completable.html",
    "<span>Completable</span> <span class=\"search-result-import-path\">rx-completable/src/completable.js</span>",
    "class"
  ],
  [
    "rx-completable/src/emitter.js~emitter",
    "class/src/emitter.js~Emitter.html",
    "<span>Emitter</span> <span class=\"search-result-import-path\">rx-completable/src/emitter.js</span>",
    "class"
  ],
  [
    "rx-completable/src/observer.js~observer",
    "class/src/observer.js~Observer.html",
    "<span>Observer</span> <span class=\"search-result-import-path\">rx-completable/src/observer.js</span>",
    "class"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/completable.js",
    "file/src/completable.js.html",
    "src/completable.js",
    "file"
  ],
  [
    "src/completable.js~abortcontroller",
    "https://developer.mozilla.org/en-US/docs/Web/API/AbortController",
    "src/completable.js~AbortController",
    "external"
  ],
  [
    "src/completable.js~completable#ambwith",
    "class/src/completable.js~Completable.html#instance-method-ambWith",
    "src/completable.js~Completable#ambWith",
    "method"
  ],
  [
    "src/completable.js~completable#andthen",
    "class/src/completable.js~Completable.html#instance-method-andThen",
    "src/completable.js~Completable#andThen",
    "method"
  ],
  [
    "src/completable.js~completable#cache",
    "class/src/completable.js~Completable.html#instance-method-cache",
    "src/completable.js~Completable#cache",
    "method"
  ],
  [
    "src/completable.js~completable#catch",
    "class/src/completable.js~Completable.html#instance-method-catch",
    "src/completable.js~Completable#catch",
    "method"
  ],
  [
    "src/completable.js~completable#compose",
    "class/src/completable.js~Completable.html#instance-method-compose",
    "src/completable.js~Completable#compose",
    "method"
  ],
  [
    "src/completable.js~completable#concatwith",
    "class/src/completable.js~Completable.html#instance-method-concatWith",
    "src/completable.js~Completable#concatWith",
    "method"
  ],
  [
    "src/completable.js~completable#delay",
    "class/src/completable.js~Completable.html#instance-method-delay",
    "src/completable.js~Completable#delay",
    "method"
  ],
  [
    "src/completable.js~completable#delaysubscription",
    "class/src/completable.js~Completable.html#instance-method-delaySubscription",
    "src/completable.js~Completable#delaySubscription",
    "method"
  ],
  [
    "src/completable.js~completable#doafterterminate",
    "class/src/completable.js~Completable.html#instance-method-doAfterTerminate",
    "src/completable.js~Completable#doAfterTerminate",
    "method"
  ],
  [
    "src/completable.js~completable#dofinally",
    "class/src/completable.js~Completable.html#instance-method-doFinally",
    "src/completable.js~Completable#doFinally",
    "method"
  ],
  [
    "src/completable.js~completable#doonabort",
    "class/src/completable.js~Completable.html#instance-method-doOnAbort",
    "src/completable.js~Completable#doOnAbort",
    "method"
  ],
  [
    "src/completable.js~completable#dooncomplete",
    "class/src/completable.js~Completable.html#instance-method-doOnComplete",
    "src/completable.js~Completable#doOnComplete",
    "method"
  ],
  [
    "src/completable.js~completable#doonerror",
    "class/src/completable.js~Completable.html#instance-method-doOnError",
    "src/completable.js~Completable#doOnError",
    "method"
  ],
  [
    "src/completable.js~completable#doonevent",
    "class/src/completable.js~Completable.html#instance-method-doOnEvent",
    "src/completable.js~Completable#doOnEvent",
    "method"
  ],
  [
    "src/completable.js~completable#doonsubscribe",
    "class/src/completable.js~Completable.html#instance-method-doOnSubscribe",
    "src/completable.js~Completable#doOnSubscribe",
    "method"
  ],
  [
    "src/completable.js~completable#doonterminate",
    "class/src/completable.js~Completable.html#instance-method-doOnTerminate",
    "src/completable.js~Completable#doOnTerminate",
    "method"
  ],
  [
    "src/completable.js~completable#lift",
    "class/src/completable.js~Completable.html#instance-method-lift",
    "src/completable.js~Completable#lift",
    "method"
  ],
  [
    "src/completable.js~completable#mergewith",
    "class/src/completable.js~Completable.html#instance-method-mergeWith",
    "src/completable.js~Completable#mergeWith",
    "method"
  ],
  [
    "src/completable.js~completable#onerrorcomplete",
    "class/src/completable.js~Completable.html#instance-method-onErrorComplete",
    "src/completable.js~Completable#onErrorComplete",
    "method"
  ],
  [
    "src/completable.js~completable#onerrorresumenext",
    "class/src/completable.js~Completable.html#instance-method-onErrorResumeNext",
    "src/completable.js~Completable#onErrorResumeNext",
    "method"
  ],
  [
    "src/completable.js~completable#repeat",
    "class/src/completable.js~Completable.html#instance-method-repeat",
    "src/completable.js~Completable#repeat",
    "method"
  ],
  [
    "src/completable.js~completable#repeatuntil",
    "class/src/completable.js~Completable.html#instance-method-repeatUntil",
    "src/completable.js~Completable#repeatUntil",
    "method"
  ],
  [
    "src/completable.js~completable#retry",
    "class/src/completable.js~Completable.html#instance-method-retry",
    "src/completable.js~Completable#retry",
    "method"
  ],
  [
    "src/completable.js~completable#startwith",
    "class/src/completable.js~Completable.html#instance-method-startWith",
    "src/completable.js~Completable#startWith",
    "method"
  ],
  [
    "src/completable.js~completable#subscribe",
    "class/src/completable.js~Completable.html#instance-method-subscribe",
    "src/completable.js~Completable#subscribe",
    "method"
  ],
  [
    "src/completable.js~completable#subscribeactual",
    "class/src/completable.js~Completable.html#instance-member-subscribeActual",
    "src/completable.js~Completable#subscribeActual",
    "member"
  ],
  [
    "src/completable.js~completable#subscribewith",
    "class/src/completable.js~Completable.html#instance-method-subscribeWith",
    "src/completable.js~Completable#subscribeWith",
    "method"
  ],
  [
    "src/completable.js~completable#takeuntil",
    "class/src/completable.js~Completable.html#instance-method-takeUntil",
    "src/completable.js~Completable#takeUntil",
    "method"
  ],
  [
    "src/completable.js~completable#then",
    "class/src/completable.js~Completable.html#instance-method-then",
    "src/completable.js~Completable#then",
    "method"
  ],
  [
    "src/completable.js~completable#timeout",
    "class/src/completable.js~Completable.html#instance-method-timeout",
    "src/completable.js~Completable#timeout",
    "method"
  ],
  [
    "src/completable.js~completable#topromise",
    "class/src/completable.js~Completable.html#instance-method-toPromise",
    "src/completable.js~Completable#toPromise",
    "method"
  ],
  [
    "src/completable.js~completable.amb",
    "class/src/completable.js~Completable.html#static-method-amb",
    "src/completable.js~Completable.amb",
    "method"
  ],
  [
    "src/completable.js~completable.complete",
    "class/src/completable.js~Completable.html#static-method-complete",
    "src/completable.js~Completable.complete",
    "method"
  ],
  [
    "src/completable.js~completable.concat",
    "class/src/completable.js~Completable.html#static-method-concat",
    "src/completable.js~Completable.concat",
    "method"
  ],
  [
    "src/completable.js~completable.create",
    "class/src/completable.js~Completable.html#static-method-create",
    "src/completable.js~Completable.create",
    "method"
  ],
  [
    "src/completable.js~completable.defer",
    "class/src/completable.js~Completable.html#static-method-defer",
    "src/completable.js~Completable.defer",
    "method"
  ],
  [
    "src/completable.js~completable.error",
    "class/src/completable.js~Completable.html#static-method-error",
    "src/completable.js~Completable.error",
    "method"
  ],
  [
    "src/completable.js~completable.fromcallable",
    "class/src/completable.js~Completable.html#static-method-fromCallable",
    "src/completable.js~Completable.fromCallable",
    "method"
  ],
  [
    "src/completable.js~completable.frompromise",
    "class/src/completable.js~Completable.html#static-method-fromPromise",
    "src/completable.js~Completable.fromPromise",
    "method"
  ],
  [
    "src/completable.js~completable.fromresolvable",
    "class/src/completable.js~Completable.html#static-method-fromResolvable",
    "src/completable.js~Completable.fromResolvable",
    "method"
  ],
  [
    "src/completable.js~completable.merge",
    "class/src/completable.js~Completable.html#static-method-merge",
    "src/completable.js~Completable.merge",
    "method"
  ],
  [
    "src/completable.js~completable.never",
    "class/src/completable.js~Completable.html#static-method-never",
    "src/completable.js~Completable.never",
    "method"
  ],
  [
    "src/completable.js~completable.timer",
    "class/src/completable.js~Completable.html#static-method-timer",
    "src/completable.js~Completable.timer",
    "method"
  ],
  [
    "src/completable.js~iterable",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols",
    "src/completable.js~Iterable",
    "external"
  ],
  [
    "src/completable.js~promiselike",
    "https://promisesaplus.com/",
    "src/completable.js~PromiseLike",
    "external"
  ],
  [
    "src/completable.js~thennable",
    "https://promisesaplus.com/",
    "src/completable.js~Thennable",
    "external"
  ],
  [
    "src/emitter.js",
    "file/src/emitter.js.html",
    "src/emitter.js",
    "file"
  ],
  [
    "src/emitter.js~emitter#oncomplete",
    "class/src/emitter.js~Emitter.html#instance-method-onComplete",
    "src/emitter.js~Emitter#onComplete",
    "method"
  ],
  [
    "src/emitter.js~emitter#onerror",
    "class/src/emitter.js~Emitter.html#instance-method-onError",
    "src/emitter.js~Emitter#onError",
    "method"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/internal/operators.js",
    "file/src/internal/operators.js.html",
    "src/internal/operators.js",
    "file"
  ],
  [
    "src/internal/operators/amb.js",
    "file/src/internal/operators/amb.js.html",
    "src/internal/operators/amb.js",
    "file"
  ],
  [
    "src/internal/operators/ambwith.js",
    "file/src/internal/operators/ambWith.js.html",
    "src/internal/operators/ambWith.js",
    "file"
  ],
  [
    "src/internal/operators/andthen.js",
    "file/src/internal/operators/andThen.js.html",
    "src/internal/operators/andThen.js",
    "file"
  ],
  [
    "src/internal/operators/cache.js",
    "file/src/internal/operators/cache.js.html",
    "src/internal/operators/cache.js",
    "file"
  ],
  [
    "src/internal/operators/complete.js",
    "file/src/internal/operators/complete.js.html",
    "src/internal/operators/complete.js",
    "file"
  ],
  [
    "src/internal/operators/compose.js",
    "file/src/internal/operators/compose.js.html",
    "src/internal/operators/compose.js",
    "file"
  ],
  [
    "src/internal/operators/concat.js",
    "file/src/internal/operators/concat.js.html",
    "src/internal/operators/concat.js",
    "file"
  ],
  [
    "src/internal/operators/create.js",
    "file/src/internal/operators/create.js.html",
    "src/internal/operators/create.js",
    "file"
  ],
  [
    "src/internal/operators/defer.js",
    "file/src/internal/operators/defer.js.html",
    "src/internal/operators/defer.js",
    "file"
  ],
  [
    "src/internal/operators/delay.js",
    "file/src/internal/operators/delay.js.html",
    "src/internal/operators/delay.js",
    "file"
  ],
  [
    "src/internal/operators/delaysubscription.js",
    "file/src/internal/operators/delaySubscription.js.html",
    "src/internal/operators/delaySubscription.js",
    "file"
  ],
  [
    "src/internal/operators/doafterterminate.js",
    "file/src/internal/operators/doAfterTerminate.js.html",
    "src/internal/operators/doAfterTerminate.js",
    "file"
  ],
  [
    "src/internal/operators/dofinally.js",
    "file/src/internal/operators/doFinally.js.html",
    "src/internal/operators/doFinally.js",
    "file"
  ],
  [
    "src/internal/operators/doonabort.js",
    "file/src/internal/operators/doOnAbort.js.html",
    "src/internal/operators/doOnAbort.js",
    "file"
  ],
  [
    "src/internal/operators/dooncomplete.js",
    "file/src/internal/operators/doOnComplete.js.html",
    "src/internal/operators/doOnComplete.js",
    "file"
  ],
  [
    "src/internal/operators/doonerror.js",
    "file/src/internal/operators/doOnError.js.html",
    "src/internal/operators/doOnError.js",
    "file"
  ],
  [
    "src/internal/operators/doonevent.js",
    "file/src/internal/operators/doOnEvent.js.html",
    "src/internal/operators/doOnEvent.js",
    "file"
  ],
  [
    "src/internal/operators/doonsubscribe.js",
    "file/src/internal/operators/doOnSubscribe.js.html",
    "src/internal/operators/doOnSubscribe.js",
    "file"
  ],
  [
    "src/internal/operators/doonterminate.js",
    "file/src/internal/operators/doOnTerminate.js.html",
    "src/internal/operators/doOnTerminate.js",
    "file"
  ],
  [
    "src/internal/operators/error.js",
    "file/src/internal/operators/error.js.html",
    "src/internal/operators/error.js",
    "file"
  ],
  [
    "src/internal/operators/fromcallable.js",
    "file/src/internal/operators/fromCallable.js.html",
    "src/internal/operators/fromCallable.js",
    "file"
  ],
  [
    "src/internal/operators/frompromise.js",
    "file/src/internal/operators/fromPromise.js.html",
    "src/internal/operators/fromPromise.js",
    "file"
  ],
  [
    "src/internal/operators/fromresolvable.js",
    "file/src/internal/operators/fromResolvable.js.html",
    "src/internal/operators/fromResolvable.js",
    "file"
  ],
  [
    "src/internal/operators/lift.js",
    "file/src/internal/operators/lift.js.html",
    "src/internal/operators/lift.js",
    "file"
  ],
  [
    "src/internal/operators/merge.js",
    "file/src/internal/operators/merge.js.html",
    "src/internal/operators/merge.js",
    "file"
  ],
  [
    "src/internal/operators/mergewith.js",
    "file/src/internal/operators/mergeWith.js.html",
    "src/internal/operators/mergeWith.js",
    "file"
  ],
  [
    "src/internal/operators/never.js",
    "file/src/internal/operators/never.js.html",
    "src/internal/operators/never.js",
    "file"
  ],
  [
    "src/internal/operators/onerrorcomplete.js",
    "file/src/internal/operators/onErrorComplete.js.html",
    "src/internal/operators/onErrorComplete.js",
    "file"
  ],
  [
    "src/internal/operators/onerrorresumenext.js",
    "file/src/internal/operators/onErrorResumeNext.js.html",
    "src/internal/operators/onErrorResumeNext.js",
    "file"
  ],
  [
    "src/internal/operators/repeat.js",
    "file/src/internal/operators/repeat.js.html",
    "src/internal/operators/repeat.js",
    "file"
  ],
  [
    "src/internal/operators/repeatuntil.js",
    "file/src/internal/operators/repeatUntil.js.html",
    "src/internal/operators/repeatUntil.js",
    "file"
  ],
  [
    "src/internal/operators/retry.js",
    "file/src/internal/operators/retry.js.html",
    "src/internal/operators/retry.js",
    "file"
  ],
  [
    "src/internal/operators/startwith.js",
    "file/src/internal/operators/startWith.js.html",
    "src/internal/operators/startWith.js",
    "file"
  ],
  [
    "src/internal/operators/takeuntil.js",
    "file/src/internal/operators/takeUntil.js.html",
    "src/internal/operators/takeUntil.js",
    "file"
  ],
  [
    "src/internal/operators/timeout.js",
    "file/src/internal/operators/timeout.js.html",
    "src/internal/operators/timeout.js",
    "file"
  ],
  [
    "src/internal/operators/timer.js",
    "file/src/internal/operators/timer.js.html",
    "src/internal/operators/timer.js",
    "file"
  ],
  [
    "src/internal/utils.js",
    "file/src/internal/utils.js.html",
    "src/internal/utils.js",
    "file"
  ],
  [
    "src/observer.js",
    "file/src/observer.js.html",
    "src/observer.js",
    "file"
  ],
  [
    "src/observer.js~observer#oncomplete",
    "class/src/observer.js~Observer.html#instance-method-onComplete",
    "src/observer.js~Observer#onComplete",
    "method"
  ],
  [
    "src/observer.js~observer#onerror",
    "class/src/observer.js~Observer.html#instance-method-onError",
    "src/observer.js~Observer#onError",
    "method"
  ],
  [
    "src/observer.js~observer#onsubscribe",
    "class/src/observer.js~Observer.html#instance-method-onSubscribe",
    "src/observer.js~Observer#onSubscribe",
    "method"
  ],
  [
    "test/amb.js",
    "test-file/test/amb.js.html",
    "test/amb.js",
    "testFile"
  ],
  [
    "test/ambwith.js",
    "test-file/test/ambWith.js.html",
    "test/ambWith.js",
    "testFile"
  ],
  [
    "test/andthen.js",
    "test-file/test/andThen.js.html",
    "test/andThen.js",
    "testFile"
  ],
  [
    "test/cache.js",
    "test-file/test/cache.js.html",
    "test/cache.js",
    "testFile"
  ],
  [
    "test/catch.js",
    "test-file/test/catch.js.html",
    "test/catch.js",
    "testFile"
  ],
  [
    "test/compose.js",
    "test-file/test/compose.js.html",
    "test/compose.js",
    "testFile"
  ],
  [
    "test/concat.js",
    "test-file/test/concat.js.html",
    "test/concat.js",
    "testFile"
  ],
  [
    "test/concatwith.js",
    "test-file/test/concatWith.js.html",
    "test/concatWith.js",
    "testFile"
  ],
  [
    "test/create.js",
    "test-file/test/create.js.html",
    "test/create.js",
    "testFile"
  ],
  [
    "test/defer.js",
    "test-file/test/defer.js.html",
    "test/defer.js",
    "testFile"
  ],
  [
    "test/delay.js",
    "test-file/test/delay.js.html",
    "test/delay.js",
    "testFile"
  ],
  [
    "test/delaysubscription.js",
    "test-file/test/delaySubscription.js.html",
    "test/delaySubscription.js",
    "testFile"
  ],
  [
    "test/doafterterminate.js",
    "test-file/test/doAfterTerminate.js.html",
    "test/doAfterTerminate.js",
    "testFile"
  ],
  [
    "test/dofinally.js",
    "test-file/test/doFinally.js.html",
    "test/doFinally.js",
    "testFile"
  ],
  [
    "test/doonabort.js",
    "test-file/test/doOnAbort.js.html",
    "test/doOnAbort.js",
    "testFile"
  ],
  [
    "test/dooncomplete.js",
    "test-file/test/doOnComplete.js.html",
    "test/doOnComplete.js",
    "testFile"
  ],
  [
    "test/doonerror.js",
    "test-file/test/doOnError.js.html",
    "test/doOnError.js",
    "testFile"
  ],
  [
    "test/doonevent.js",
    "test-file/test/doOnEvent.js.html",
    "test/doOnEvent.js",
    "testFile"
  ],
  [
    "test/doonsubscribe.js",
    "test-file/test/doOnSubscribe.js.html",
    "test/doOnSubscribe.js",
    "testFile"
  ],
  [
    "test/doonterminate.js",
    "test-file/test/doOnTerminate.js.html",
    "test/doOnTerminate.js",
    "testFile"
  ],
  [
    "test/error.js",
    "test-file/test/error.js.html",
    "test/error.js",
    "testFile"
  ],
  [
    "test/fromcallable.js",
    "test-file/test/fromCallable.js.html",
    "test/fromCallable.js",
    "testFile"
  ],
  [
    "test/frompromise.js",
    "test-file/test/fromPromise.js.html",
    "test/fromPromise.js",
    "testFile"
  ],
  [
    "test/fromresolvable.js",
    "test-file/test/fromResolvable.js.html",
    "test/fromResolvable.js",
    "testFile"
  ],
  [
    "test/lift.js",
    "test-file/test/lift.js.html",
    "test/lift.js",
    "testFile"
  ],
  [
    "test/merge.js",
    "test-file/test/merge.js.html",
    "test/merge.js",
    "testFile"
  ],
  [
    "test/mergewith.js",
    "test-file/test/mergeWith.js.html",
    "test/mergeWith.js",
    "testFile"
  ],
  [
    "test/never.js",
    "test-file/test/never.js.html",
    "test/never.js",
    "testFile"
  ],
  [
    "test/onerrorcomplete.js",
    "test-file/test/onErrorComplete.js.html",
    "test/onErrorComplete.js",
    "testFile"
  ],
  [
    "test/onerrorresumenext.js",
    "test-file/test/onErrorResumeNext.js.html",
    "test/onErrorResumeNext.js",
    "testFile"
  ],
  [
    "test/repeat.js",
    "test-file/test/repeat.js.html",
    "test/repeat.js",
    "testFile"
  ],
  [
    "test/repeatuntil.js",
    "test-file/test/repeatUntil.js.html",
    "test/repeatUntil.js",
    "testFile"
  ],
  [
    "test/retry.js",
    "test-file/test/retry.js.html",
    "test/retry.js",
    "testFile"
  ],
  [
    "test/startwith.js",
    "test-file/test/startWith.js.html",
    "test/startWith.js",
    "testFile"
  ],
  [
    "test/takeuntil.js",
    "test-file/test/takeUntil.js.html",
    "test/takeUntil.js",
    "testFile"
  ],
  [
    "test/then.js",
    "test-file/test/then.js.html",
    "test/then.js",
    "testFile"
  ],
  [
    "test/timeout.js",
    "test-file/test/timeout.js.html",
    "test/timeout.js",
    "testFile"
  ],
  [
    "test/timer.js",
    "test-file/test/timer.js.html",
    "test/timer.js",
    "testFile"
  ],
  [
    "test/topromise.js",
    "test-file/test/toPromise.js.html",
    "test/toPromise.js",
    "testFile"
  ]
]